<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://schemi.processotelematico.giustizia.it/cassazione/tipi/allegati/v7" 
xmlns:at="http://schemi.processotelematico.giustizia.it/cassazione/tipi/anagrafiche/v7" 
xmlns:bt="http://schemi.processotelematico.giustizia.it/cassazione/tipi/v7" 
xmlns:pt="http://schemi.processotelematico.giustizia.it/cassazione/tipi/atti/v7" 
xmlns:xs="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://schemi.processotelematico.giustizia.it/cassazione/tipi/allegati/v7" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<xs:import namespace="http://schemi.processotelematico.giustizia.it/cassazione/tipi/v7" schemaLocation="./tipi-base.xsd"/>
	<xs:import namespace="http://schemi.processotelematico.giustizia.it/cassazione/tipi/anagrafiche/v7" schemaLocation="./tipi-anagrafiche.xsd"/>
	<xs:complexType name="IndiceBusta">
		<xs:annotation>
			<xs:documentation>Informazioni sui documenti che compongono la busta</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="AttoPrincipale" type="bt:RiferimentoAllegato">
				<xs:annotation>
					<xs:documentation>Riferimento all'atto principale nella busta</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:any namespace="##targetNamespace" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Riferimenti ad altri allegati presenti nella busta</xs:documentation>
				</xs:annotation>
			</xs:any>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SoggettoNotificato">
		<xs:annotation>
			<xs:documentation>Informazioni del soggetto notificato</xs:documentation>
		</xs:annotation>
		<xs:attribute name="codiceFiscale" type="bt:CodiceFiscale" use="required"/>
		<xs:attribute name="indirizzoPec" type="bt:IndirizzoEmail" use="required"/>
		<xs:attribute name="pubblicoElenco" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="INIPEC-professionisti"/>
					<xs:enumeration value="RegistroImprese"/>
					<xs:enumeration value="RegInde"/>
					<xs:enumeration value="IPA"/>
					<xs:enumeration value="altro"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="AllegatoSemplice" type="bt:RiferimentoAllegato">
		<xs:annotation>
			<xs:documentation>Riferimento ad un allegato semplice - può essere firmato da chiunque</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="NotaIscrizioneRuolo" type="bt:RiferimentoAllegato">
		<xs:annotation>
			<xs:documentation>Riferimento all'allegato per la nota di iscrizione a ruolo - la deve firmare il depositante</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="ProcuraSpeciale" type="bt:RiferimentoAllegato">
		<xs:annotation>
			<xs:documentation>Riferimento all'allegato per la procura speciale - la deve firmare il depositante</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="CopiaProvvedimento" type="bt:RiferimentoAllegato">
		<xs:annotation>
			<xs:documentation>Riferimento all'allegato della copia autentica del provvedimento impugnato - la deve firmare il depositante</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="IstanzaExArt369" type="bt:RiferimentoAllegato">
		<xs:annotation>
			<xs:documentation>Riferimento all'allegato di istanza ex art. 369 c.p.c. - può essere firmato dal depositante</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="IstanzaGratuitoPatrocinio" type="bt:RiferimentoAllegato">
		<xs:annotation>
			<xs:documentation>Riferimento all'allegato di istanza per il gratuito patrocinio - può essere firmato dal depositante</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="IstanzaSollecitaFissazione" type="bt:RiferimentoAllegato">
		<xs:annotation>
			<xs:documentation>Riferimento all'allegato di istanza per sollecitare la fissazione dell'udienza - può essere firmato dal depositante</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="IstanzaRiunioneRicorsi" type="bt:RiferimentoAllegato">
		<xs:annotation>
			<xs:documentation>Riferimento all'allegato di istanza per la riunione di ricorsi - può essere firmato dal depositante</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="RicevutaPagamento" type="bt:RiferimentoAllegato">
		<xs:annotation>
			<xs:documentation>Riferimento all'allegato di ricevuta di pagamento elettronica - la deve firmare il depositante</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="NotificaAccettazione">
		<xs:annotation>
			<xs:documentation>Riferimento all'allegato di ricevuta di accettazione (PEC) - può essere firmato dal depositante</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="bt:RiferimentoAllegato">
					<xs:sequence>
						<xs:element name="SoggettoNotificato" type="SoggettoNotificato" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="NotificaConsegna">
		<xs:annotation>
			<xs:documentation>Riferimento all'allegato di ricevuta di avvenuta consegna (PEC) - può essere firmato dal depositante</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="bt:RiferimentoAllegato">
					<xs:sequence>
						<xs:element name="SoggettoNotificato" type="SoggettoNotificato"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="PatrocinioSpeseStato" type="bt:RiferimentoAllegato">
		<xs:annotation>
			<xs:documentation>Riferimento all'allegato di ricevuta di pagamento elettronica - la deve firmare il depositante</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="ProcuraAttoPubblico" type="bt:RiferimentoAllegato">
		<xs:annotation>
			<xs:documentation>Procura atto pubblico - può essere firmato da chiunque</xs:documentation>
		</xs:annotation>
	</xs:element>
</xs:schema>
