"""Atti del processo civile ordinario, monitorio, cautelare e delle impugnazioni."""

from __future__ import annotations

from pct.fascicoli import TipoDocumento

from ._modello import regola

REGOLE = (
    regola(
        "ricorso_decreto_ingiuntivo",
        r"ricorso\s+per\s+(?:decreto\s+)?ingiuntivo(?:\s+.*)?|ricorso\s+per\s+ingiunzione(?:\s+di\s+pagamento)?(?:\s+.*)?",
        r"\bingiung\w+\b|\bcreditor\w*\b|\b63[3-9]\b",
        "Ricorso per decreto ingiuntivo",
        role="atto_principale", section="atti", tipo=TipoDocumento.RICORSO,
        fonte="cpc_procedimento_monitorio", deposit_role="atto_principale",
        evidence="titolo del ricorso monitorio e domanda di ingiunzione (art. 633 c.p.c.)",
    ),
    regola(
        "decreto_ingiuntivo",
        r"decreto\s+ingiuntivo(?:\s+.*)?",
        r"\bingiunge\b|\bingiungiamo\b",
        "Decreto ingiuntivo",
        role="provvedimento", section="provvedimenti", tipo=TipoDocumento.DECRETO,
        fonte="cpc_procedimento_monitorio", deposit_role="fuori_busta", deposit_candidate=False,
        evidence="titolo del decreto e formula «ingiunge» del giudice (art. 641 c.p.c.)",
    ),
    regola(
        "opposizione_decreto_ingiuntivo",
        r"(?:atto\s+di\s+citazione\s+in\s+)?opposizione\s+a\s+decreto\s+ingiuntivo(?:\s+.*)?|atto\s+di\s+citazione\s+in\s+opposizione(?:\s+.*)?",
        r"\bopponent\w+\b|\boppost\w+\b|\b645\b|\bdecreto\s+ingiuntivo\b",
        "Opposizione a decreto ingiuntivo",
        role="atto_principale", section="atti", tipo=TipoDocumento.CITAZIONE,
        fonte="normattiva_cpc_opposizione_decreto_ingiuntivo", deposit_role="atto_principale",
        evidence="titolo dell'atto e opposizione al decreto (art. 645 c.p.c.)",
    ),
    regola(
        "ricorso_696bis",
        r"ricorso\s+(?:per\s+)?(?:consulenza\s+tecnica\s+preventiva|accertamento\s+tecnico\s+preventivo|ex\s+art\.?\s*696)(?:\s+.*)?",
        r"\b696\b|\bconsulente\b|\baccertamento\b",
        "Ricorso per consulenza tecnica preventiva (art. 696-bis c.p.c.)",
        role="atto_principale", section="atti", tipo=TipoDocumento.RICORSO,
        fonte="normattiva_cpc_consulenza_tecnica", deposit_role="atto_principale",
        evidence="titolo del ricorso e richiesta di consulenza tecnica preventiva",
    ),
    regola(
        "ricorso_700",
        r"ricorso\s+(?:ex\s+|ai\s+sensi\s+dell.?\s*)?art\.?\s*700(?:\s+.*)?|ricorso\s+per\s+provvedimento\s+d.?\s*urgenza(?:\s+.*)?|ricorso\s+cautelare(?:\s+.*)?",
        r"\bpericulum\b|\burgen\w+\b|\b700\b|\bfumus\b|\bcautelar\w+\b",
        "Ricorso cautelare ex art. 700 c.p.c.",
        role="atto_principale", section="atti", tipo=TipoDocumento.RICORSO,
        fonte="normattiva_cpc_cautelari", deposit_role="atto_principale",
        evidence="titolo del ricorso e presupposti cautelari (art. 700 c.p.c.)",
    ),
    regola(
        "ricorso_sequestro",
        r"ricorso\s+per\s+sequestro(?:\s+(?:conservativo|giudiziario))?(?:\s+.*)?",
        r"\bsequestr\w+\b|\bpericulum\b|\bcredit\w+\b",
        "Ricorso per sequestro",
        role="atto_principale", section="atti", tipo=TipoDocumento.RICORSO,
        fonte="normattiva_cpc_cautelari", deposit_role="atto_principale",
        evidence="titolo del ricorso e misura di sequestro (art. 671 c.p.c.)",
    ),
    regola(
        "reclamo_cautelare",
        r"reclamo(?:\s+(?:ex\s+art\.?\s*669[\s.-]*terdecies|cautelare|avverso).*)?",
        r"\b669\b|\bordinanza\b|\bcautelar\w+\b|\breclam\w+\b",
        "Reclamo cautelare",
        role="atto_principale", section="atti", tipo=TipoDocumento.RICORSO,
        fonte="normattiva_cpc_cautelari", deposit_role="atto_principale",
        evidence="titolo del reclamo e ordinanza reclamata (art. 669-terdecies c.p.c.)",
    ),
    regola(
        "comparsa_conclusionale",
        r"comparsa\s+conclusionale(?:\s+.*)?",
        r"\bconclusion\w*\b|\bconclude\b",
        "Comparsa conclusionale",
        role="atto_difensivo", section="atti", tipo=TipoDocumento.COMPARSA,
        fonte="normattiva_cpc", deposit_role="atto_principale",
        evidence="titolo della comparsa conclusionale (art. 190 c.p.c.)",
    ),
    regola(
        "comparsa_costituzione",
        r"comparsa\s+di\s+(?:costituzione(?:\s+e\s+risposta)?|risposta)(?:\s+.*)?",
        r"\bsi\s+costituisc\w+\b|\bconvenut\w+\b|\bresistent\w+\b",
        "Comparsa di costituzione e risposta",
        role="atto_difensivo", section="atti", tipo=TipoDocumento.COMPARSA,
        fonte="cpc_art_167_comparsa", deposit_role="atto_principale",
        evidence="titolo della comparsa e costituzione in giudizio (art. 167 c.p.c.)",
    ),
    regola(
        "memoria_171ter",
        r"memori[ae]\b.{0,40}\b171[\s.-]*ter\b(?:.*)?",
        r"\b171[\s.-]*ter\b|\bprecis\w+\b|\bmodific\w+\b|\bprov\w+\b",
        "Memoria integrativa ex art. 171-ter c.p.c.",
        role="atto_difensivo", section="atti", tipo=TipoDocumento.MEMORIA,
        fonte="cpc_art_171_ter_memorie", deposit_role="atto_principale",
        evidence="titolo della memoria e richiamo all'art. 171-ter c.p.c.",
    ),
    regola(
        "memoria_183",
        r"memori[ae]\b.{0,40}\b183\b(?:.*)?",
        r"\bistruttor\w*\b|\bmezzi\s+di\s+prova\b|\bprova\s+per\s+testi\b|\bcapitol\w*\b|\b183\b",
        "Memoria istruttoria ex art. 183 c.p.c.",
        role="atto_difensivo", section="atti", tipo=TipoDocumento.MEMORIA,
        fonte="normattiva_cpc", deposit_role="atto_principale",
        evidence="titolo della memoria e deduzioni istruttorie (art. 183 c.p.c.)",
    ),
    regola(
        "precisazione_conclusioni",
        r"(?:foglio\s+di\s+|note\s+di\s+)?precisazione\s+delle\s+conclusioni(?:\s+.*)?",
        r"\bconclusion\w*\b|\bprecisa\w*\b",
        "Precisazione delle conclusioni",
        role="atto_difensivo", section="atti", tipo=TipoDocumento.MEMORIA,
        fonte="normattiva_cpc_art_189_precisazione_conclusioni", deposit_role="atto_principale",
        evidence="titolo dell'atto e conclusioni precisate (art. 189 c.p.c.)",
    ),
    regola(
        "decreto_127ter",
        r"decreto\s+(?:per\s+il\s+deposito\s+di\s+note\s+scritte|di\s+trattazione\s+scritta|di\s+sostituzione\s+dell.?\s*udienza)(?:\s+.*)?",
        r"\b127[\s.-]*ter\b|\bnote\s+scritte\b",
        "Decreto di trattazione scritta (art. 127-ter c.p.c.)",
        role="provvedimento", section="provvedimenti", tipo=TipoDocumento.DECRETO,
        fonte="normattiva_cpc_udienza_note_scritte", deposit_role="fuori_busta", deposit_candidate=False,
        evidence="titolo del decreto e sostituzione dell'udienza con note scritte (art. 127-ter c.p.c.)",
    ),
    regola(
        "note_127ter",
        r"note\s+(?:scritte\s+)?(?:ex\s+|ai\s+sensi\s+dell.?\s*)?art\.?\s*127[\s.-]*ter(?:\s+.*)?|note\s+scritte(?:\s+in\s+sostituzione\s+dell.?\s*udienza)?(?:\s+.*)?"
        # l'intestazione breve dei modelli di studio: «Trattazione scritta R.G. …»
        r"|trattazione\s+scritta(?:\s+.*)?",
        r"\b127[\s.-]*ter\b|\budienza\b|\btrattazione\b",
        "Note scritte ex art. 127-ter c.p.c.",
        role="atto_difensivo", section="atti", tipo=TipoDocumento.MEMORIA,
        fonte="normattiva_cpc_udienza_note_scritte", deposit_role="atto_principale",
        evidence="titolo delle note e sostituzione dell'udienza (art. 127-ter c.p.c.)",
    ),
    regola(
        "istanza_correzione_errore",
        r"istanza\s+di\s+correzione(?:\s+(?:di\s+)?errore\s+materiale)?(?:\s+.*)?|ricorso\s+per\s+correzione(?:\s+.*)?",
        r"\berrore\s+materiale\b|\b287\b|\bcorrez\w+\b|\bomission\w+\b",
        "Istanza di correzione di errore materiale",
        role="istanza", section="atti", tipo=TipoDocumento.ATTO_GIUDIZIARIO,
        fonte="normattiva_cpc_correzione_errore_materiale", deposit_role="atto_principale",
        evidence="titolo dell'istanza e correzione del provvedimento (art. 287 c.p.c.)",
    ),
    regola(
        "appello_civile",
        r"(?:atto\s+di\s+)?(?:citazione\s+in\s+)?appello(?:\s+.*)?",
        r"\bappell\w+\b|\bcorte\s+d.?\s*appello\b|\bsentenza\s+impugnata\b|\b342\b|\bgravame\b",
        "Atto di appello",
        role="atto_principale", section="atti", tipo=TipoDocumento.CITAZIONE,
        fonte="normattiva_cpc_impugnazioni", deposit_role="atto_principale",
        evidence="titolo dell'atto e impugnazione della sentenza (art. 342 c.p.c.)",
    ),
    regola(
        "atto_citazione",
        r"atto\s+di\s+citazione(?:\s+.*)?",
        r"\bcit\w*\b.{0,200}\bcomparire\b|\binvit\w*\b.{0,200}\bcostituir\w*\b|\b163\b|\b166\b|\bavvertiment\w*\b",
        "Atto di citazione",
        role="atto_principale", section="atti", tipo=TipoDocumento.CITAZIONE,
        fonte="normattiva_cpc_citazione", deposit_role="atto_principale",
        evidence="titolo dell'atto e invito a comparire e costituirsi (art. 163 c.p.c.)",
    ),
    regola(
        "cassazione_civile",
        r"ricorso\s+per\s+cassazione(?:\s+.*)?",
        r"\b360\b|\bcorte\s+di\s+cassazione\b|\bmotiv\w+\b|\bsentenza\s+impugnata\b",
        "Ricorso per cassazione",
        role="atto_principale", section="atti", tipo=TipoDocumento.RICORSO,
        fonte="normattiva_cpc_impugnazioni", deposit_role="atto_principale",
        evidence="titolo del ricorso e motivi di cassazione (art. 360 c.p.c.)",
    ),
    regola(
        "relata_notifica",
        r"relata\s+di\s+notific(?:a|azione)(?:\s+.*)?",
        r"\bho\s+notificato\b|\bnotific\w+\b.{0,80}\b(?:pec|posta\s+elettronica\s+certificata)\b",
        "Relata di notifica",
        role="relata", section="notifiche", tipo=TipoDocumento.NOTIFICA,
        fonte="normattiva_legge_53_1994_notifiche", deposit_role="prova_notifica",
        evidence="titolo della relata e attestazione dell'attività di notificazione (L. 53/1994, art. 3-bis)",
    ),
    regola(
        "relazione_ctu",
        r"(?:relazione\s+(?:di\s+)?)?consulenza\s+tecnica\s+d.?\s*ufficio(?:\s+.*)?|relazione\s+(?:del\s+)?ctu(?:\s+.*)?|relazione\s+peritale(?:\s+.*)?",
        r"\bctu\b|\bquesit\w*\b|\bnominat\w+\b|\bgiuramento\b|\boperazioni\s+peritali\b",
        "Relazione di consulenza tecnica d'ufficio (CTU)",
        role="relazione_peritale_ctu", section="allegati", tipo=TipoDocumento.ALLEGATO,
        fonte="normattiva_cpc_consulenza_tecnica",
        evidence="titolo della relazione e incarico del consulente d'ufficio (artt. 191 e 195 c.p.c.)",
    ),
    regola(
        "relazione_ctp",
        r"(?:relazione\s+tecnica|consulenza\s+tecnica|perizia(?:\s+tecnica)?)\s+di\s+parte(?:\s+.*)?|perizia\s+(?:stragiudiziale|tecnica|giurata)(?:\s+.*)?",
        r"\bconsulente\s+tecnico\s+di\s+parte\b|\bctp\b|\bsottoscritt\w+\b.{0,120}\b(?:ing|geom|arch|dott|perito)\b",
        "Relazione tecnica di parte (CTP)",
        role="perizia_di_parte", section="allegati", tipo=TipoDocumento.ALLEGATO,
        fonte="normattiva_cpc_consulenza_tecnica",
        evidence="titolo della relazione e qualifica del consulente di parte (art. 201 c.p.c.)",
    ),
    regola(
        "istanza_mediazione",
        r"(?:istanza|domanda)\s+di\s+mediazione(?:\s+.*)?",
        r"\borganismo\s+di\s+mediazione\b|\bparte\s+(?:istante|chiamata)\b|\bmediator\w*\b",
        "Istanza di mediazione",
        role="istanza_mediazione", section="allegati", tipo=TipoDocumento.ALLEGATO,
        fonte="normattiva_d_lgs_28_2010_mediazione",
        evidence="titolo dell'istanza e organismo di mediazione (D.Lgs. 28/2010, art. 4)",
    ),
    regola(
        "proposta_mediatore",
        r"proposta\s+(?:del\s+mediatore|di\s+conciliazione)(?:\s+.*)?",
        r"\bmediator\w+\b|\borganismo\b|\bpropon\w+\b|\bconcili\w+\b",
        "Proposta del mediatore",
        role="atto_mediazione", section="allegati", tipo=TipoDocumento.ALLEGATO,
        fonte="normattiva_d_lgs_28_2010_art_11_proposta",
        evidence="titolo della proposta e mediatore proponente (art. 11 D.Lgs. 28/2010)",
    ),
)

__all__ = ["REGOLE"]
