"""Atti di famiglia, successioni e volontaria giurisdizione."""

from __future__ import annotations

from pct.fascicoli import TipoDocumento

from ._modello import regola

REGOLE = (
    regola(
        "ricorso_separazione_divorzio",
        r"ricorso\s+(?:congiunto\s+)?(?:per\s+)?(?:la\s+)?(?:separazione|divorzio|scioglimento\s+del\s+matrimonio|cessazione\s+degli\s+effetti\s+civili)(?:\s+.*)?|ricorso\s+(?:ex\s+)?art\.?\s*473[\s.-]*bis(?:\s+.*)?",
        r"\bconiug\w+\b|\bmatrimonio\b|\bfigli\w*\b|\b473[\s.-]*bis\b|\bseparazion\w+\b|\bdivorzi\w+\b",
        "Ricorso per separazione o divorzio",
        role="atto_principale", section="atti", tipo=TipoDocumento.RICORSO,
        fonte="normattiva_cpc_famiglia_473_bis", deposit_role="atto_principale",
        evidence="titolo del ricorso e rapporto matrimoniale (art. 473-bis.12 c.p.c.; L. 898/1970)",
    ),
    regola(
        "ricorso_modifica_condizioni",
        r"ricorso\s+per\s+(?:la\s+)?modifica\s+delle\s+condizioni(?:\s+.*)?|ricorso\s+per\s+(?:la\s+)?revisione(?:\s+.*)?",
        r"\bseparazion\w+\b|\bdivorzi\w+\b|\baffid\w+\b|\bassegno\b|\bmantenimento\b",
        "Ricorso per modifica delle condizioni",
        role="atto_principale", section="atti", tipo=TipoDocumento.RICORSO,
        fonte="normattiva_cpc_famiglia_473_bis", deposit_role="atto_principale",
        evidence="titolo del ricorso e revisione dei provvedimenti (art. 473-bis.29 c.p.c.)",
    ),
    regola(
        "piano_genitoriale",
        r"piano\s+genitoriale(?:\s+.*)?",
        r"\bfigli\w*\b|\bminor\w+\b|\bgenitor\w+\b|\bscuol\w+\b",
        "Piano genitoriale",
        role="allegato_famiglia", section="allegati", tipo=TipoDocumento.ALLEGATO,
        fonte="normattiva_cpc_famiglia_473_bis",
        evidence="titolo del piano e impegni dei genitori (art. 473-bis.12 c.p.c.)",
    ),
    regola(
        "negoziazione_assistita_famiglia",
        r"(?:convenzione|accordo)\s+di\s+negoziazione\s+assistita(?:\s+.*)?|accordo\s+raggiunto\s+a\s+seguito\s+di\s+negoziazione(?:\s+.*)?",
        r"\bnegoziazion\w+\b|\bavvocat\w+\b|\b132\b|\bseparazion\w+\b|\bdivorzi\w+\b",
        "Accordo di negoziazione assistita",
        role="accordo", section="allegati", tipo=TipoDocumento.CONTRATTO,
        fonte="normattiva_dl_132_2014_art_6_famiglia",
        evidence="titolo dell'accordo e procedura di negoziazione assistita (art. 6 D.L. 132/2014)",
    ),
    regola(
        "decreto_omologa",
        r"decreto\s+di\s+omologa(?:zione)?(?:\s+.*)?",
        r"\bomolog\w+\b|\bseparazion\w+\b|\baccordo\b|\bconiug\w+\b",
        "Decreto di omologazione",
        role="provvedimento", section="provvedimenti", tipo=TipoDocumento.DECRETO,
        fonte="normattiva_cpc_famiglia_473_bis", deposit_role="fuori_busta", deposit_candidate=False,
        evidence="titolo del decreto e omologazione dell'accordo",
    ),
    regola(
        "relazione_servizi_sociali",
        r"relazione\s+(?:dei\s+|del\s+)?serviz\w+\s+social\w+(?:\s+.*)?|relazione\s+psico[\s-]*sociale(?:\s+.*)?",
        r"\bminor\w+\b|\bfamigl\w+\b|\bgenitor\w+\b|\bassistente\s+sociale\b",
        "Relazione dei servizi sociali",
        role="relazione_terzi", section="allegati", tipo=TipoDocumento.ALLEGATO,
        fonte="normattiva_cpc_famiglia_473_bis", deposit_role="fuori_busta", deposit_candidate=False,
        evidence="titolo della relazione e valutazione dei servizi sociali",
    ),
    regola(
        "dichiarazione_redditi",
        r"modello\s+730(?:[\s/].*)?|modello\s+(?:redditi|unico)(?:[\s/].*)?|dichiarazione\s+dei\s+redditi(?:\s+.*)?",
        r"\breddit\w+\b|\bimponibile\b|\birpef\b|\bquadro\b",
        "Dichiarazione dei redditi",
        role="documento_economico", section="allegati", tipo=TipoDocumento.ALLEGATO,
        fonte="normattiva_dpr_322_1998_dichiarazioni",
        evidence="titolo del modello e redditi dichiarati (art. 1 D.P.R. 322/1998)",
    ),
    regola(
        "attestazione_isee",
        r"attestazione\s+isee(?:\s+.*)?|dichiarazione\s+sostitutiva\s+unica(?:\s+.*)?|isee(?:\s+.*)?",
        r"\bisee\b|\bindicatore\b|\bnucleo\s+familiare\b",
        "Attestazione ISEE",
        role="documento_economico", section="allegati", tipo=TipoDocumento.ALLEGATO,
        fonte="normattiva_dpcm_159_2013_isee",
        evidence="titolo dell'attestazione e indicatore della situazione economica (art. 10 D.P.C.M. 159/2013)",
    ),
    regola(
        "ricorso_amministrazione_sostegno",
        r"ricorso\s+per\s+(?:la\s+)?(?:nomina\s+(?:di|dell.?)\s*|apertura\s+(?:di|dell.?)\s*)?amministra(?:zione|tore)\s+di\s+sostegno(?:\s+.*)?",
        r"\bbeneficiar\w+\b|\bsostegno\b|\b404\b|\bgiudice\s+tutelare\b",
        "Ricorso per amministrazione di sostegno",
        role="atto_principale", section="atti", tipo=TipoDocumento.RICORSO,
        fonte="normattiva_cc_amministrazione_sostegno", deposit_role="atto_principale",
        evidence="titolo del ricorso e beneficiario della misura (artt. 404 e 407 c.c.)",
    ),
    regola(
        "decreto_nomina_ads",
        r"decreto\s+di\s+nomina(?:\s+.*)?",
        r"\bamministratore\s+di\s+sostegno\b|\btutor\w+\b|\bcurator\w+\b|\bgiudice\s+tutelare\b",
        "Decreto di nomina",
        role="provvedimento", section="provvedimenti", tipo=TipoDocumento.DECRETO,
        fonte="normattiva_cc_amministrazione_sostegno", deposit_role="fuori_busta", deposit_candidate=False,
        evidence="titolo del decreto e nomina del giudice tutelare",
    ),
    regola(
        "testamento",
        r"testamento(?:\s+(?:olografo|pubblico|segreto))?(?:\s+.*)?",
        r"\blascio\b|\bnomino\b.{0,30}\bered\w+\b|\bistituisco\b|\bultime\s+volont\w+\b|\bdisposizion\w+\b|\blegat\w+\b",
        "Testamento",
        role="atto_successorio", section="allegati", tipo=TipoDocumento.ALLEGATO,
        fonte="normattiva_cc_successioni",
        evidence="titolo dell'atto e disposizioni di ultima volontà (art. 601 c.c.)",
    ),
    regola(
        "verbale_pubblicazione_testamento",
        r"verbale\s+di\s+pubblicazione(?:\s+.*)?",
        r"\btestament\w+\b|\bnotai\w+\b",
        "Verbale di pubblicazione di testamento",
        role="atto_successorio", section="allegati", tipo=TipoDocumento.VERBALE,
        fonte="normattiva_cc_successioni",
        evidence="titolo del verbale e pubblicazione notarile (art. 620 c.c.)",
    ),
    regola(
        "dichiarazione_successione",
        r"dichiarazione\s+di\s+successione(?:\s+.*)?",
        r"\bered\w+\b|\bde\s+cuius\b|\bdefunt\w+\b|\basse\s+ereditario\b|\bagenzia\s+delle\s+entrate\b",
        "Dichiarazione di successione",
        role="atto_successorio", section="allegati", tipo=TipoDocumento.ALLEGATO,
        fonte="normattiva_d_lgs_346_1990_successioni",
        evidence="titolo della dichiarazione e asse ereditario (art. 28 D.Lgs. 346/1990)",
    ),
    regola(
        "rinuncia_eredita",
        r"(?:atto\s+di\s+)?rinun[cz]ia\s+(?:all.?\s*eredit[aà]|di\s+eredit[aà])(?:\s+.*)?",
        r"\bered\w+\b|\brinun\w+\b|\bdefunt\w+\b|\bcancell\w+\b",
        "Rinuncia all'eredità",
        role="atto_successorio", section="allegati", tipo=TipoDocumento.ALLEGATO,
        fonte="normattiva_cc_successioni",
        evidence="titolo dell'atto e rinuncia del chiamato (art. 519 c.c.)",
    ),
    regola(
        "accettazione_beneficio_inventario",
        r"(?:atto\s+di\s+)?accettazione\s+(?:dell.?\s*eredit[aà]\s+)?con\s+beneficio\s+d.?\s*inventario(?:\s+.*)?",
        r"\bered\w+\b|\binventario\b|\bbenefici\w+\b",
        "Accettazione con beneficio d'inventario",
        role="atto_successorio", section="allegati", tipo=TipoDocumento.ALLEGATO,
        fonte="normattiva_cc_successioni",
        evidence="titolo dell'atto e accettazione beneficiata (art. 484 c.c.)",
    ),
    regola(
        "atto_notorio",
        r"atto\s+(?:notorio|di\s+notoriet[aà])(?:\s+.*)?|dichiarazione\s+sostitutiva\s+dell.?\s*atto\s+di\s+notoriet[aà](?:\s+.*)?",
        r"\bdichiar\w+\b|\btestimon\w+\b|\bered\w+\b|\bnotori\w+\b",
        "Atto notorio",
        role="dichiarazione_sostitutiva", section="allegati", tipo=TipoDocumento.ALLEGATO,
        fonte="normattiva_dpr_445_2000_documentazione_amministrativa",
        evidence="titolo dell'atto e dichiarazione sostitutiva (art. 47 D.P.R. 445/2000)",
    ),
)

__all__ = ["REGOLE"]
