"""Atti del procedimento penale (c.p.p.) e certificati del casellario."""

from __future__ import annotations

from pct.fascicoli import TipoDocumento

from ._modello import regola

# Un atto penale si riconosce anche dal lessico che il civile non usa.
_PENALE = r"\bimputat\w*\b|\bindagat\w*\b|\breato\b|\bp\.?\s*m\.?\b|\bprocura\s+della\s+repubblica\b|\bc\.?\s*p\.?\s*p\.?\b|\bpubblico\s+ministero\b|\bpersona\s+offesa\b"

REGOLE = (
    regola(
        "informazione_garanzia",
        r"informazione\s+di\s+garanzia(?:\s+.*)?",
        r"\bindagat\w*\b|\bart\.?\s*369\b|\breato\b|\bdifensore\b",
        "Informazione di garanzia",
        role="atto_ufficio", section="comunicazioni", tipo=TipoDocumento.COMUNICAZIONE,
        fonte="normattiva_cpp_indagini_preliminari", deposit_role="fuori_busta", deposit_candidate=False,
        evidence="titolo dell'atto e comunicazione all'indagato (art. 369 c.p.p.)",
    ),
    regola(
        "avviso_415bis",
        r"avviso\s+(?:di\s+conclusione\s+delle\s+indagini(?:\s+preliminari)?|ex\s+art\.?\s*415[\s.-]*bis)(?:\s+.*)?",
        r"\b415[\s.-]*bis\b|\bindagin\w*\b|\bindagat\w*\b",
        "Avviso di conclusione delle indagini preliminari",
        role="atto_ufficio", section="comunicazioni", tipo=TipoDocumento.COMUNICAZIONE,
        fonte="normattiva_cpp_indagini_preliminari", deposit_role="fuori_busta", deposit_candidate=False,
        evidence="titolo dell'avviso e conclusione delle indagini (art. 415-bis c.p.p.)",
    ),
    regola(
        "richiesta_archiviazione",
        r"richiesta\s+di\s+archiviazione(?:\s+.*)?",
        r"\barchivia\w*\b|\bnotizia\s+di\s+reato\b|\bindagat\w*\b",
        "Richiesta di archiviazione",
        role="atto_ufficio", section="atti", tipo=TipoDocumento.ATTO_GIUDIZIARIO,
        fonte="normattiva_cpp_indagini_preliminari", deposit_role="fuori_busta", deposit_candidate=False,
        evidence="titolo della richiesta del pubblico ministero (art. 408 c.p.p.)",
    ),
    regola(
        "opposizione_archiviazione",
        r"(?:atto\s+di\s+)?opposizione\s+alla\s+richiesta\s+di\s+archiviazione(?:\s+.*)?",
        r"\barchivia\w*\b|\bpersona\s+offesa\b|\b410\b",
        "Opposizione alla richiesta di archiviazione",
        role="atto_principale", section="atti", tipo=TipoDocumento.ATTO_GIUDIZIARIO,
        fonte="normattiva_cpp_indagini_preliminari", deposit_role="atto_principale",
        evidence="titolo dell'opposizione e richiesta di prosecuzione delle indagini (art. 410 c.p.p.)",
    ),
    regola(
        "richiesta_rinvio_giudizio",
        r"richiesta\s+di\s+rinvio\s+a\s+giudizio(?:\s+.*)?",
        r"\bimputat\w*\b|\breato\b|\budienza\s+preliminare\b",
        "Richiesta di rinvio a giudizio",
        role="atto_ufficio", section="atti", tipo=TipoDocumento.ATTO_GIUDIZIARIO,
        fonte="normattiva_cpp_esercizio_azione_penale", deposit_role="fuori_busta", deposit_candidate=False,
        evidence="titolo della richiesta del pubblico ministero (art. 416 c.p.p.)",
    ),
    regola(
        "decreto_dispone_giudizio",
        r"decreto\s+che\s+dispone\s+il\s+giudizio(?:\s+.*)?",
        r"\bimputat\w*\b|\bdibattiment\w*\b|\bdispone\b",
        "Decreto che dispone il giudizio",
        role="provvedimento", section="provvedimenti", tipo=TipoDocumento.DECRETO,
        fonte="normattiva_cpp_esercizio_azione_penale", deposit_role="fuori_busta", deposit_candidate=False,
        evidence="titolo del decreto e fissazione del dibattimento (art. 429 c.p.p.)",
    ),
    regola(
        "decreto_citazione_giudizio",
        r"decreto\s+di\s+citazione(?:\s+diretta)?\s+a\s+giudizio(?:\s+.*)?|decreto\s+di\s+giudizio\s+immediato(?:\s+.*)?",
        r"\bimputat\w*\b|\breato\b|\bcita\b|\bcomparire\b",
        "Decreto di citazione a giudizio",
        role="provvedimento", section="provvedimenti", tipo=TipoDocumento.DECRETO,
        fonte="normattiva_cpp_esercizio_azione_penale", deposit_role="fuori_busta", deposit_candidate=False,
        evidence="titolo del decreto e citazione dell'imputato (artt. 450 e 552 c.p.p.)",
    ),
    regola(
        "decreto_penale_condanna",
        r"decreto\s+penale\s+di\s+condanna(?:\s+.*)?",
        r"\bcondanna\b|\bpena\b|\bimputat\w*\b|\bopposizione\b",
        "Decreto penale di condanna",
        role="provvedimento", section="provvedimenti", tipo=TipoDocumento.DECRETO,
        fonte="normattiva_cpp_procedimento_per_decreto", deposit_role="fuori_busta", deposit_candidate=False,
        evidence="titolo del decreto e condanna a pena pecuniaria (art. 460 c.p.p.)",
    ),
    regola(
        "opposizione_decreto_penale",
        r"(?:atto\s+di\s+)?opposizione\s+a\s+decreto\s+penale(?:\s+di\s+condanna)?(?:\s+.*)?",
        r"\bdecreto\s+penale\b|\bimputat\w*\b|\b461\b|\bgiudizio\s+immediato\b|\brito\s+abbreviato\b",
        "Opposizione a decreto penale di condanna",
        role="atto_principale", section="atti", tipo=TipoDocumento.ATTO_GIUDIZIARIO,
        fonte="normattiva_cpp_procedimento_per_decreto", deposit_role="atto_principale",
        evidence="titolo dell'opposizione e scelta del rito (art. 461 c.p.p.)",
    ),
    regola(
        "nomina_difensore",
        r"(?:atto\s+di\s+)?nomina\s+(?:del\s+|di\s+)?difensore(?:\s+di\s+fiducia)?(?:\s+.*)?|dichiarazione\s+di\s+nomina\s+(?:del\s+)?difensore(?:\s+.*)?",
        r"\bnomin\w+\b|\bdifensore\s+di\s+fiducia\b|\bavv\.?\b|\belegg\w+\s+domicilio\b",
        "Nomina del difensore di fiducia",
        role="procura", section="procure", tipo=TipoDocumento.PROCURA,
        fonte="normattiva_cpp_difensore", deposit_role="procura",
        evidence="titolo dell'atto e nomina del difensore (art. 96 c.p.p.)",
    ),
    regola(
        "querela",
        r"(?:atto\s+di\s+)?(?:denuncia[\s-]*)?querela(?:\s+.*)?",
        r"\bquerel\w+\b|\breato\b|\bpunit\w+\b|\bprocura\s+della\s+repubblica\b|\bcarabinieri\b|\bpolizia\b",
        "Querela",
        role="atto_principale", section="atti", tipo=TipoDocumento.ATTO_GIUDIZIARIO,
        fonte="normattiva_cpp_notizia_di_reato", deposit_role="atto_principale",
        evidence="titolo dell'atto e istanza di punizione (art. 336 c.p.p.)",
    ),
    regola(
        "denuncia",
        r"(?:atto\s+di\s+)?denuncia(?:\s+.*)?",
        r"\bdenunci\w+\b|\breato\b|\bfatt[oi]\b|\bprocura\s+della\s+repubblica\b|\bcarabinieri\b|\bpolizia\b",
        "Denuncia",
        role="atto_principale", section="atti", tipo=TipoDocumento.ATTO_GIUDIZIARIO,
        fonte="normattiva_cpp_notizia_di_reato", deposit_role="atto_principale",
        evidence="titolo dell'atto e notizia di reato (art. 333 c.p.p.)",
    ),
    regola(
        "richiesta_riesame",
        r"(?:richiesta|istanza)\s+di\s+riesame(?:\s+.*)?",
        r"\bmisura\s+cautelare\b|\bordinanza\b|\b309\b|\bindagat\w*\b|\bimputat\w*\b",
        "Richiesta di riesame",
        role="atto_principale", section="atti", tipo=TipoDocumento.ATTO_GIUDIZIARIO,
        fonte="normattiva_cpp_riesame", deposit_role="atto_principale",
        evidence="titolo della richiesta e misura cautelare impugnata (art. 309 c.p.p.)",
    ),
    regola(
        "lista_testi",
        r"lista\s+(?:dei\s+)?(?:testimoni|testi)(?:\s+.*)?|lista\s+testimoniale(?:\s+.*)?",
        r"\btestimon\w*\b|\bcircostanz\w*\b|\b468\b|\bperit\w*\b",
        "Lista dei testimoni",
        role="atto_difensivo", section="atti", tipo=TipoDocumento.ATTO_GIUDIZIARIO,
        fonte="normattiva_cpp_lista_testi", deposit_role="atto_principale",
        evidence="titolo della lista e indicazione dei testimoni (art. 468 c.p.p.)",
    ),
    regola(
        "memoria_121_cpp",
        r"memoria\s+(?:difensiva\s+)?(?:ex\s+)?art\.?\s*121(?:\s+.*)?",
        _PENALE,
        "Memoria difensiva ex art. 121 c.p.p.",
        role="atto_difensivo", section="atti", tipo=TipoDocumento.MEMORIA,
        fonte="normattiva_cpp_difensore", deposit_role="atto_principale",
        evidence="titolo della memoria e richiamo all'art. 121 c.p.p.",
    ),
    regola(
        "verbale_sequestro",
        r"verbale\s+di\s+sequestro(?:\s+.*)?",
        r"\bsequestr\w+\b|\bpolizia\s+giudiziaria\b|\bcose\b|\bcorpo\s+del\s+reato\b",
        "Verbale di sequestro",
        role="verbale_ufficio", section="provvedimenti", tipo=TipoDocumento.VERBALE,
        fonte="normattiva_cpp_sequestro_identificazione", deposit_role="fuori_busta", deposit_candidate=False,
        evidence="titolo del verbale e attività di sequestro (artt. 253 e 354 c.p.p.)",
    ),
    regola(
        "verbale_identificazione",
        r"verbale\s+di\s+(?:identificazione|elezione\s+di\s+domicilio)(?:\s+.*)?",
        r"\bdomicilio\b|\bidentific\w+\b|\bindagat\w*\b|\bgeneralit\w*\b",
        "Verbale di identificazione ed elezione di domicilio",
        role="verbale_ufficio", section="provvedimenti", tipo=TipoDocumento.VERBALE,
        fonte="normattiva_cpp_sequestro_identificazione", deposit_role="fuori_busta", deposit_candidate=False,
        evidence="titolo del verbale e dichiarazione di domicilio (art. 161 c.p.p.)",
    ),
    regola(
        "certificato_casellario",
        r"certificato\s+(?:generale\s+)?(?:del\s+)?casellario(?:\s+giudiziale)?(?:\s+.*)?",
        r"\bcasellario\b|\bprocura\s+della\s+repubblica\b|\bnulla\b|\biscrizion\w*\b",
        "Certificato del casellario giudiziale",
        role="certificato", section="allegati", tipo=TipoDocumento.ALLEGATO,
        fonte="normattiva_dpr_313_2002_casellario",
        evidence="titolo del certificato e ufficio del casellario (art. 24 D.P.R. 313/2002)",
    ),
    regola(
        "certificato_carichi_pendenti",
        r"certificato\s+dei\s+carichi\s+pendenti(?:\s+.*)?",
        r"\bcarichi\s+pendenti\b|\bprocura\s+della\s+repubblica\b|\bprocediment\w*\b",
        "Certificato dei carichi pendenti",
        role="certificato", section="allegati", tipo=TipoDocumento.ALLEGATO,
        fonte="normattiva_dpr_313_2002_casellario",
        evidence="titolo del certificato e procedimenti pendenti (art. 27 D.P.R. 313/2002)",
    ),
    regola(
        "appello_penale",
        r"(?:atto\s+di\s+)?appello(?:\s+.*)?",
        _PENALE,
        "Atto di appello penale",
        role="atto_principale", section="atti", tipo=TipoDocumento.ATTO_GIUDIZIARIO,
        fonte="normattiva_cpp_impugnazioni", deposit_role="atto_principale",
        evidence="titolo dell'atto e lessico del processo penale (art. 581 c.p.p.)",
    ),
    regola(
        "cassazione_penale",
        r"ricorso\s+per\s+cassazione(?:\s+.*)?",
        _PENALE,
        "Ricorso per cassazione penale",
        role="atto_principale", section="atti", tipo=TipoDocumento.RICORSO,
        fonte="normattiva_cpp_impugnazioni", deposit_role="atto_principale",
        evidence="titolo del ricorso e lessico del processo penale (art. 606 c.p.p.)",
    ),
)

__all__ = ["REGOLE"]
