"""RFC 3161 timestamp client helpers.

The production path can call a TSA URL with a prebuilt request generated by
OpenSSL. Development may use an explicit non-qualified timestamp token; that
token is marked as such and never accepted as qualified evidence.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime
import json
import os
import subprocess
import tempfile
from pathlib import Path
from typing import Any

import requests

from .exceptions import AuditConfigError, AuditTimestampError
from .hashing import is_sha256_hex


@dataclass(frozen=True)
class TimestampToken:
    token: bytes
    content_type: str
    qualified: bool
    source: str


class AuditTSAClient:
    def __init__(
        self,
        *,
        tsa_url: str = "",
        username: str = "",
        password: str = "",
        required: bool = False,
        env: str = "development",
        openssl_bin: str = "openssl",
    ) -> None:
        self.tsa_url = tsa_url.strip()
        self.username = username
        self.password = password
        self.required = required
        self.env = env.strip().lower() or "development"
        self.openssl_bin = openssl_bin

    @classmethod
    def from_config(cls, config: dict[str, Any] | None = None) -> "AuditTSAClient":
        cfg = dict(config or {})
        return cls(
            tsa_url=str(cfg.get("AUDIT_TSA_URL") or os.getenv("AUDIT_TSA_URL") or ""),
            username=str(cfg.get("AUDIT_TSA_USERNAME") or os.getenv("AUDIT_TSA_USERNAME") or ""),
            password=str(cfg.get("AUDIT_TSA_PASSWORD") or os.getenv("AUDIT_TSA_PASSWORD") or ""),
            required=str(cfg.get("AUDIT_REQUIRE_TSA_FOR_SNAPSHOT") or os.getenv("AUDIT_REQUIRE_TSA_FOR_SNAPSHOT") or "").lower()
            in {"1", "true", "yes", "on"},
            env=str(cfg.get("AUDIT_ENV") or os.getenv("AUDIT_ENV") or "development"),
            openssl_bin=str(cfg.get("AUDIT_OPENSSL_BIN") or os.getenv("AUDIT_OPENSSL_BIN") or "openssl"),
        )

    def timestamp_hash(self, digest_hex: str) -> TimestampToken | None:
        if not is_sha256_hex(digest_hex):
            raise AuditTimestampError("Digest snapshot non valido per TSA.")
        if self.tsa_url:
            return self._request_rfc3161(digest_hex)
        if self.required and self.env == "production":
            raise AuditTimestampError("TSA obbligatoria in produzione ma non configurata.")
        if self.env in {"development", "test", "testing", "staging"}:
            payload = {
                "format": "iusentra-non-qualified-timestamp-v1",
                "qualified": False,
                "digest_alg": "SHA-256",
                "digest": digest_hex,
                "timestamp_utc": datetime.now(UTC).replace(microsecond=0).isoformat().replace("+00:00", "Z"),
                "warning": "NON_QUALIFICATO",
            }
            return TimestampToken(json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8"), "application/json", False, "development-fallback")
        if self.required:
            raise AuditTimestampError("TSA obbligatoria ma non configurata.")
        return None

    def _request_rfc3161(self, digest_hex: str) -> TimestampToken:
        try:
            with tempfile.TemporaryDirectory() as tmp:
                query_path = Path(tmp) / "request.tsq"
                subprocess.run(
                    [
                        self.openssl_bin,
                        "ts",
                        "-query",
                        "-digest",
                        digest_hex,
                        "-sha256",
                        "-cert",
                        "-out",
                        str(query_path),
                    ],
                    check=True,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                )
                headers = {"Content-Type": "application/timestamp-query", "Accept": "application/timestamp-reply"}
                auth = (self.username, self.password) if self.username or self.password else None
                response = requests.post(self.tsa_url, data=query_path.read_bytes(), headers=headers, auth=auth, timeout=30)
                response.raise_for_status()
                return TimestampToken(response.content, response.headers.get("content-type", "application/timestamp-reply"), True, self.tsa_url)
        except Exception as exc:
            if self.required:
                raise AuditTimestampError("Richiesta TSA RFC3161 fallita.") from exc
            return self.timestamp_hash_dev_fallback(digest_hex)

    def timestamp_hash_dev_fallback(self, digest_hex: str) -> TimestampToken:
        if self.env == "production":
            raise AuditTimestampError("Fallback timestamp non qualificato vietato in produzione.")
        payload = {
            "format": "iusentra-non-qualified-timestamp-v1",
            "qualified": False,
            "digest_alg": "SHA-256",
            "digest": digest_hex,
            "timestamp_utc": datetime.now(UTC).replace(microsecond=0).isoformat().replace("+00:00", "Z"),
            "warning": "TSA_NON_DISPONIBILE",
        }
        return TimestampToken(json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8"), "application/json", False, "development-fallback")


def verify_timestamp_token(token: bytes, digest_hex: str, *, openssl_bin: str = "openssl") -> bool:
    if not token:
        return False
    try:
        parsed = json.loads(token.decode("utf-8"))
        if parsed.get("format") == "iusentra-non-qualified-timestamp-v1":
            return parsed.get("digest") == digest_hex and parsed.get("qualified") is False
    except Exception:
        pass
    if not is_sha256_hex(digest_hex):
        return False
    with tempfile.TemporaryDirectory() as tmp:
        token_path = Path(tmp) / "token.tsr"
        query_path = Path(tmp) / "request.tsq"
        token_path.write_bytes(token)
        try:
            subprocess.run(
                [openssl_bin, "ts", "-query", "-digest", digest_hex, "-sha256", "-cert", "-out", str(query_path)],
                check=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )
            # Without a trusted TSA cert this confirms structural readability only.
            subprocess.run(
                [openssl_bin, "ts", "-reply", "-in", str(token_path), "-text"],
                check=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )
            return True
        except Exception:
            return False
