<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="http://schemi.processotelematico.giustizia.it/sigp/corsocausa/v1"
           xmlns:bt="http://schemi.processotelematico.giustizia.it/sigp/tipi/v1"
           xmlns:pt="http://schemi.processotelematico.giustizia.it/sigp/tipi/atti/v1"
           xmlns:evt="http://schemi.processotelematico.giustizia.it/sigp/eventi/parte/v1"
           xmlns:ns1="http://schemi.processotelematico.giustizia.it/sigp/tipi/anagrafiche/v1"
           targetNamespace="http://schemi.processotelematico.giustizia.it/sigp/corsocausa/v1"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified"
           version="1.0">
	<xs:import namespace="http://schemi.processotelematico.giustizia.it/sigp/tipi/v1"
	           schemaLocation="../base_v1/tipi-base.xsd"/>
	<xs:import namespace="http://schemi.processotelematico.giustizia.it/sigp/tipi/atti/v1"
	           schemaLocation="../base_v1/tipi-atti.xsd"/>
	<xs:import namespace="http://schemi.processotelematico.giustizia.it/sigp/eventi/parte/v1"
	           schemaLocation="../base_v1/eventi-parte.xsd"/>
	<xs:import namespace="http://schemi.processotelematico.giustizia.it/sigp/tipi/anagrafiche/v1"
	           schemaLocation="../base_v1/tipi-anagrafiche.xsd"/>
	<xs:annotation>
		<xs:documentation>ATTI DI PARTE IN CORSO CAUSA</xs:documentation>
		<xs:documentation>Gli atti qui definiti si riferiscono a procedimenti
			in essere</xs:documentation>
	</xs:annotation>
	<xs:complexType name="TipiIstanzeMemorieGeneriche">
		<xs:choice minOccurs="0"
		           maxOccurs="unbounded">
			<xs:element ref="evt:IstanzaRichiestaEsecutorietaExArt647"/>
			<xs:element ref="evt:IstanzaExArt186Bis"/>
			<xs:element ref="evt:IstanzaExArt186Ter"/>
			<xs:element ref="evt:IstanzaExArt186Quater"/>
			<xs:element ref="evt:IstanzaGenerica"/>
		</xs:choice>
	</xs:complexType>
	<xs:group name="TipoDocumenti">
		<xs:choice>
			<!-- TODO definire i tipi doc! -->
		</xs:choice>
	</xs:group>
	<xs:element name="ProduzioneDocumentiRichiesti">
		<xs:annotation>
			<xs:documentation>Atto di deposito documentazione richiesta
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="pt:AttoProcedimento">
					<xs:sequence>
						<xs:element ref="pt:domanda"
						            minOccurs="0"
						            maxOccurs="1"/>
						<xs:element name="documenti"
						            minOccurs="0"
						            maxOccurs="1">
							<xs:annotation>
								<xs:documentation>Tipo dell'atto depositato</xs:documentation>
							</xs:annotation>
							<xs:complexType>
								<xs:group ref="TipoDocumenti"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="IstanzaGenerica">
		<xs:annotation>
			<xs:documentation>Istanza generica depositabile dall'avvocato</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="pt:AttoProcedimento">
					<xs:sequence>
						<xs:element name="note"
						            type="xs:string"
						            minOccurs="0"
						            maxOccurs="1"/>
						<xs:element ref="pt:domanda"
						            minOccurs="0"
						            maxOccurs="1"/>
						<xs:element name="deposito"
						            type="TipiIstanzeMemorieGeneriche"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="AttoRichiestaVisibilita">
		<xs:annotation>
			<xs:documentation>Atto di richiesta visibilità del fascicolo
		</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="pt:AttoProcedimento">
					<xs:sequence>
						<xs:element name="Parte">
							<xs:complexType>
								<xs:complexContent>
									<xs:extension base="ns1:RiferimentoSoggetto">
										<xs:attribute name="ID"
										              type="xs:string"/>
									</xs:extension>
								</xs:complexContent>
							</xs:complexType>
						</xs:element>
						<xs:element name="Avvocato">
							<xs:complexType>
								<xs:complexContent>
									<xs:extension base="ns1:Avvocato"/>
								</xs:complexContent>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
		<!--xs:key name="PK_PARTE_VIS">
			<xs:selector xpath="tns:Parte" />
			<xs:field xpath="@ID" />
		</xs:key>
		<xs:keyref name="FK_PARTE_AVVOCATO_MODIFICHE" refer="PK_PARTE_VIS">
			<xs:selector xpath="tns:Avvocato/at:parteRappresentata" />
			<xs:field xpath="@ref" />
		</xs:keyref-->
	</xs:element>
	<xs:element name="DepositoNoteConclusionali">
		<xs:annotation>
			<xs:documentation>Deposito note conclusionali</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="pt:AttoProcedimento">
					<xs:sequence>
						<xs:element ref="pt:domanda"
						            minOccurs="0"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="DepositoMemorie">
		<xs:annotation>
			<xs:documentation>Deposito memorie generiche</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="pt:AttoProcedimento">
					<xs:sequence>
						<xs:element ref="pt:domanda"
						            minOccurs="0"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="CostituzioneSemplice">
		<xs:annotation>
			<xs:documentation>Atto di costituzione delle parti</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="pt:AttoProcedimento">
					<xs:sequence>
						<xs:element ref="pt:ModificheAnagrafica"/>
						<xs:element ref="pt:domanda"
						            minOccurs="0"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
</xs:schema>