<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="http://schemi.processotelematico.giustizia.it/sigp/introduttivi/v1"
           xmlns:bt="http://schemi.processotelematico.giustizia.it/sigp/tipi/v1"
           xmlns:pt="http://schemi.processotelematico.giustizia.it/sigp/tipi/atti/v1"
           xmlns:evt="http://schemi.processotelematico.giustizia.it/sigp/eventi/parte/v1"
           xmlns:ns1="http://schemi.processotelematico.giustizia.it/sigp/tipi/anagrafiche/v1"
           xmlns:all="http://schemi.processotelematico.giustizia.it/sigp/tipi/allegati/v1"
           targetNamespace="http://schemi.processotelematico.giustizia.it/sigp/introduttivi/v1"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified"
           version="1.0">
	<xs:import namespace="http://schemi.processotelematico.giustizia.it/sigp/tipi/v1"
	           schemaLocation="../base_v1/tipi-base.xsd"/>
	<xs:import namespace="http://schemi.processotelematico.giustizia.it/sigp/tipi/atti/v1"
	           schemaLocation="../base_v1/tipi-atti.xsd"/>
	<xs:import namespace="http://schemi.processotelematico.giustizia.it/sigp/eventi/parte/v1"
	           schemaLocation="../base_v1/eventi-parte.xsd"/>
	<xs:import namespace="http://schemi.processotelematico.giustizia.it/sigp/tipi/anagrafiche/v1"
	           schemaLocation="../base_v1/tipi-anagrafiche.xsd"/>
	<xs:import namespace="http://schemi.processotelematico.giustizia.it/sigp/tipi/allegati/v1"
	           schemaLocation="../base_v1/tipi-allegati.xsd"/>
	<xs:annotation>
		<xs:documentation>ATTI DI PARTE INTRODUTTIVI</xs:documentation>
		<xs:documentation>Gli atti qui definiti iscrivono una nuova causa al ruolo per citazione o ricorso</xs:documentation>
	</xs:annotation>
	<xs:complexType name="TipoDecreto">
		<xs:choice>
			<xs:element name="somma"
			            type="bt:Valuta"/>
			<xs:element name="somma-beni"
			            type="bt:Valuta"/>
			<xs:element name="oneri-condominiali"
			            type="bt:Valuta"/>
			<xs:element name="consegna-beni"
			            type="bt:Valuta"/>
		</xs:choice>
		<xs:attribute name="esecutivo"
		              type="xs:boolean"
		              use="required"/>
	</xs:complexType>
	<xs:element name="RicorsoDecretoIngiuntivo">
		<xs:annotation>
			<xs:documentation>Iscrizione di un ricorso per decreto ingiuntivo.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="pt:AttoIntroduttivo">
					<xs:sequence>
						<xs:element ref="pt:AnagraficaProcedimento"/>
						<xs:element name="TipoDecreto" type="TipoDecreto"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="RicorsoImmigrazione">
		<xs:annotation>
			<xs:documentation>Iscrizione di un ricorso per decreto ingiuntivo.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="pt:AttoIntroduttivo">
					<xs:sequence>
						<xs:element ref="pt:AnagraficaProcedimento"/>
						<xs:element name="codVestanet" minOccurs="0">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:minLength value="9"/>
									<xs:maxLength value="9"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="nazioneProvenienza" type="xs:string" minOccurs="0"/>
						<xs:element name="CUI" minOccurs="0">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:minLength value="7"/>
									<xs:maxLength value="7"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="dataDecreto" type="xs:date" minOccurs="0">
							<xs:annotation>
								<xs:documentation>Data del decreto per il trattenimento presso la frontiera (oggetto 110041)</xs:documentation>
							</xs:annotation>
						</xs:element>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="Citazione">
		<xs:annotation>
			<xs:documentation>Citazione generica</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="pt:AttoIntroduttivo">
					<xs:sequence>
						<xs:element ref="pt:AnagraficaProcedimento"/>
						<xs:element name="AltriDati"
						            type="pt:AltriDati"/>
					</xs:sequence>
					<xs:attribute name="Datacitazione"
					              type="xs:date"
					              use="required"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="CitazioneInRiassunzione">
		<xs:annotation>
			<xs:documentation>Citazione in riassunzione e riassunzione in appello</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="pt:AttoIntroduttivo">
					<xs:sequence>
						<xs:element ref="pt:AnagraficaProcedimento"/>
						<xs:element name="DatiProcedimento"
						            type="pt:DatiRiassunzioneProcedimento">
							<xs:annotation>
								<xs:documentation>Procedimento riassunto</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="AltriDati"
						            type="pt:AltriDati"/>
					</xs:sequence>
					<xs:attribute name="Datacitazione"
					              type="xs:date"
					              use="required"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="OpposizioneDecretoIngiuntivo">
		<xs:annotation>
			<xs:documentation>Atto di opposizione a decreto ingiuntivo</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="pt:AttoIntroduttivo">
					<xs:sequence>
						<xs:element ref="pt:AnagraficaProcedimento"/>
						<xs:element name="DatiDecreto">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="causa"
									            type="pt:RiferimentoFascicolo"
									            minOccurs="0">
										<xs:annotation>
											<xs:documentation>Riferimento al decreto opposto, come identificativi di procedimento (anno numero)</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="decreto"
									            type="pt:RiferimentoProvvedimento">
										<xs:annotation>
											<xs:documentation>Riferimento al decreto ingiuntivo</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="data"
									            type="xs:date">
										<xs:annotation>
											<xs:documentation>Data di emissione del decreto</xs:documentation>
										</xs:annotation>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="AltriDati"
						            type="pt:AltriDati"/>
					</xs:sequence>
					<xs:attribute name="Datacitazione"
					              type="xs:date"
					              use="required"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="Ricorso">
		<xs:annotation>
			<xs:documentation>Ricorso generico</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="pt:AttoIntroduttivo">
					<xs:sequence>
						<xs:element ref="pt:AnagraficaProcedimento"/>
						<xs:element name="DatiProcedimento"
						            type="pt:DatiRiassunzioneProcedimento"
						            minOccurs="0">
							<xs:annotation>
								<xs:documentation>Procedimento riassunto</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="AltriDati"
						            type="pt:AltriDati"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="OSA">
		<xs:annotation>
			<xs:documentation>Ricorso in opposizione a sanzione amministrativa</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="pt:AttoIntroduttivo">
					<xs:sequence>
						<xs:element ref="pt:AnagraficaProcedimento"/>
						<xs:element name="DatiProcedimento"
						            type="pt:DatiRiassunzioneProcedimento"
						            minOccurs="0">
							<xs:annotation>
								<xs:documentation>Procedimento riassunto</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="AltriDati"
						            type="pt:AltriDati"/>
						<xs:element name="SanzioneOpposta">
							<xs:annotation>
								<xs:documentation>Indicare almeno una tra le tre sanzioni opposte: Verbale, Cartella oppure Ordinanza di Ingiunzione</xs:documentation>
							</xs:annotation>
							<xs:complexType>
								<xs:sequence>
									<xs:element name="Verbale"
									            type="bt:VerbaleOSA"
									            minOccurs="0"
									            maxOccurs="unbounded"/>
									<xs:element name="OrdinanzaDiIngiunzione"
									            minOccurs="0"
									            maxOccurs="unbounded">
										<xs:complexType>
											<xs:complexContent>
												<xs:extension base="bt:VerbaleOSA">
													<xs:attribute name="RiferimentoOrdinanza"
													              type="xs:string"
													              use="required"/>
												</xs:extension>
											</xs:complexContent>
										</xs:complexType>
									</xs:element>
									<xs:element name="Cartella"
									            minOccurs="0"
									            maxOccurs="unbounded">
										<xs:complexType>
											<xs:complexContent>
												<xs:extension base="bt:VerbaleOSA">
													<xs:attribute name="RiferimentoCartella"
													              use="required">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:length value="17"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:attribute>
												</xs:extension>
											</xs:complexContent>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
</xs:schema>
