import { useEffect, useRef, useState } from 'react'
import type { CSSProperties, PointerEvent } from 'react'
import type { Mark, PageInfo } from './viewerEditorTypes'
type Props={marks:Mark[];page:number;pageInfo?:PageInfo;disabled:boolean;selected:number|null;onSelect:(index:number,mark:Mark)=>void;onChange:(marks:Mark[])=>void}
export function ViewerCanvasObjects({marks,page,pageInfo,disabled,selected,onSelect,onChange}:Props){
  const [menu,setMenu]=useState<{index:number;x:number;y:number}|null>(null)
  const menuRef=useRef<HTMLDivElement>(null)
  const drag=useRef<{index:number;mode:'move'|'resize';clientX:number;clientY:number;w:number;h:number;mark:Mark}|null>(null)
  const [moving,setMoving]=useState<{index:number;mark:Mark}|null>(null)
  useEffect(()=>{if(!menu)return;menuRef.current?.querySelector<HTMLButtonElement>('button')?.focus();const close=(event:globalThis.PointerEvent)=>{if(!menuRef.current?.contains(event.target as Node))setMenu(null)};window.addEventListener('pointerdown',close);return()=>window.removeEventListener('pointerdown',close)},[menu])
  const update=(index:number,patch:Partial<Mark>)=>{const changed={...marks[index],...patch};onChange(marks.map((mark,i)=>i===index?changed:mark));onSelect(index,changed)}
  const begin=(event:PointerEvent<HTMLButtonElement>,index:number,mark:Mark,mode:'move'|'resize')=>{event.stopPropagation();if(event.button!==0||disabled)return;onSelect(index,mark);const rect=event.currentTarget.closest('.iu-viewer-edit__paper')!.getBoundingClientRect();drag.current={index,mode,clientX:event.clientX,clientY:event.clientY,w:rect.width,h:rect.height,mark};event.currentTarget.setPointerCapture(event.pointerId)}
  const move=(event:PointerEvent<HTMLButtonElement>)=>{const d=drag.current;if(!d)return;const dx=(event.clientX-d.clientX)/d.w,dy=(event.clientY-d.clientY)/d.h;let patch:Partial<Mark>;if(d.mode==='move'){patch={x:Math.max(0,Math.min(1-(d.mark.width||.05),d.mark.x+dx)),y:Math.max(.01,Math.min(1-(d.mark.height||.02),d.mark.y+dy))}}else{const width=Math.max(.01,Math.min(1-d.mark.x,(d.mark.width||.1)+dx));patch={width,height:d.mark.keepRatio===false?Math.max(.01,Math.min(1-d.mark.y,(d.mark.height||.1)+dy)):Math.max(.01,Math.min(1-d.mark.y,(d.mark.height||.1)*width/(d.mark.width||.1)))}};setMoving({index:d.index,mark:{...d.mark,...patch}})}
  const finish=(event:PointerEvent<HTMLButtonElement>)=>{event.stopPropagation();const d=drag.current;if(!d)return;if(moving?.index===d.index)update(d.index,moving.mark);drag.current=null;setMoving(null)}
  const style=(mark:Mark):CSSProperties=>{if(mark.type==='image')return{left:`${mark.x*100}%`,top:`${mark.y*100}%`,width:`${(mark.width||.1)*100}%`,height:`${(mark.height||.1)*100}%`};const size=mark.fontSizePt||12,lines=(mark.text||'').split('\n'),leading=mark.lineHeightPt||size*1.2,w=pageInfo?.width||595,h=pageInfo?.height||842,width=Math.max(.025,Math.max(...lines.map(line=>line.length+3),1)*size*.6/w),height=(1.4*size+(lines.length-1)*leading)/h,offset=mark.align==='center'?50:mark.align==='right'?100:0;return{left:`${mark.x*100}%`,top:`${(mark.y-size/h)*100}%`,width:`${width*100}%`,height:`${height*100}%`,transform:`rotate(-${mark.rotation||0}deg) translateX(-${offset}%)`,transformOrigin:`0 ${size/h/height*100}%`}}
  return <>
    {marks.map((mark,index)=>mark.page===page&&['text','image'].includes(mark.type)?<div key={index} className={`iu-viewer-edit__object${selected===index?' is-selected':''}`} style={style(moving?.index===index?moving.mark:mark)}>
      <button type="button" className="iu-viewer-edit__object-target" aria-label={`Seleziona ${mark.type==='image'?'immagine':'testo'}: ${mark.imageName||mark.text}`} disabled={disabled} title="Trascina per spostare. Tasto destro per le azioni."
        onPointerDown={event=>begin(event,index,mark,'move')} onPointerMove={move} onPointerUp={finish} onPointerCancel={()=>{drag.current=null;setMoving(null)}}
        onContextMenu={event=>{event.preventDefault();event.stopPropagation();if(!disabled){onSelect(index,mark);setMenu({index,x:event.clientX,y:event.clientY})}}}
        onKeyDown={event=>{event.stopPropagation();if(event.key==='ContextMenu'||(event.shiftKey&&event.key==='F10')){event.preventDefault();const rect=event.currentTarget.getBoundingClientRect();onSelect(index,mark);setMenu({index,x:rect.left,y:rect.bottom});return}if(event.key==='Enter'||event.key===' '){event.preventDefault();onSelect(index,mark)}else if(event.key==='Delete'){event.preventDefault();onChange(marks.filter((_,i)=>i!==index))}else if(event.key.startsWith('Arrow')){event.preventDefault();const delta=event.shiftKey?.01:.002;update(index,{x:Math.max(0,Math.min(1-(mark.width||.05),mark.x+(event.key==='ArrowRight'?delta:event.key==='ArrowLeft'?-delta:0))),y:Math.max(.01,Math.min(1-(mark.height||.02),mark.y+(event.key==='ArrowDown'?delta:event.key==='ArrowUp'?-delta:0)))})}}}/>
      {mark.type==='image'&&selected===index?<button type="button" className="iu-viewer-edit__resize" aria-label="Ridimensiona immagine" disabled={disabled} onPointerDown={event=>begin(event,index,mark,'resize')} onPointerMove={move} onPointerUp={finish} onKeyDown={event=>{event.stopPropagation();if(['ArrowRight','ArrowDown','ArrowLeft','ArrowUp'].includes(event.key)){event.preventDefault();const factor=['ArrowRight','ArrowDown'].includes(event.key)?1.05:.95;update(index,{width:Math.min(1-mark.x,(mark.width||.1)*factor),height:Math.min(1-mark.y,(mark.height||.1)*factor)})}}}/>:null}
    </div>:null)}
    {menu&&marks[menu.index]?<div ref={menuRef} className="iu-viewer-edit__context" role="menu" aria-label="Azioni sull’oggetto" style={{left:Math.max(8,Math.min(menu.x,window.innerWidth-220)),top:Math.max(8,Math.min(menu.y,window.innerHeight-235))}} onPointerDown={event=>event.stopPropagation()} onKeyDown={event=>{if(event.key==='Escape'){event.preventDefault();setMenu(null)}if(['ArrowDown','ArrowUp'].includes(event.key)){event.preventDefault();const buttons=Array.from(menuRef.current?.querySelectorAll<HTMLButtonElement>('button')||[]);const i=buttons.indexOf(document.activeElement as HTMLButtonElement);buttons[(i+(event.key==='ArrowDown'?1:buttons.length-1))%buttons.length]?.focus()}}}>
      <button type="button" role="menuitem" onClick={()=>{onSelect(menu.index,marks[menu.index]);setMenu(null)}}>Modifica nel pannello</button>
      <button type="button" role="menuitem" onClick={()=>{const mark=marks[menu.index];onChange([...marks,{...mark,x:Math.min(1-(mark.width||.1),mark.x+.02),y:Math.min(1-(mark.height||.02),mark.y+.02)}]);setMenu(null)}}>Duplica</button>
      <button type="button" role="menuitem" onClick={()=>{const mark=marks[menu.index];update(menu.index,{rotation:((mark.rotation||0)+(mark.type==='text'?45:90))%360});setMenu(null)}}>Ruota {marks[menu.index].type==='text'?'45°':'90°'}</button>
      <button type="button" role="menuitem" onClick={()=>{onChange(marks.filter((_,i)=>i!==menu.index));setMenu(null)}}>Elimina oggetto</button>
    </div>:null}
  </>
}
