<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://schemi.processotelematico.giustizia.it/eventi/notaio"
           xmlns:pt="http://schemi.processotelematico.giustizia.it/tipi/atti/v7"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://schemi.processotelematico.giustizia.it/eventi/notaio" elementFormDefault="qualified"
           attributeFormDefault="unqualified" version="1.0">
    <xs:import namespace="http://schemi.processotelematico.giustizia.it/tipi" schemaLocation="tipi-base.xsd"/>
    <xs:import namespace="http://schemi.processotelematico.giustizia.it/tipi/anagrafiche/v4"
               schemaLocation="base_v4/tipi-anagrafiche.xsd"/>
    <xs:import namespace="http://schemi.processotelematico.giustizia.it/tipi/atti/v7"
               schemaLocation="base_v7/tipi-atti.xsd"/>
    <xs:annotation>
        <xs:documentation>Eventi associabili ad atti di notaio</xs:documentation>
    </xs:annotation>
    <xs:element name="depositoAutorizzazioneNotaioArt21" type="pt:IstanzaEvento">
        <xs:annotation>
            <xs:documentation>Deposito Istanza Autorizzazione Notaio Art 21</xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="depositoVisibilitaNotaioArt21" type="pt:IstanzaEvento">
        <xs:annotation>
            <xs:documentation>Deposito Autorizzazione Visibilita' Notaio Art 21</xs:documentation>
        </xs:annotation>
    </xs:element>
</xs:schema>

