"""Dati di prova realistici per ciascuno strumento forense.

Un valore per campo, scelto perche' plausibile in una pratica vera: servono a
provare che ogni strumento della pagina calcola davvero, non a fissare un
risultato atteso. Le attese sui numeri stanno nei test dei singoli calcolatori,
dove sono ancorate alla norma.

Il test `test_strumenti_legali_end_to_end` pretende una voce per ogni strumento
del catalogo: uno strumento nuovo senza dati di prova fa fallire la suite, ed e'
il modo per accorgersi subito di un modulo che nessuno ha mai eseguito.
"""

from __future__ import annotations

from typing import Dict

PAYLOAD_STRUMENTI: Dict[str, Dict[str, str]] = {
    "acconto_imposte": {
        "acc_rigo_differenza": "10000",
        "acc_imposta": "irpef",
        "acc_isa": "0",
    },
    "assegno_mantenimento": {
        "man_tipo": "figli",
        "man_reddito_obbligato": "10000",
        "man_reddito_beneficiario": "10000",
        "man_figli": "1",
        "man_collocamento_paritetico": "0",
        "man_casa_assegnata": "0",
        "man_durata_matrimonio": "10",
    },
    "canone_locazione": {
        "loc_canone": "800",
        "loc_perc_adeguamento": "75",
        "loc_anno_base": "2024",
        "loc_mese_base": "3",
        "loc_anno_fine": "2025",
        "loc_mese_fine": "3",
    },
    "capitalizzazione_rendita": {
        "cr_sesso": "maschi",
        "cr_eta": "45",
        "cr_reddito": "10000",
        "cr_eta_finale": "45",
        "cr_anni": "5",
        "cr_quota_perc": "100",
    },
    "categorie_catastali": {
        "catcat_gruppo": "TUTTI",
    },
    "cedolare_secca": {
        "cedolare_canone_annuo": "10000",
        "cedolare_aliquota": "21",
        "cedolare_annualita": "1",
    },
    "codice_fiscale": {
        "cf_cognome": "Rossi",
        "cf_nome": "Mario",
        "cf_sesso": "M",
        "cf_data_nascita": "1980-01-01",
        "cf_luogo": "Bari",
        "cf_provincia": "BA",
    },
    "compenso_a_tempo": {
        "cat_tariffa_oraria": "10000",
        "cat_ore": "10",
        "cat_minuti": "0",
        "cat_criterio": "ora_frazione_oltre_30",
        "cat_massimale_ore": "10",
        "cat_soglia_ore": "10",
        "cat_spese_generali_percent": "15",
    },
    "competenza_valore": {
        "comp_materia": "beni_mobili",
        "comp_valore": "10",
        "comp_data_introduzione": "2026-09-14",
    },
    "consenso_informato": {
        "ci_fascia": "media",
        "ci_posizione": "50",
        "ci_importo_eccezionale": "10000",
        "ci_trattamento_estetico": "0",
    },
    "conta_giorni": {
        "giorni_data_inizio": "2026-09-14",
        "giorni_data_fine": "2026-09-14",
    },
    "contributi_cassa_forense": {
        "cf_anno": "2026",
        "cf_reddito": "10000",
        "cf_compensi": "10000",
    },
    "contributo_unificato": {
        "cu_categoria": "civile_ordinario",
        "cu_grado": "primo_grado",
        "cu_valore_tipo": "indeterminabile",
        "cu_valore": "10",
        "cu_anticipazione_forfettaria": "1",
        "cu_numero_parti_ricorrenti": "1",
        "cu_sezione_specializzata_impresa": "0",
        "cu_dati_obbligatori_mancanti": "0",
    },
    "crediti_lavoro": {
        "lav_importo": "12000",
        "lav_data_maturazione": "2023-01-31",
        "lav_data_liquidazione": "2026-01-31",
        "lav_regime": "privato",
        "lav_tipo_indice": "foi",
        "lav_base_interessi": "rivalutato_progressivo",
    },
    "ctu": {
        "ctu_modalita": "vacazioni",
        "ctu_ore": "10",
        "ctu_vacazioni": "10000",
        "ctu_onorario": "10000",
        "ctu_spese": "10000",
        "ctu_cpa_perc": "4",
        "ctu_iva_perc": "22",
    },
    "custodia_cautelare": {
        "custodia_tipo_misura": "carcere",
        "custodia_data_esecuzione": "2026-09-14",
        "custodia_data_istanza_riesame": "2025-03-17",
        "custodia_data_decisione_riesame": "2025-03-17",
    },
    "danno_biologico": {
        "db_ambito": "circolazione",
        "db_data_sinistro": "2024-03-17",
        "db_data_liquidazione": "2026-03-17",
        "db_eta": "40",
        "db_perc_ip": "8",
        "db_giorni_itt": "15",
        "db_giorni_itp": "20",
        "db_perc_itp": "50",
        "db_morale_livello": "medio",
        "db_personalizzazione": "0",
    },
    "danno_parentale": {
        "dp_categoria": "nucleo_primario",
        "dp_eta_vittima": "55",
        "dp_eta_congiunto": "50",
        "dp_convivenza": "convivenza",
        "dp_superstiti": "2",
        "dp_qualita_relazione": "intensa",
    },
    "danno_premorienza": {
        "pm_perc_ip": "20",
        "pm_data_lesione": "2022-03-17",
        "pm_data_decesso": "2025-03-17",
        "pm_anni": "3",
        "pm_personalizzazione": "0",
    },
    "danno_terminale": {
        "dt_data_lesione": "2025-03-17",
        "dt_data_decesso": "2025-03-17",
        "dt_giorni": "30",
        "dt_importo_primi_tre": "10000",
        "dt_personalizzazione": "0",
    },
    "detrazione_canone": {
        "detcan_reddito": "10000",
        "detcan_tipo": "ordinario",
        "detcan_canone": "10000",
    },
    "detrazioni_familiari": {
        "detfam_reddito": "28000",
        "detfam_coniuge": "1",
        "detfam_figli": "1",
        "detfam_figli_totali": "1",
        "detfam_altri": "0",
    },
    "detrazioni_reddito": {
        "detred_reddito": "10000",
        "detred_tipo": "dipendente",
        "detred_determinato": "0",
        "detred_reddito_dipendente": "10000",
    },
    "diffamazione": {
        "df_fascia": "media",
        "df_posizione": "50",
        "df_importo_eccezionale": "10000",
        "df_riparazione": "0",
    },
    "fattura_agente": {
        "age_provvigioni": "10000",
        "age_collaboratori": "0",
    },
    "grado_parentela": {
        "par_relazione": "fratelli",
        "par_linea": "collaterale",
        "par_generazioni_su": "10000",
        "par_generazioni_giu": "10000",
        "par_affinita": "0",
    },
    "imposta_registro": {
        "reg_tipo_atto": "sentenza_condanna",
        "reg_valore": "10",
        "reg_parti": "2",
    },
    "imposte_compravendita": {
        "comp_regime": "privato",
        "comp_prezzo": "98.5",
        "comp_valore_catastale": "0",
        "comp_prima_casa": "0",
        "comp_lusso": "0",
    },
    "imposte_successione": {
        "succ_quota": "50",
        "succ_rapporto": "coniuge_linea_retta",
        "succ_handicap": "0",
        "succ_valore_immobili": "0",
        "succ_prima_casa": "0",
    },
    "impugnazioni": {
        "imp_mezzo": "appello",
        "imp_data_pubblicazione": "2026-03-17",
        "imp_data_notificazione": "2026-04-10",
        "imp_sospensione_feriale": "applica",
        "imp_riferimento": "RG 100/2026",
    },
    "imu": {
        "imu_rendita": "1200",
        "imu_gruppo": "a_non_a10",
        "imu_aliquota": "0.86",
        "imu_abitazione_principale": "0",
        "imu_lusso": "0",
        "imu_mesi": "12",
        "imu_quota": "100",
        "imu_residenti": "1",
    },
    "indennita_licenziamento": {
        "lic_retribuzione_mensile": "10000",
        "lic_anni_servizio": "5",
        "lic_mesi_servizio": "6",
        "lic_regime": "jobs_act",
        "lic_mensilita_preavviso": "0",
    },
    "indennita_mediazione": {
        "med_valore": "10",
        "med_valore_tipo": "determinato",
        "med_regime": "volontaria",
        "med_esito": "primo_incontro_senza_accordo",
        "med_art31": "0",
    },
    "interessi": {
        "int_tipo": "legali",
        "int_capitale": "10000",
        "int_data_inizio": "2026-09-14",
        "int_data_fine": "2026-09-14",
    },
    "interessi_acconti": {
        "acc_tipo": "legali",
        "acc_capitale": "10000",
        "acc_data_inizio": "2026-09-14",
        "acc_data_fine": "2026-09-14",
    },
    "irpef": {
        "irpef_reddito": "10000",
        "irpef_anno": "2026",
    },
    "lite_temeraria": {
        "lt_compenso": "10000",
        "lt_parti": "1",
        "lt_valore_elevato": "0",
        "lt_processo_lungo": "0",
        "lt_piu_parti": "0",
        "lt_dolo": "0",
        "lt_affaticamento": "0",
    },
    "maggior_danno": {
        "md_importo": "10000",
        "md_base_interessi": "rivalutato_annuale",
        "md_anno_base": "2023",
        "md_mese_base": "1",
        "md_anno_fine": "2026",
        "md_mese_fine": "1",
    },
    "nota_credito": {
        "note_tribunale": "Tribunale di Bari",
        "note_rg": "100/2026",
        "note_creditore": "Mario Rossi",
        "note_debitore": "Bianchi S.r.l.",
        "note_titolo": "Decreto ingiuntivo n. 50/2026",
        "note_capitale": "15000",
        "note_interessi_tipo": "legali",
        "note_interessi_manual": "0",
        "note_data_inizio": "2024-01-15",
        "note_data_fine": "2026-01-15",
        "note_spese_vive": "200",
        "note_compensi": "2500",
        "note_cpa_perc": "4",
        "note_iva_perc": "22",
        "note_acconti": "0",
        "note_luogo": "Bari",
        "note_data": "2026-03-17",
        "note_avvocato": "Avv. Verdi",
    },
    "onorari_forensi": {
        "onorari_materia": "CIVILE_COGN",
        "onorari_grado": "TRIBUNALE",
        "onorari_valore": "10",
        "onorari_complessita": "media",
        "onorari_bonus_telematico": "0",
        "onorari_includi_spese_generali": "1",
        "onorari_cliente_qualificato": "0",
        "onorari_convenzione_predisposta_avvocato": "0",
        "onorari_equo_compenso_verificato": "0",
        "onorari_informativa_scritta": "0",
    },
    "patrocinio_spese_stato": {
        "pat_processo": "civile",
        "pat_reddito_richiedente": "9000",
        "pat_redditi_conviventi": "4000",
        "pat_familiari_conviventi": "2",
        "pat_solo_reddito_personale": "0",
        "pat_data_riferimento": "2026-03-17",
    },
    "pena_riti_alternativi": {
        "pena_anni": "2",
        "pena_mesi": "6",
        "pena_giorni": "0",
        "pena_tipo_reato": "delitto",
        "pena_eta_imputato": "35",
        "pena_rito": "abbreviato",
        "pena_frazione_patteggiamento": "un_terzo",
        "pena_attenuanti_generiche": "1",
        "pena_reati_satellite": "0",
        "pena_aumento_per_reato_giorni": "0",
        "pena_recidiva_reiterata": "0",
        "pena_mancata_impugnazione": "0",
    },
    "percentuali": {
        "perc_base": "1000",
        "perc_percento": "10",
        "perc_parte": "250",
    },
    "perfezionamento_notifica": {
        "not_canale": "pec",
        "not_data_invio": "2026-09-14",
        "not_data_consegna": "2026-09-14",
        "not_esito_posta": "consegnato",
        "not_data_avviso": "2025-03-17",
        "not_data_ritiro": "2025-03-17",
        "not_termine_durata": "10",
        "not_termine_unita": "giorni",
        "not_sospensione_feriale": "applica",
    },
    "piano_ammortamento": {
        "amm_capitale": "10000",
        "amm_tasso_annuo": "4",
        "amm_durata_anni": "10",
        "amm_rate_anno": "12",
        "amm_tipo": "francese",
        "amm_data_prima_rata": "2026-09-14",
    },
    "pignoramento": {
        "pig_tipo_reddito": "stipendio",
        "pig_tipo_credito": "ordinario",
        "pig_importo_netto": "10000",
        "pig_aliquota_alimentare": "33.33",
    },
    "prescrizione": {
        "presc_tipo": "ordinaria_10",
        "presc_data_decorrenza": "2026-09-14",
        "presc_atto_interruttivo": "2025-03-17",
    },
    "prescrizione_penale": {
        "presc_data_fatto": "2026-09-14",
        "presc_ergastolo": "0",
        "presc_massimo_edittale_anni": "6",
        "presc_massimo_edittale_mesi": "0",
        "presc_contravvenzione": "0",
        "presc_raddoppio": "0",
        "presc_coeff_interruzione": "1.25",
        "presc_giorni_sospensione": "0",
    },
    "prestazione_occasionale": {
        "occ_compenso": "10000",
        "occ_rimborsi": "0",
        "occ_anticipazioni": "0",
        "occ_sostituto": "1",
    },
    "procedibilita_adr": {
        "adr_materia": "condominio",
        "adr_procedimento": "ordinario",
        "adr_valore": "10",
        "adr_consumatore": "0",
        "adr_data_avvio": "2025-03-17",
    },
    "pronti_contro_termine": {
        "pct_prezzo_pronti": "98.5",
        "pct_prezzo_termine": "98.5",
        "pct_giorni": "30",
    },
    "quote_riserva": {
        "ris_patrimonio": "10000",
        "ris_debiti": "10000",
        "ris_donazioni": "10000",
        "ris_coniuge": "1",
        "ris_figli": "0",
        "ris_ascendenti": "0",
    },
    "rateazione_imposte": {
        "rate_importo": "12",
        "rate_numero": "6",
    },
    "ravvedimento_operoso": {
        "rav_tipo_violazione": "omesso_versamento",
        "rav_imposta": "10000",
        "rav_sanzione_minima": "10000",
        "rav_data_scadenza": "2025-03-17",
        "rav_data_versamento": "2026-09-14",
        "rav_evento": "nessuno",
    },
    "regime_forfettario": {
        "forf_ricavi": "10000",
        "forf_gruppo": "professionali",
        "forf_contributi": "0",
        "forf_startup": "0",
    },
    "rendimento_bot": {
        "bot_prezzo": "98.5",
        "bot_giorni": "30",
        "bot_nominale": "100",
        "bot_commissioni": "0",
    },
    "reversibilita": {
        "rev_pensione_annua": "10000",
        "rev_coniuge": "1",
        "rev_figli": "0",
        "rev_genitori": "0",
        "rev_fratelli": "0",
        "rev_reddito_beneficiario": "0",
        "rev_trattamento_minimo": "10000",
        "rev_figli_tutelati": "0",
    },
    "riparto_spese": {
        "rip_importo": "3000",
        "rip_criterio": "millesimi",
        "rip_quote": "Interno 1: 350\nInterno 2: 400\nInterno 3: 250",
    },
    "rivalutazione_istat": {
        "riv_importo": "10000",
        "riv_tipo": "foi",
        "riv_anno_base": "2023",
        "riv_mese_base": "1",
        "riv_anno_fine": "2026",
        "riv_mese_fine": "1",
    },
    "rivalutazione_media": {
        "rivm_importo": "10000",
        "rivm_anno_base": "2023",
        "rivm_anno_target": "2025",
        "rivm_tipo": "FOI",
    },
    "scorporo_iva": {
        "iva_verso": "scorporo",
        "iva_importo": "10000",
        "iva_aliquota": "22",
    },
    "successione_legittima": {
        "successione_asse": "300000",
        "successione_coniuge": "1",
        "successione_figli": "2",
        "successione_ascendenti": "0",
        "successione_fratelli": "0",
    },
    "surroga": {
        "sur_debito_residuo": "120000",
        "sur_tan_attuale": "4.5",
        "sur_anni_residui": "15",
        "sur_tan_nuovo": "3.2",
        "sur_anni_nuovi": "15",
        "sur_rate_anno": "12",
    },
    "tabella_istat": {
        "istat_tipo": "FOI",
        "istat_anni": "5",
    },
    "tabella_tassi": {
        "tassi_vista": "entrambe",
    },
    "taeg": {
        "taeg_capitale": "120000",
        "taeg_tan": "3.5",
        "taeg_durata_anni": "20",
        "taeg_rate_anno": "12",
        "taeg_spese_iniziali": "1500",
        "taeg_spese_rata": "2",
        "taeg_spese_annue": "30",
    },
    "termini_processuali": {
        "term_modello": "CIV_APPELLO_BREVE",
        "term_data_evento": "2026-09-14",
        "term_urgente": "0",
        "term_valore_personalizzato": "10",
    },
    "tfr": {
        "tfr_retribuzione_annua": "10000",
        "tfr_anni_servizio": "5",
        "tfr_mesi_servizio": "6",
        "tfr_inflazione_perc": "2.00",
        "tfr_anticipazioni": "10000",
        "tfr_montante_pregresso": "10000",
    },
    "uffici_competenti": {
        "comune": "Bari",
        "includi_speciali": "1",
    },
    "usufrutto": {
        "usu_valore_piena": "10",
        "usu_eta": "45",
        "usu_quota_perc": "100",
    },
    "usura": {
        "usura_tasso": "4",
        "usura_categoria": "credito_personale",
        "usura_data": "2026-09-14",
    },
    "valore_catastale": {
        "cat_rendita": "1200",
        "cat_gruppo": "abitazione_altri",
        "cat_ambito": "registro",
    },
    "valore_causa": {
        "val_criterio": "somma_mobili",
        "val_importo": "10000",
        "val_annualita": "5",
        "val_diritto": "proprieta",
        "val_altre_domande": "10000",
        "val_interessi_scaduti": "10000",
        "val_spese_danni": "5",
    },
}
