<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://schemi.processotelematico.giustizia.it/unep/siecic/tipibase"
           xmlns:bt="http://schemi.processotelematico.giustizia.it/unep/tipi"
           xmlns:at="http://schemi.processotelematico.giustizia.it/unep/tipi/anagrafiche"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://schemi.processotelematico.giustizia.it/unep/siecic/tipibase"
           elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
    <xs:import namespace="http://schemi.processotelematico.giustizia.it/unep/tipi" schemaLocation="./tipi-base.xsd"/>
    <xs:import namespace="http://schemi.processotelematico.giustizia.it/unep/tipi/anagrafiche"
               schemaLocation="./tipi-anagrafiche.xsd"/>
    <xs:include schemaLocation="./enum/tipi-enum-siecic.xsd"/>
    <xs:complexType name="TitoloEsecutivo">
        <xs:annotation>
            <xs:documentation>Informazioni specifiche per un titolo esecutivo</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="descrizione" type="xs:string"/>
            <xs:element name="ipoteca" nillable="true" minOccurs="0" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>Elemento nillable se non esiste ipoteca associata al titolo. L'assenza
                        dell'elemento indica la non indicazione dei dati relativi un ipoteca esistente
                    </xs:documentation>
                </xs:annotation>
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="numero" type="xs:positiveInteger"/>
                        <xs:element name="anno" type="xs:positiveInteger"/>
                        <xs:element name="dataIscrizione" type="xs:date"/>
                        <xs:element name="importo" type="bt:Valuta"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="numero" minOccurs="0" type="xs:positiveInteger"/>
            <xs:element name="dataEmissione" minOccurs="0" type="xs:date"/>
        </xs:sequence>
        <xs:attribute name="tipologia" type="TipologiaTitolo" use="required"/>
    </xs:complexType>
    <xs:complexType name="Titolo">
        <xs:annotation>
            <xs:documentation>Informazioni per un titolo di credito vantato verso uno o più debitori</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:choice>
                <xs:element name="titoloEsecutivo" type="TitoloEsecutivo"/>
                <xs:element name="titoloNonEsecutivo">
                    <xs:complexType>
                        <xs:attribute name="tipologia" type="TipologiaTitoloNonEsecutivo" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
            <xs:element ref="debitore" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>Debitore verso il quale è vantato il titolo</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Diritto">
        <xs:annotation>
            <xs:documentation>Rappresentazione del diritto vantabile su un bene mobile o immobile</xs:documentation>
        </xs:annotation>
        <xs:simpleContent>
            <xs:extension base="TipologiaDiritto">
                <xs:attribute name="quota" type="xs:float" use="required"/>
                <xs:attribute name="stato" use="optional" default="Inventariato">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Inventariato"/>
                            <xs:enumeration value="NonRinvenuto"/>
                            <xs:enumeration value="InventariatoTerzo"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
                <xs:attribute name="stima" type="bt:Valuta"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="DatiCatastali">
        <xs:annotation>
            <xs:documentation>Dati necessari per l’identificazione catastale di un bene immobile</xs:documentation>
        </xs:annotation>
        <xs:all>
            <xs:element name="sezione" type="xs:string"/>
            <xs:element name="foglio" type="xs:string"/>
            <xs:element name="particella" type="xs:string"/>
            <xs:element name="subparticella" type="xs:string" minOccurs="0"/>
            <xs:element name="subalterno" type="xs:string" minOccurs="0"/>
            <xs:element name="subalterno2" type="xs:string" minOccurs="0"/>
            <xs:element name="graffato" type="xs:string" minOccurs="0"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="BeneImmobile">
        <xs:annotation>
            <xs:documentation>Informazioni complete bene immobile</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="descrizione" type="xs:string">
                <xs:annotation>
                    <xs:documentation>Descrizione del bene</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="indirizzo" type="at:Indirizzo"/>
            <xs:element name="catasto">
                <xs:annotation>
                    <xs:documentation>Tipologia di catasto: urbano / terreni</xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="NCEU">
                            <xs:annotation>
                                <xs:documentation>Nuovo Catasto Edilizio Urbano</xs:documentation>
                            </xs:annotation>
                        </xs:enumeration>
                        <xs:enumeration value="NCT">
                            <xs:annotation>
                                <xs:documentation>Nuovo Catasto Terreni</xs:documentation>
                            </xs:annotation>
                        </xs:enumeration>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:choice>
                <xs:element name="datiCatastali" type="DatiCatastali" maxOccurs="unbounded"/>
                <xs:element name="datiDenuncia">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="tipologia">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="P">
                                            <xs:annotation>
                                                <xs:documentation>Protocollo</xs:documentation>
                                            </xs:annotation>
                                        </xs:enumeration>
                                        <xs:enumeration value="S">
                                            <xs:annotation>
                                                <xs:documentation>Scheda</xs:documentation>
                                            </xs:annotation>
                                        </xs:enumeration>
                                        <xs:enumeration value="V">
                                            <xs:annotation>
                                                <xs:documentation>Variazione</xs:documentation>
                                            </xs:annotation>
                                        </xs:enumeration>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="numero" type="xs:int"/>
                            <xs:element name="anno" type="xs:int"/>
                            <xs:element name="data" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
            <xs:element name="classe">
                <xs:annotation>
                    <xs:documentation>Classe / tipologia del bene</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="TipologiaClasseImmobiliare">
                            <xs:attribute name="classato" type="xs:boolean" use="required"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:choice minOccurs="0">
                <xs:sequence>
                    <xs:annotation>
                        <xs:documentation>Informazioni specifiche per accatastamenti "urbani"</xs:documentation>
                    </xs:annotation>
                    <xs:element name="edificio" type="xs:string"/>
                    <xs:element name="scala" type="xs:string"/>
                    <xs:element name="interno" type="xs:string"/>
                    <xs:element name="piano" type="xs:string"/>
                    <xs:element name="vani" type="xs:int"/>
                </xs:sequence>
                <xs:sequence>
                    <xs:annotation>
                        <xs:documentation>Informazioni specifiche per accatastamenti "terreni"</xs:documentation>
                    </xs:annotation>
                    <xs:element name="superficie">
                        <xs:complexType>
                            <xs:simpleContent>
                                <xs:extension base="xs:double">
                                    <xs:attribute name="unitamisura" type="UnitaMisuraSuperficie" use="required"/>
                                </xs:extension>
                            </xs:simpleContent>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:choice>
            <xs:element name="riferimento" type="xs:string" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>Numero di riferimento dell'immobile nel sistema di gestione registroi
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="ID" type="xs:NMTOKEN" use="optional">
            <xs:annotation>
                <xs:documentation>Chiave opzionale per l'identificazione del bene</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
    <xs:complexType name="BeneMobile">
        <xs:annotation>
            <xs:documentation>Informazioni complete bene mobile</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="tipologia" type="xs:string">
                <xs:annotation>
                    <xs:documentation>La codifica è descritta nell'allegato 1 della Documentazione Specifica di
                        Interoperabilità
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="descrizione" type="xs:string"/>
            <xs:element name="ubicazione" type="at:Indirizzo" minOccurs="0"/>
            <xs:element name="quantita" minOccurs="0">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:double">
                            <xs:attribute name="unitamisura" type="UnitaMisuraQuantita" default="UN"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="riferimentoInventario" type="xs:string" minOccurs="0"/>
            <xs:element name="dataInventario" type="xs:date" minOccurs="0"/>
            <xs:element name="valoreBene" type="bt:Valuta" minOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="ID" type="xs:NMTOKEN" use="optional">
            <xs:annotation>
                <xs:documentation>Chiave opzionale per l'identificazione del bene</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
    <xs:element name="debitore" type="at:RiferimentoSoggetto">
        <xs:annotation>
            <xs:documentation>Riferimento ad un debitore già censito dal sistema</xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="beneImmobile" type="BeneImmobile">
        <xs:annotation>
            <xs:documentation>Specifica di un bene immobile</xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="beneMobile" type="BeneMobile">
        <xs:annotation>
            <xs:documentation>Specifica di un bene mobile</xs:documentation>
        </xs:annotation>
    </xs:element>
</xs:schema>
