"""Central registry for operational sources available to Lex."""

from __future__ import annotations

from .models import OperationalSourceDefinition


def _src(
    source_id: str,
    display_name: str,
    source_type: str,
    category: str,
    *,
    tenant_keys: tuple[str, ...],
    permissions: tuple[str, ...],
    repository_module: str,
    api_surface: str = "",
    tools: tuple[str, ...] = (),
    internal: bool = True,
    sensitive: bool = True,
    document_retrieval: bool = False,
    official_public_source: bool = False,
    notes: str = "",
) -> OperationalSourceDefinition:
    return OperationalSourceDefinition(
        source_id=source_id,
        display_name=display_name,
        source_type=source_type,
        category=category,
        tenant_keys=tenant_keys,
        required_permissions=permissions,
        repository_module=repository_module,
        api_surface=api_surface,
        deterministic_tools=tools,
        internal=internal,
        sensitive=sensitive,
        document_retrieval=document_retrieval,
        official_public_source=official_public_source,
        notes=notes,
    )


DEFAULT_SOURCE_DEFINITIONS: tuple[OperationalSourceDefinition, ...] = (
    _src(
        "clienti",
        "Clienti",
        "cliente",
        "anagrafica",
        tenant_keys=("CLIENTI_DB",),
        permissions=("clienti.leggi",),
        repository_module="pct.clienti.GestioneClienti",
        api_surface="web.helpers.get_clienti",
        tools=("search_clienti", "get_cliente_by_id"),
    ),
    _src(
        "soggetti",
        "Soggetti e parti",
        "soggetto",
        "anagrafica",
        tenant_keys=("SOGGETTI_DB", "SOGGETTI_PARTI_DB"),
        permissions=("clienti.leggi",),
        repository_module="pct.soggetti.GestioneSoggetti",
        api_surface="web.helpers.get_soggetti",
        tools=("search_soggetti", "get_soggetto", "parti_by_fascicolo", "parti_by_soggetto"),
    ),
    _src(
        "fascicoli",
        "Fascicoli",
        "fascicolo",
        "pratiche",
        tenant_keys=("FASCICOLI_DB", "FASCICOLI_DOCS", "FASCICOLI_ARCH"),
        permissions=("fascicoli.leggi",),
        repository_module="pct.fascicoli.GestioneFascicoli",
        api_surface="web.helpers.get_fascicoli",
        tools=("search_fascicoli", "get_fascicolo"),
    ),
    _src(
        "agenda",
        "Agenda",
        "agenda",
        "operativo",
        tenant_keys=("AGENDA_DB",),
        permissions=("agenda.leggi",),
        repository_module="pct.agenda.Agenda",
        api_surface="web.helpers.get_agenda",
        tools=("get_agenda_range",),
    ),
    _src(
        "scadenziario",
        "Scadenziario",
        "scadenza",
        "operativo",
        tenant_keys=("SCADENZIARIO_DB",),
        permissions=("scadenziario.leggi",),
        repository_module="pct.scadenziario.GestioneScadenziario",
        api_surface="web.helpers.get_scadenziario",
        tools=("get_scadenze_by_fascicolo", "get_scadenze_by_cliente"),
    ),
    _src(
        "preventivi",
        "Preventivi",
        "preventivo",
        "economico",
        tenant_keys=("PREVENTIVI_DB",),
        permissions=("fatturazione.leggi",),
        repository_module="pct.preventivi.GestionePreventivi",
        api_surface="web.helpers.get_preventivi",
        tools=("get_preventivo", "search_preventivi"),
    ),
    _src(
        "conferimenti",
        "Conferimenti incarico",
        "conferimento",
        "economico",
        tenant_keys=("PREVENTIVI_DB",),
        permissions=("fatturazione.leggi",),
        repository_module="pct.preventivi.GestionePreventivi",
        api_surface="web.helpers.get_preventivi",
        tools=("get_conferimento", "search_conferimenti"),
    ),
    _src(
        "tariffario",
        "Tariffario forense",
        "tariffario",
        "economico",
        tenant_keys=(),
        permissions=("fatturazione.leggi",),
        repository_module="pct.tariffario",
        tools=("get_tariffario_result",),
        sensitive=False,
    ),
    _src(
        "fatturazione",
        "Parcelle e fatturazione",
        "parcella",
        "economico",
        tenant_keys=("FATTURAZIONE_DB",),
        permissions=("fatturazione.leggi",),
        repository_module="pct.fatturazione.GestioneFatturazione",
        api_surface="web.helpers.get_fatturazione",
        tools=("get_parcelle_by_cliente", "get_parcelle_by_fascicolo"),
    ),
    _src(
        "timesheet",
        "Attivita' e timesheet",
        "attivita",
        "economico",
        tenant_keys=("TIMESHEET_DB",),
        permissions=("fatturazione.leggi",),
        repository_module="pct.timesheet.GestioneTimesheet",
        api_surface="web.helpers.get_timesheet",
        tools=("get_attivita_by_cliente", "get_attivita_by_fascicolo"),
    ),
    _src(
        "documenti_fascicolo",
        "Documenti fascicolo",
        "documento",
        "documentale",
        tenant_keys=("FASCICOLI_DB", "FASCICOLI_DOCS"),
        permissions=("fascicoli.leggi",),
        repository_module="pct.document_intelligence",
        api_surface="DocumentAIRepository.from_fascicoli_db",
        tools=("get_documenti_fascicolo", "search_documenti_fascicolo"),
        document_retrieval=True,
    ),
    _src(
        "messaggi",
        "Messaggi inviati e comunicazioni",
        "messaggio",
        "comunicazioni",
        tenant_keys=("MESSAGGI_DB",),
        permissions=("messaggi.leggi",),
        repository_module="pct.messaggi.GestioneMessaggi",
        tools=("get_messaggi_by_cliente", "get_messaggi_by_fascicolo"),
    ),
    _src(
        "email_pec",
        "Email PEC",
        "email_pec",
        "comunicazioni",
        tenant_keys=("EMAIL_CASELLA_DB",),
        permissions=("messaggi.leggi",),
        repository_module="pct.email_client.GestioneEmailRicevute",
        tools=("list_pec_messages", "get_pec_message", "list_pec_attachments"),
        document_retrieval=True,
        notes="Inventario PEC tenant-aware con allegati letti tramite reader compatibile zip/file sciolti.",
    ),
    _src(
        "pec_audit",
        "Controlli automatici PEC",
        "pec_audit",
        "comunicazioni",
        tenant_keys=("EMAIL_CASELLA_DB", "PEC_AUDIT_DB"),
        permissions=("messaggi.leggi",),
        repository_module="pct.pec_pipeline.PecAuditRepository",
        api_surface="/api/pec/*",
        tools=("list_pec_audit_messages", "get_pec_audit_message", "get_pec_audit_for_email"),
        document_retrieval=True,
        notes="MIME originale, parsed JSON versionato, confidence, allegati, firme, matrice validazione, riconciliazione fascicolo, contesti normativi PEC/PCT/L.53/PAT/PTT/SNT/PDP e audit append-only.",
    ),
    _src(
        "pec_control_tower",
        "PEC Control Tower",
        "evento_pec",
        "comunicazioni",
        tenant_keys=("EMAIL_CASELLA_DB", "PEC_CONTROL_TOWER_DB", "FASCICOLI_DB", "SCADENZIARIO_DB", "AGENDA_DB"),
        permissions=("messaggi.leggi", "fascicoli.leggi"),
        repository_module="pct.pec_control_tower.PecControlTowerRepository",
        api_surface="/api/pec/ingest, /api/communications, /api/deadlines, /api/notifications/*",
        tools=("answer_pec_control_question", "list_pec_control_events"),
        document_retrieval=True,
        notes="Ogni PEC viene trasformata in evento giuridico tracciato con fascicolo, scadenze in bozza, agenda, task, notifiche, prove e audit HMAC; Lex puo' rispondere a domande operative senza confermare automaticamente termini legali.",
    ),
    _src(
        "email_ordinaria",
        "Email ordinaria",
        "email_ordinaria",
        "comunicazioni",
        tenant_keys=("EMAIL_ORDINARIA_DB",),
        permissions=("messaggi.leggi",),
        repository_module="pct.email_client.GestioneEmailRicevute",
        tools=("list_ordinary_email_messages", "get_ordinary_email_message", "list_ordinary_email_attachments"),
        document_retrieval=True,
        notes="Inventario posta ordinaria tenant-aware: nessun fallback automatico su /data/email in multi-studio.",
    ),
    _src(
        "notifiche",
        "Notifiche",
        "notifica",
        "operativo",
        tenant_keys=("NOTIFICATIONS_DB",),
        permissions=(),
        repository_module="pct.notifications.NotificationRepository",
        api_surface="web.services.notifications_runtime",
        tools=("get_notifiche_utente",),
    ),
    _src(
        "telematico",
        "Portali e telematico",
        "telematico",
        "portali",
        tenant_keys=("TELEMATICO_DB", "PDP_PENALE_DB", "PORTALE_DB"),
        permissions=("telematico.leggi",),
        repository_module="web.services.pdp_penale_runtime / pct.*",
        tools=("get_telematico_status",),
    ),
    _src(
        "pagamenti",
        "Pagamenti",
        "pagamento",
        "economico",
        tenant_keys=("PAGAMENTI_DIR",),
        permissions=("fatturazione.leggi",),
        repository_module="pct.pagamenti.GestionePagamenti",
        api_surface="web.helpers.get_pagamenti",
        tools=("get_pagamenti_status",),
    ),
    _src(
        "sito_studio",
        "Sito studio",
        "sito_studio",
        "pubblicazione",
        tenant_keys=("PORTALE_DB", "PORTALE_UPLOADS", "CONFIG_STUDIO_DB"),
        permissions=(),
        repository_module="pct.portale / web.services.react_sito_studio_bridge",
        tools=("get_sito_studio_status",),
    ),
    _src(
        "ricerca_studio",
        "Ricerca studio",
        "ricerca",
        "operativo",
        tenant_keys=("SEARCH_INDEX",),
        permissions=("fascicoli.leggi",),
        repository_module="pct.search_index.IndiceRicerca",
        api_surface="web.helpers.get_indice_ricerca",
        tools=("search_studio_index",),
        document_retrieval=True,
    ),
    _src(
        "privacy_gdpr",
        "Registro GDPR",
        "privacy",
        "governance",
        tenant_keys=("PRIVACY_DB", "AUDIT_DB"),
        permissions=("ai.audit",),
        repository_module="web.services.react_privacy_bridge",
        tools=("get_privacy_registry_status",),
    ),
    _src(
        "backup_storage",
        "Backup e spazio",
        "storage",
        "manutenzione",
        tenant_keys=("BACKUP_DIR", "PCT_DATA_ROOT"),
        permissions=("ai.audit",),
        repository_module="pct.backup / web.services.server_maintenance",
        tools=("get_storage_status",),
    ),
    _src(
        "database",
        "Database studio",
        "database",
        "governance",
        tenant_keys=("STUDIO_DB", "DATABASE_URL"),
        permissions=("ai.audit",),
        repository_module="pct.database / pct.storage_migration_full",
        tools=("get_database_status",),
    ),
    _src(
        "uffici_giudiziari",
        "Uffici giudiziari",
        "ufficio",
        "portali",
        tenant_keys=("UFFICI_GIUDIZIARI_DB", "REGINDE_DB"),
        permissions=("telematico.leggi",),
        repository_module="pct.uffici_giudiziari",
        tools=("lookup_uffici_giudiziari",),
        sensitive=False,
    ),
    _src(
        "ai_locale",
        "AI locale e RAG",
        "ai_locale",
        "lex",
        tenant_keys=("LOCAL_AI_DB", "WORKSPACE_INTELLIGENCE_DB"),
        permissions=("ai.usa",),
        repository_module="pct.local_ai / pct.workspace_intelligente",
        tools=("get_ai_local_status",),
        document_retrieval=True,
    ),
    _src(
        "template_atti",
        "Template atti",
        "template_atto",
        "documentale",
        tenant_keys=("TEMPLATE_ATTI_DB",),
        permissions=("fascicoli.leggi",),
        repository_module="pct.template_atti.GestioneTemplateAtti",
        tools=("search_template_atti",),
        sensitive=False,
    ),
    _src(
        "editor_ai",
        "Editor atti con Lex",
        "editor_ai",
        "documentale",
        tenant_keys=("FASCICOLI_DB", "FASCICOLI_DOCS", "TEMPLATE_ATTI_DB", "LOCAL_AI_DB"),
        permissions=("fascicoli.leggi",),
        repository_module="pct.editor_ai / lex.tools.editor_ai",
        api_surface="/api/v1/ui/fascicoli/<id>/editor-ai/*",
        tools=(
            "get_editor_ai_status",
            "list_template_atti",
            "read_template_atto",
            "collect_fascicolo_context",
            "generate_editor_draft",
            "read_editor_document",
            "propose_editor_edits",
            "export_editor_document",
        ),
        document_retrieval=True,
        notes="Supporto Lex per editor normale/professionale, con bozza reale nel fascicolo e proposte pending.",
    ),
    _src(
        "citazioni_cassazione",
        "Citazioni verificate Cassazione",
        "giurisprudenza",
        "fonti_pubbliche",
        tenant_keys=("GIURISPRUDENZA_DB", "LEGAL_INTELLIGENCE_DB"),
        permissions=(),
        repository_module="pct.giurisprudenza / lex.retrieval.official_web",
        tools=("search_verified_cassazione", "get_giurisprudenza_items"),
        sensitive=False,
        official_public_source=True,
        notes="Le massime e citazioni devono derivare da corpus verificato o fonte ufficiale; nessuna citazione inventata.",
    ),
    _src(
        "chat_lex_editor",
        "Chat Lex nell'editor",
        "chat_editor",
        "documentale",
        tenant_keys=("FASCICOLI_DB", "FASCICOLI_DOCS", "LOCAL_AI_DB", "TEMPLATE_ATTI_DB"),
        permissions=("fascicoli.leggi",),
        repository_module="pct.editor_ai / lex.tools.editor_ai / pct.local_ai",
        tools=("read_editor_document", "propose_editor_edits", "collect_fascicolo_context"),
        document_retrieval=True,
        notes="Copilota redazionale: legge il documento corrente, propone modifiche pending e non applica senza conferma.",
    ),
    _src(
        "contratti_pareri",
        "Contratti e pareri",
        "redazione",
        "documentale",
        tenant_keys=("TEMPLATE_ATTI_DB", "FASCICOLI_DB", "FASCICOLI_DOCS"),
        permissions=("fascicoli.leggi",),
        repository_module="pct.template_atti / pct.editor_ai",
        tools=("search_template_atti", "generate_editor_draft"),
        document_retrieval=True,
        notes="Supporto a contratti, pareri e atti con clausole, rischi e alternative sempre da verificare.",
    ),
    _src(
        "pdf_manager",
        "PDF Manager",
        "documento",
        "documentale",
        tenant_keys=("FASCICOLI_DOCS", "OCR_JOBS_DB", "SEARCH_INDEX"),
        permissions=("fascicoli.leggi",),
        repository_module="pct.validazione / pct.pdf_tools / pct.local_ai",
        tools=("get_pdf_tools_status",),
        document_retrieval=True,
        notes="Unione, compressione, OCR, PDF/A e controlli deposito: Lex legge stato e suggerisce il prossimo controllo.",
    ),
    _src(
        "firma_digitale",
        "Firma digitale",
        "firma",
        "telematico",
        tenant_keys=("STUDIO_CONFIG", "CONFIG_STUDIO_DB", "FASCICOLI_DOCS"),
        permissions=("telematico.leggi",),
        repository_module="pct.firma / integrazioni provider firma",
        tools=("get_firma_digitale_status",),
        notes="Aruba, InfoCert e Namirial richiedono integrazione provider verificata; Lex segnala prerequisiti senza firmare automaticamente.",
    ),
    _src(
        "fatturazione_elettronica_sdi",
        "Fatturazione elettronica e SDI",
        "fatturazione_sdi",
        "economico",
        tenant_keys=("FATTURAZIONE_DB", "PAGAMENTI_DIR", "CONFIG_STUDIO_DB"),
        permissions=("fatturazione.leggi",),
        repository_module="pct.fattura_pa / pct.fatturazione",
        tools=("get_sdi_status",),
        notes="Emissione, notifiche e conservazione devono restare tracciate e non inviate da Lex senza azione umana.",
    ),
    _src(
        "client_portal",
        "Portale cliente",
        "portale_cliente",
        "pubblicazione",
        tenant_keys=("PORTALE_DB", "PORTALE_UPLOADS", "FASCICOLI_DB", "CLIENTI_DB"),
        permissions=("clienti.leggi", "fascicoli.leggi"),
        repository_module="pct.portale / web.blueprints.portale",
        tools=("get_client_portal_status",),
        notes="Accessi token, documenti condivisi, messaggistica e timeline devono essere letti solo per il tenant corrente.",
    ),
    _src(
        "antiriciclaggio",
        "Antiriciclaggio",
        "compliance",
        "governance",
        tenant_keys=("CLIENTI_DB", "PRIVACY_DB", "AUDIT_DB"),
        permissions=("clienti.leggi", "ai.audit"),
        repository_module="pct.compliance / web.services.react_privacy_bridge",
        tools=("get_aml_status",),
        notes="Valutazione rischio e adeguata verifica: Lex puo' evidenziare lacune, non certificare conformita' automatica.",
    ),
    _src(
        "rest_api_webhooks",
        "REST API e webhooks",
        "integrazione",
        "governance",
        tenant_keys=("AUDIT_DB", "CONFIG_STUDIO_DB"),
        permissions=("ai.audit",),
        repository_module="web.api / docs.openapi",
        tools=("get_api_status",),
        sensitive=False,
        notes="Catalogo integrazioni e API: utile per superadmin e audit, non per esporre segreti o token.",
    ),
    _src(
        "integrazioni_native",
        "Integrazioni native",
        "integrazione",
        "operativo",
        tenant_keys=("CONFIG_STUDIO_DB", "CALENDAR_SYNC_DB", "STUDIO_CONFIG"),
        permissions=("ai.usa",),
        repository_module="config_studio, calendar_sync, mailbox providers",
        tools=("get_integrations_status",),
        notes="Google, Microsoft, Aruba, InfoCert, Namirial, SDI e provider email devono essere censiti con stato configurazione.",
    ),
    _src(
        "legal_intelligence",
        "Legal intelligence",
        "legal_intelligence",
        "fonti_pubbliche",
        tenant_keys=("LEGAL_INTELLIGENCE_DB", "NORMATIVE_TABLES_DB"),
        permissions=(),
        repository_module="pct.legal_intelligence.GestioneLegalIntelligence",
        api_surface="web.helpers.get_legal_intelligence",
        tools=("get_legal_intelligence_items",),
        sensitive=False,
        official_public_source=True,
    ),
    _src(
        "update_intelligence",
        "Update intelligence",
        "update_intelligence",
        "fonti_pubbliche",
        tenant_keys=("LEGAL_INTELLIGENCE_DB",),
        permissions=(),
        repository_module="pct.legal_update_repository.LegalUpdateRepository",
        api_surface="web.helpers.get_legal_update_pipeline",
        tools=("get_update_intelligence_items",),
        sensitive=False,
        official_public_source=True,
    ),
    _src(
        "fonti_ufficiali",
        "Fonti ufficiali",
        "fonte_ufficiale",
        "fonti_pubbliche",
        tenant_keys=("IUSENTRA_LEGAL_SOURCES_DATA_DIR", "IUSENTRA_LEGAL_SOURCES_INDEX_DIR"),
        permissions=(),
        repository_module="lex.legal_sources",
        tools=("search_legal_sources",),
        sensitive=False,
        official_public_source=True,
    ),
    _src(
        "web_libero",
        "Web libero",
        "ricerca_web",
        "fonti_pubbliche",
        tenant_keys=(),
        permissions=(),
        repository_module="lex.retrieval.official_web.search_free_public_web",
        tools=("search_free_public_web",),
        internal=False,
        sensitive=False,
        notes="Ricerca pubblica libera non vincolata alle fonti ufficiali: nessuna allowlist, nessun salvataggio nel corpus, controllo rimesso all'avvocato.",
    ),
    _src(
        "audit",
        "Registro attivita'",
        "audit",
        "governance",
        tenant_keys=("AUDIT_DB",),
        permissions=("ai.audit",),
        repository_module="pct.auth.GestioneUtenti",
        api_surface="web.helpers.get_utenti",
        tools=("get_audit_events",),
    ),
)


class OperationalSourceRegistry:
    def __init__(self, sources: tuple[OperationalSourceDefinition, ...] | None = None) -> None:
        self._sources = {source.source_id: source for source in (sources or DEFAULT_SOURCE_DEFINITIONS)}

    def all(self) -> list[OperationalSourceDefinition]:
        return list(self._sources.values())

    def get(self, source_id: str) -> OperationalSourceDefinition | None:
        return self._sources.get(str(source_id or "").strip())

    def by_category(self, category: str) -> list[OperationalSourceDefinition]:
        key = str(category or "").strip()
        return [source for source in self.all() if source.category == key]

    def enabled(self) -> list[OperationalSourceDefinition]:
        return [source for source in self.all() if source.enabled_by_default]

    def to_report(self) -> list[dict[str, object]]:
        return [source.to_dict() for source in self.all()]


def build_default_registry() -> OperationalSourceRegistry:
    return OperationalSourceRegistry()
