<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://schemi.processotelematico.giustizia.it/siecic/concorsuali/introduttivi/v5"
           xmlns:pt="http://schemi.processotelematico.giustizia.it/tipi/atti/v5"
           xmlns:bt="http://schemi.processotelematico.giustizia.it/tipi"
           xmlns:at="http://schemi.processotelematico.giustizia.it/tipi/anagrafiche/v3"
           xmlns:st="http://schemi.processotelematico.giustizia.it/siecic/tipibase/v3"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:ns="http://schemi.processotelematico.giustizia.it/siecic/concorsuali/introduttivi/v5"
           targetNamespace="http://schemi.processotelematico.giustizia.it/siecic/concorsuali/introduttivi/v5"
           elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.1">
    <xs:import namespace="http://schemi.processotelematico.giustizia.it/tipi/atti/v5" schemaLocation="../base_v5/tipi-atti.xsd"/>
    <xs:import namespace="http://schemi.processotelematico.giustizia.it/tipi" schemaLocation="../tipi-base.xsd"/>
    <xs:import namespace="http://schemi.processotelematico.giustizia.it/siecic/tipibase/v3" schemaLocation="../base_v3/tipi-base-siecic.xsd"/>
    <xs:import namespace="http://schemi.processotelematico.giustizia.it/tipi/anagrafiche/v3" schemaLocation="../base_v3/tipi-anagrafiche.xsd"/>
    <xs:annotation>
        <xs:documentation>ATTI DI PARTE INTRODUTTIVI</xs:documentation>
        <xs:documentation>Gli atti qui definiti iscrivono una nuova causa al ruolo per citazione o ricorso
        </xs:documentation>
    </xs:annotation>
    <xs:simpleType name="TipoConcordatoCCIPU">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Ordinario"/>
            <xs:enumeration value="Bianco"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TipoConcordatoOrdinario">
        <xs:restriction base="xs:string">
            <xs:enumeration value="A"/>
            <xs:enumeration value="B"/>
            <xs:enumeration value="AB"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="IscrizioneRuoloPrefallimentare">
        <xs:annotation>
            <xs:documentation>Istanza di fallimento</xs:documentation>
        </xs:annotation>
        <xs:complexType mixed="false">
            <xs:complexContent mixed="false">
                <xs:extension base="pt:AttoIntroduttivo">
                    <xs:sequence>
                        <xs:element ref="pt:AnagraficaProcedimento">
                            <xs:annotation>
                                <xs:appinfo source="http://www.giustizia.it/gl/sgr"/>
                            </xs:annotation>
                        </xs:element>
                        <xs:element name="EstensioneAnagrafica" minOccurs="0">
                            <xs:annotation>
                                <xs:documentation>Informazioni aggiuntive sull'anagrafica delle parti</xs:documentation>
                                <xs:appinfo source="http://www.giustizia.it/gl/sgr"/>
                            </xs:annotation>
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="DatiDebitore">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="formaSocietaria" type="st:FormaSocietaria"/>
                                            </xs:sequence>
                                            <xs:attribute name="ref" type="xs:NMTOKEN" use="required"/>
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:element name="DatiCreditore" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="tipologiaCreditore" type="st:TipologiaCreditore">
                                                    <xs:annotation>
                                                        <xs:documentation>Tipologia applicativa del creditore
                                                            (gerarchia)
                                                        </xs:documentation>
                                                    </xs:annotation>
                                                </xs:element>
                                            </xs:sequence>
                                            <xs:attribute name="ref" type="xs:NMTOKEN" use="required"/>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
        <xs:key name="AK_PARTE">
            <xs:selector xpath="pt:AnagraficaProcedimento/pt:Partecipanti/pt:Parte"/>
            <xs:field xpath="@ID"/>
        </xs:key>
        <xs:key name="AK_CONTROPARTE">
            <xs:selector xpath="pt:AnagraficaProcedimento/pt:Partecipanti/pt:ControParte"/>
            <xs:field xpath="@ID"/>
        </xs:key>
        <xs:keyref name="FK_DEBITORE_CONTROPARTE" refer="AK_CONTROPARTE">
            <xs:selector xpath="ns:EstensioneAnagrafica/ns:DatiDebitore"/>
            <xs:field xpath="@ref"/>
        </xs:keyref>
        <xs:keyref name="FK_CREDITORE_PARTE" refer="AK_PARTE">
            <xs:selector xpath="ns:EstensioneAnagrafica/ns:DatiCreditore"/>
            <xs:field xpath="@ref"/>
        </xs:keyref>
    </xs:element>
    <xs:element name="IscrizioneRuoloNuovoConcordato">
        <xs:annotation>
            <xs:documentation>Ricorso al Nuovo Concordato Preventivo</xs:documentation>
        </xs:annotation>
        <xs:complexType mixed="false">
            <xs:complexContent mixed="false">
                <xs:extension base="pt:AttoIntroduttivo">
                    <xs:sequence>
                        <xs:element ref="pt:AnagraficaProcedimento">
                            <xs:annotation>
                                <xs:appinfo source="http://www.giustizia.it/gl/sgr"/>
                            </xs:annotation>
                        </xs:element>
                        <xs:element name="EstensioneAnagrafica" minOccurs="0">
                            <xs:annotation>
                                <xs:documentation>Informazioni aggiuntive sull'anagrafica delle parti</xs:documentation>
                                <xs:appinfo source="http://www.giustizia.it/gl/sgr"/>
                            </xs:annotation>
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="DatiDebitore">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="formaSocietaria" type="st:FormaSocietaria"/>
                                            </xs:sequence>
                                            <xs:attribute name="ref" type="xs:NMTOKEN" use="required"/>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="TipoConcordato">
                            <xs:complexType>
                                <xs:choice>
                                    <xs:element name="prenotativo" type="xs:boolean"/>
                                    <xs:element name="ordinario">
                                        <xs:complexType>
                                            <xs:simpleContent>
                                                <xs:extension base="TipoConcordatoOrdinario">
                                                    <xs:attribute name="DivisioneCrediti" type="xs:boolean"
                                                                  use="required"/>
                                                    <xs:attribute name="TransazioneExArt182Ter" type="xs:boolean"
                                                                  use="required"/>
                                                    <xs:attribute name="Relazione1602c" type="xs:boolean"
                                                                  use="required"/>
                                                </xs:extension>
                                            </xs:simpleContent>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:choice>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
        <xs:key name="AK_PARTE_NUCP">
            <xs:selector xpath="pt:AnagraficaProcedimento/pt:Partecipanti/pt:Parte"/>
            <xs:field xpath="@ID"/>
        </xs:key>
        <xs:keyref name="FK_DEBITORE_PARTE_NUCP" refer="AK_PARTE_NUCP">
            <xs:selector xpath="ns:EstensioneAnagrafica/ns:DatiDebitore"/>
            <xs:field xpath="@ref"/>
        </xs:keyref>
    </xs:element>
    <xs:element name="RicorsoLiquidazioneGiudizialeCCIPU">
        <xs:annotation>
            <xs:documentation>Deposito ricorso per liquidazione giudiziale CCIPU - atto non depositabile prima
                dell'entrata in vigore della riforma della crisi d'impresa
            </xs:documentation>
        </xs:annotation>
        <xs:complexType mixed="false">
            <xs:complexContent mixed="false">
                <xs:extension base="pt:AttoIntroduttivoPU">
                    <xs:sequence>
                        <xs:element ref="pt:AnagraficaProcedimentoPU">
                            <xs:annotation>
                                <xs:appinfo source="http://www.giustizia.it/gl/sgr"/>
                            </xs:annotation>
                        </xs:element>
                        <xs:element name="EstensioneAnagrafica" minOccurs="0">
                            <xs:annotation>
                                <xs:documentation>Informazioni aggiuntive sull'anagrafica delle parti</xs:documentation>
                                <xs:appinfo source="http://www.giustizia.it/gl/sgr"/>
                            </xs:annotation>
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="DatiDebitore" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="formaSocietaria" type="st:FormaSocietaria"/>
                                            </xs:sequence>
                                            <xs:attribute name="ref" type="xs:NMTOKEN" use="required"/>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="misureCautelari" type="xs:boolean"/>
                        <xs:element name="misureProtettive" type="xs:boolean"/>
                        <xs:element name="gruppoImprese" type="xs:boolean"/>
                        <xs:element name="TipoParteIstante">
                            <xs:complexType>
                                <xs:choice>
                                    <xs:element name="AutoritaVigilanza">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="denominazione"/>
                                                <xs:element name="codiceFiscale"/>
                                                <xs:element name="indirizzo" type="at:Indirizzo">
                                                    <xs:annotation>
                                                        <xs:appinfo source="http://www.giustizia.it/gl/sgr"/>
                                                    </xs:annotation>
                                                </xs:element>
                                                <xs:element name="fax" minOccurs="0"/>
                                                <xs:element name="pec" minOccurs="0"/>
                                                <xs:element name="avvocato" type="at:Avvocato" minOccurs="0"
                                                            maxOccurs="unbounded">
                                                    <xs:annotation>
                                                        <xs:appinfo source="http://www.giustizia.it/gl/sgr"/>
                                                    </xs:annotation>
                                                </xs:element>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:element name="Creditore" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="creditore" type="at:Parte">
                                                    <xs:annotation>
                                                        <xs:documentation>AnagraficaProcedimento - DatiCreditore
                                                        </xs:documentation>
                                                    </xs:annotation>
                                                </xs:element>
                                                <xs:element name="avvocato" type="at:Avvocato" minOccurs="0"
                                                            maxOccurs="unbounded">
                                                    <xs:annotation>
                                                        <xs:appinfo source="http://www.giustizia.it/gl/sgr"/>
                                                    </xs:annotation>
                                                </xs:element>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:element name="Curatore">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="curatore" type="at:Curatore">
                                                    <xs:annotation>
                                                        <xs:appinfo source="http://www.giustizia.it/gl/sgr"/>
                                                    </xs:annotation>
                                                </xs:element>
                                                <xs:element name="cfImpresaFallita"/>
                                                <xs:element name="denomImpresaFallita" minOccurs="0"/>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:element name="Debitore">
                                        <xs:annotation>
                                            <xs:documentation>AnagraficaProcedimento - DatiDebitore</xs:documentation>
                                        </xs:annotation>
                                    </xs:element>
                                    <xs:element name="OrganismoControllo">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="denominazione"/>
                                                <xs:element name="nome" minOccurs="0"/>
                                                <xs:element name="codiceFiscale"/>
                                                <xs:element name="luogoNascita" minOccurs="0"/>
                                                <xs:element name="dataNascita" type="xs:date" minOccurs="0"/>
                                                <xs:element name="tipologia"/>
                                                <xs:element name="indirizzo" type="at:Indirizzo">
                                                    <xs:annotation>
                                                        <xs:appinfo source="http://www.giustizia.it/gl/sgr"/>
                                                    </xs:annotation>
                                                </xs:element>
                                                <xs:element name="fax" minOccurs="0"/>
                                                <xs:element name="pec" minOccurs="0"/>
                                                <xs:element name="avvocato" type="at:Avvocato" minOccurs="0"
                                                            maxOccurs="unbounded">
                                                    <xs:annotation>
                                                        <xs:appinfo source="http://www.giustizia.it/gl/sgr"/>
                                                    </xs:annotation>
                                                </xs:element>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:element name="Socio">
                                        <xs:complexType>
                                            <xs:choice>
                                                <xs:element name="personaFisica">
                                                    <xs:complexType>
                                                        <xs:sequence>
                                                            <xs:element name="cognome"/>
                                                            <xs:element name="nome"/>
                                                            <xs:element name="codiceFiscale"/>
                                                            <xs:element name="luogoNascita" minOccurs="0"/>
                                                            <xs:element name="dataNascita" minOccurs="0"/>
                                                            <xs:element name="costituitoPersonalmente" type="xs:boolean"
                                                                        minOccurs="0"/>
                                                            <xs:element name="indirizzo" type="at:Indirizzo">
                                                                <xs:annotation>
                                                                    <xs:appinfo
                                                                            source="http://www.giustizia.it/gl/sgr"/>
                                                                </xs:annotation>
                                                            </xs:element>
                                                            <xs:element name="fax" minOccurs="0"/>
                                                            <xs:element name="pec" minOccurs="0"/>
                                                        </xs:sequence>
                                                    </xs:complexType>
                                                </xs:element>
                                                <xs:element name="personaGiuridica">
                                                    <xs:complexType>
                                                        <xs:sequence>
                                                            <xs:element name="denominazione"/>
                                                            <xs:element name="ragioneSociale"/>
                                                            <xs:element name="codiceFiscale"/>
                                                            <xs:element name="partitaIva"/>
                                                            <xs:element name="costituitoPersonalmente" type="xs:boolean"
                                                                        minOccurs="0"/>
                                                            <xs:element name="indirizzo" type="at:Indirizzo">
                                                                <xs:annotation>
                                                                    <xs:appinfo
                                                                            source="http://www.giustizia.it/gl/sgr"/>
                                                                </xs:annotation>
                                                            </xs:element>
                                                            <xs:element name="fax" minOccurs="0"/>
                                                            <xs:element name="pec" minOccurs="0"/>
                                                        </xs:sequence>
                                                    </xs:complexType>
                                                </xs:element>
                                            </xs:choice>
                                            <xs:attribute name="codiceFiscaleDebitore" type="bt:CodiceFiscale"
                                                          use="required"/>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:choice>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="RicorsoFissazioneTerminePropostaOAccordiCCIPU">
        <xs:annotation>
            <xs:documentation>Deposito ricorso fissazione termine per deposito proposta cp o accordi CCIPU
            </xs:documentation>
        </xs:annotation>
        <xs:complexType mixed="false">
            <xs:complexContent mixed="false">
                <xs:extension base="pt:AttoIntroduttivoPU">
                    <xs:sequence>
                        <xs:element ref="pt:AnagraficaProcedimentoPU">
                            <xs:annotation>
                                <xs:appinfo source="http://www.giustizia.it/gl/sgr"/>
                            </xs:annotation>
                        </xs:element>
                        <xs:element name="EstensioneAnagrafica" minOccurs="0">
                            <xs:annotation>
                                <xs:documentation>Informazioni aggiuntive sull'anagrafica delle parti</xs:documentation>
                                <xs:appinfo source="http://www.giustizia.it/gl/sgr"/>
                            </xs:annotation>
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="DatiDebitore" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="formaSocietaria" type="st:FormaSocietaria"/>
                                            </xs:sequence>
                                            <xs:attribute name="ref" type="xs:NMTOKEN" use="required"/>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="misureCautelari" type="xs:boolean"/>
                        <xs:element name="misureProtettive" type="xs:boolean"/>
                        <xs:element name="gruppoImprese" type="xs:boolean"/>
                    </xs:sequence>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="RicorsoAmmissConcordatoPreventivoCCIPU">
        <xs:annotation>
            <xs:documentation>Deposito ricorso per ammissione al concordato preventivo CCIPU - atto non depositabile
                prima dell'entrata in vigore della riforma della crisi d'impresa
            </xs:documentation>
        </xs:annotation>
        <xs:complexType mixed="false">
            <xs:complexContent mixed="false">
                <xs:extension base="pt:AttoIntroduttivoPU">
                    <xs:sequence>
                        <xs:element ref="pt:AnagraficaProcedimentoPU">
                            <xs:annotation>
                                <xs:appinfo source="http://www.giustizia.it/gl/sgr"/>
                            </xs:annotation>
                        </xs:element>
                        <xs:element name="EstensioneAnagrafica" minOccurs="0">
                            <xs:annotation>
                                <xs:documentation>Informazioni aggiuntive sull'anagrafica delle parti</xs:documentation>
                                <xs:appinfo source="http://www.giustizia.it/gl/sgr"/>
                            </xs:annotation>
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="DatiDebitore" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="formaSocietaria" type="st:FormaSocietaria"/>
                                            </xs:sequence>
                                            <xs:attribute name="ref" type="xs:NMTOKEN" use="required"/>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="misureCautelari" type="xs:boolean"/>
                        <xs:element name="misureProtettive" type="xs:boolean"/>
                        <xs:element name="gruppoImprese" type="xs:boolean"/>
                        <xs:element name="tipoConcordato">
                            <xs:complexType>
                                <xs:simpleContent>
                                    <xs:extension base="TipoConcordatoCCIPU"/>
                                </xs:simpleContent>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="RicorsoOmologaAccordiRistrutturazCCIPU">
        <xs:annotation>
            <xs:documentation>Ricorso omologazione accordi di ristrutturazione CCIPU - atto non depositabile prima
                dell'entrata in vigore della riforma della crisi d'impresa
            </xs:documentation>
        </xs:annotation>
        <xs:complexType mixed="false">
            <xs:complexContent mixed="false">
                <xs:extension base="pt:AttoIntroduttivoPU">
                    <xs:sequence>
                        <xs:element ref="pt:AnagraficaProcedimentoPU">
                            <xs:annotation>
                                <xs:appinfo source="http://www.giustizia.it/gl/sgr"/>
                            </xs:annotation>
                        </xs:element>
                        <xs:element name="EstensioneAnagrafica" minOccurs="0">
                            <xs:annotation>
                                <xs:documentation>Informazioni aggiuntive sull'anagrafica delle parti</xs:documentation>
                                <xs:appinfo source="http://www.giustizia.it/gl/sgr"/>
                            </xs:annotation>
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="DatiDebitore" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="formaSocietaria" type="st:FormaSocietaria"/>
                                            </xs:sequence>
                                            <xs:attribute name="ref" type="xs:NMTOKEN" use="required"/>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="misureCautelari" type="xs:boolean"/>
                        <xs:element name="misureProtettive" type="xs:boolean"/>
                        <xs:element name="gruppoImprese" type="xs:boolean"/>
                        <xs:element name="tipoConcordato">
                            <xs:complexType>
                                <xs:simpleContent>
                                    <xs:extension base="TipoConcordatoCCIPU"/>
                                </xs:simpleContent>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="RicorsoLiquidazioneControllataCCIPU">
        <xs:annotation>
            <xs:documentation>Deposito ricorso liquidazione controllata - atto non depositabile prima dell'entrata in
                vigore della riforma della crisi d'impresa
            </xs:documentation>
        </xs:annotation>
        <xs:complexType mixed="false">
            <xs:complexContent mixed="false">
                <xs:extension base="pt:AttoIntroduttivoPU">
                    <xs:sequence>
                        <xs:element ref="pt:AnagraficaProcedimentoPU">
                            <xs:annotation>
                                <xs:appinfo source="http://www.giustizia.it/gl/sgr"/>
                            </xs:annotation>
                        </xs:element>
                        <xs:element name="EstensioneAnagrafica" minOccurs="0">
                            <xs:annotation>
                                <xs:documentation>Informazioni aggiuntive sull'anagrafica delle parti</xs:documentation>
                                <xs:appinfo source="http://www.giustizia.it/gl/sgr"/>
                            </xs:annotation>
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="DatiDebitore" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="formaSocietaria" type="st:FormaSocietaria"/>
                                            </xs:sequence>
                                            <xs:attribute name="ref" type="xs:NMTOKEN" use="required"/>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="misureCautelari" type="xs:boolean"/>
                        <xs:element name="misureProtettive" type="xs:boolean"/>
                        <xs:element name="gruppoImprese" type="xs:boolean"/>
                        <xs:element name="TipoParteIstante">
                            <xs:complexType>
                                <xs:choice>
                                    <xs:element name="Creditore" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="creditore" type="at:Parte">
                                                    <xs:annotation>
                                                        <xs:documentation>AnagraficaProcedimento - DatiCreditore
                                                        </xs:documentation>
                                                    </xs:annotation>
                                                </xs:element>
                                                <xs:element name="avvocato" type="at:Avvocato" minOccurs="0"
                                                            maxOccurs="unbounded">
                                                    <xs:annotation>
                                                        <xs:appinfo source="http://www.giustizia.it/gl/sgr"/>
                                                    </xs:annotation>
                                                </xs:element>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:element name="Debitore">
                                        <xs:annotation>
                                            <xs:documentation>AnagraficaProcedimento - DatiDebitore</xs:documentation>
                                        </xs:annotation>
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="TipoOrgano">
                                                    <xs:complexType>
                                                        <xs:choice>
                                                            <xs:element name="OCC">
                                                                <xs:complexType>
                                                                    <xs:complexContent>
                                                                        <xs:extension base="at:Parte">
                                                                            <xs:sequence>
                                                                                <xs:element name="partitaIVA"
                                                                                            type="xs:string"
                                                                                            minOccurs="0"/>
                                                                                <xs:element name="Referente">
                                                                                    <xs:complexType>
                                                                                        <xs:complexContent>
                                                                                            <xs:extension
                                                                                                    base="at:Parte">
                                                                                                <xs:attribute
                                                                                                        name="qualifica"
                                                                                                        use="required">
                                                                                                    <xs:simpleType>
                                                                                                        <xs:restriction
                                                                                                                base="xs:normalizedString">
                                                                                                            <xs:enumeration
                                                                                                                    value="Avvocato"/>
                                                                                                            <xs:enumeration
                                                                                                                    value="Commercialista"/>
                                                                                                            <xs:enumeration
                                                                                                                    value="Consulente del lavoro"/>
                                                                                                        </xs:restriction>
                                                                                                    </xs:simpleType>
                                                                                                </xs:attribute>
                                                                                            </xs:extension>
                                                                                        </xs:complexContent>
                                                                                    </xs:complexType>
                                                                                </xs:element>
                                                                            </xs:sequence>
                                                                        </xs:extension>
                                                                    </xs:complexContent>
                                                                </xs:complexType>
                                                            </xs:element>
                                                            <xs:element name="GestoreCrisi" type="at:Parte"/>
                                                        </xs:choice>
                                                    </xs:complexType>
                                                </xs:element>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:choice>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="RicorsoDichiarazioneInsolvenzaCCIPU">
        <xs:annotation>
            <xs:documentation>Deposito ricorso per dichiarazione stato di insolvenza CCIPU - atto non depositabile prima
                dell'entrata in vigore della riforma della crisi d'impresa
            </xs:documentation>
        </xs:annotation>
        <xs:complexType mixed="false">
            <xs:complexContent mixed="false">
                <xs:extension base="pt:AttoIntroduttivoPU">
                    <xs:sequence>
                        <xs:element ref="pt:AnagraficaProcedimentoPU">
                            <xs:annotation>
                                <xs:appinfo source="http://www.giustizia.it/gl/sgr"/>
                            </xs:annotation>
                        </xs:element>
                        <xs:element name="EstensioneAnagrafica" minOccurs="0">
                            <xs:annotation>
                                <xs:documentation>Informazioni aggiuntive sull'anagrafica delle parti</xs:documentation>
                                <xs:appinfo source="http://www.giustizia.it/gl/sgr"/>
                            </xs:annotation>
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="DatiDebitore" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="formaSocietaria" type="st:FormaSocietaria"/>
                                            </xs:sequence>
                                            <xs:attribute name="ref" type="xs:NMTOKEN" use="required"/>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="misureCautelari" type="xs:boolean"/>
                        <xs:element name="misureProtettive" type="xs:boolean"/>
                        <xs:element name="gruppoImprese" type="xs:boolean"/>
                        <xs:element name="TipoParteIstante">
                            <xs:complexType>
                                <xs:choice>
                                    <xs:element name="AutoritaVigilanza">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="denominazione" type="xs:string"/>
                                                <xs:element name="codiceFiscale" type="xs:string"/>
                                                <xs:element name="indirizzo" type="at:Indirizzo">
                                                    <xs:annotation>
                                                        <xs:appinfo source="http://www.giustizia.it/gl/sgr"/>
                                                    </xs:annotation>
                                                </xs:element>
                                                <xs:element name="fax" type="xs:string" minOccurs="0"/>
                                                <xs:element name="pec" type="xs:string" minOccurs="0"/>
                                                <xs:element name="avvocato" type="at:Avvocato" minOccurs="0"
                                                            maxOccurs="unbounded">
                                                    <xs:annotation>
                                                        <xs:appinfo source="http://www.giustizia.it/gl/sgr"/>
                                                    </xs:annotation>
                                                </xs:element>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:element name="Creditore" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="creditore" type="at:Parte">
                                                    <xs:annotation>
                                                        <xs:documentation>AnagraficaProcedimento - DatiCreditore
                                                        </xs:documentation>
                                                    </xs:annotation>
                                                </xs:element>
                                                <xs:element name="avvocato" type="at:Avvocato" minOccurs="0"
                                                            maxOccurs="unbounded">
                                                    <xs:annotation>
                                                        <xs:appinfo source="http://www.giustizia.it/gl/sgr"/>
                                                    </xs:annotation>
                                                </xs:element>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:element name="Debitore">
                                        <xs:annotation>
                                            <xs:documentation>AnagraficaProcedimento - DatiDebitore</xs:documentation>
                                        </xs:annotation>
                                    </xs:element>
                                </xs:choice>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="RicorsoConcordatoMinoreCCIPU">
        <xs:annotation>
            <xs:documentation>Deposito ricorso per concordato minore CCIPU - atto non depositabile prima dell'entrata in
                vigore della riforma della crisi d'impresa
            </xs:documentation>
        </xs:annotation>
        <xs:complexType mixed="false">
            <xs:complexContent mixed="false">
                <xs:extension base="pt:AttoIntroduttivoPU">
                    <xs:sequence>
                        <xs:element ref="pt:AnagraficaProcedimentoPU">
                            <xs:annotation>
                                <xs:appinfo source="http://www.giustizia.it/gl/sgr"/>
                            </xs:annotation>
                        </xs:element>
                        <xs:element name="EstensioneAnagrafica" minOccurs="0">
                            <xs:annotation>
                                <xs:documentation>Informazioni aggiuntive sull'anagrafica delle parti</xs:documentation>
                                <xs:appinfo source="http://www.giustizia.it/gl/sgr"/>
                            </xs:annotation>
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="DatiDebitore" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="formaSocietaria" type="st:FormaSocietaria"/>
                                            </xs:sequence>
                                            <xs:attribute name="ref" type="xs:NMTOKEN" use="required"/>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="misureCautelari" type="xs:boolean"/>
                        <xs:element name="misureProtettive" type="xs:boolean"/>
                        <xs:element name="gruppoImprese" type="xs:boolean"/>
                        <xs:element name="TipoOrgano">
                            <xs:complexType>
                                <xs:choice>
                                    <xs:element name="OCC">
                                        <xs:complexType>
                                            <xs:complexContent>
                                                <xs:extension base="at:Parte">
                                                    <xs:sequence>
                                                        <xs:element name="partitaIVA" type="xs:string" minOccurs="0"/>
                                                        <xs:element name="Referente">
                                                            <xs:complexType>
                                                                <xs:complexContent>
                                                                    <xs:extension base="at:Parte">
                                                                        <xs:attribute name="qualifica" use="required">
                                                                            <xs:simpleType>
                                                                                <xs:restriction
                                                                                        base="xs:normalizedString">
                                                                                    <xs:enumeration value="Avvocato"/>
                                                                                    <xs:enumeration
                                                                                            value="Commercialista"/>
                                                                                    <xs:enumeration
                                                                                            value="Consulente del lavoro"/>
                                                                                </xs:restriction>
                                                                            </xs:simpleType>
                                                                        </xs:attribute>
                                                                    </xs:extension>
                                                                </xs:complexContent>
                                                            </xs:complexType>
                                                        </xs:element>
                                                    </xs:sequence>
                                                </xs:extension>
                                            </xs:complexContent>
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:element name="GestoreCrisi" type="at:Parte"/>
                                </xs:choice>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="RicorsoRistruttDebitiConsumatoreCCIPU">
        <xs:annotation>
            <xs:documentation>Deposito ricorso ristrutturazione debiti consumatore CCIPU - atto non depositabile prima
                dell'entrata in vigore della riforma della crisi d'impresa
            </xs:documentation>
        </xs:annotation>
        <xs:complexType mixed="false">
            <xs:complexContent mixed="false">
                <xs:extension base="pt:AttoIntroduttivoPU">
                    <xs:sequence>
                        <xs:element ref="pt:AnagraficaProcedimentoPU">
                            <xs:annotation>
                                <xs:appinfo source="http://www.giustizia.it/gl/sgr"/>
                            </xs:annotation>
                        </xs:element>
                        <xs:element name="EstensioneAnagrafica" minOccurs="0">
                            <xs:annotation>
                                <xs:documentation>Informazioni aggiuntive sull'anagrafica delle parti</xs:documentation>
                                <xs:appinfo source="http://www.giustizia.it/gl/sgr"/>
                            </xs:annotation>
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="DatiDebitore" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="formaSocietaria" type="st:FormaSocietaria"/>
                                            </xs:sequence>
                                            <xs:attribute name="ref" type="xs:NMTOKEN" use="required"/>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="misureCautelari" type="xs:boolean"/>
                        <xs:element name="misureProtettive" type="xs:boolean"/>
                        <xs:element name="gruppoImpresa" type="xs:boolean"/>
                        <xs:element name="TipoOrgano">
                            <xs:complexType>
                                <xs:choice>
                                    <xs:element name="OCC">
                                        <xs:complexType>
                                            <xs:complexContent>
                                                <xs:extension base="at:Parte">
                                                    <xs:sequence>
                                                        <xs:element name="partitaIVA" type="xs:string" minOccurs="0"/>
                                                        <xs:element name="Referente">
                                                            <xs:complexType>
                                                                <xs:complexContent>
                                                                    <xs:extension base="at:Parte">
                                                                        <xs:attribute name="qualifica" use="required">
                                                                            <xs:simpleType>
                                                                                <xs:restriction
                                                                                        base="xs:normalizedString">
                                                                                    <xs:enumeration value="Avvocato"/>
                                                                                    <xs:enumeration
                                                                                            value="Commercialista"/>
                                                                                    <xs:enumeration
                                                                                            value="Consulente del lavoro"/>
                                                                                </xs:restriction>
                                                                            </xs:simpleType>
                                                                        </xs:attribute>
                                                                    </xs:extension>
                                                                </xs:complexContent>
                                                            </xs:complexType>
                                                        </xs:element>
                                                    </xs:sequence>
                                                </xs:extension>
                                            </xs:complexContent>
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:element name="GestoreCrisi" type="at:Parte"/>
                                </xs:choice>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="IscrizioneRuoloConcordatoSemplificato">
        <xs:annotation>
            <xs:documentation>Ricorso al Concordato Semplificato</xs:documentation>
        </xs:annotation>
        <xs:complexType mixed="false">
            <xs:complexContent mixed="false">
                <xs:extension base="pt:AttoIntroduttivo">
                    <xs:sequence>
                        <xs:element ref="pt:AnagraficaProcedimento">
                            <xs:annotation>
                                <xs:appinfo source="http://www.giustizia.it/gl/sgr"/>
                            </xs:annotation>
                        </xs:element>
                        <xs:element name="EstensioneAnagrafica" minOccurs="0">
                            <xs:annotation>
                                <xs:documentation>Informazioni aggiuntive sull'anagrafica delle parti</xs:documentation>
                                <xs:appinfo source="http://www.giustizia.it/gl/sgr"/>
                            </xs:annotation>
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="DatiDebitore">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="formaSocietaria" type="st:FormaSocietaria"/>
                                            </xs:sequence>
                                            <xs:attribute name="ref" type="xs:NMTOKEN" use="required"/>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
        <xs:key name="AK_PARTE_CS">
            <xs:selector xpath="pt:AnagraficaProcedimento/pt:Partecipanti/pt:Parte"/>
            <xs:field xpath="@ID"/>
        </xs:key>
        <xs:keyref name="FK_DEBITORE_PARTE_CS" refer="AK_PARTE_CS">
            <xs:selector xpath="ns:EstensioneAnagrafica/ns:DatiDebitore"/>
            <xs:field xpath="@ref"/>
        </xs:keyref>
    </xs:element>
    <xs:element name="RicorsoEDI">
        <xs:annotation>
            <xs:documentation>Ricorso per rito EDI</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="pt:AttoIntroduttivo">
                    <xs:sequence>
                        <xs:element ref="pt:AnagraficaProcedimento"/>
                        <xs:element name="OCC">
                            <xs:complexType>
                                <xs:complexContent>
                                    <xs:extension base="at:Parte">
                                        <xs:sequence>
                                            <xs:element name="partitaIVA" type="xs:string" minOccurs="0"/>
                                            <xs:element name="Referente">
                                                <xs:complexType>
                                                    <xs:complexContent>
                                                        <xs:extension base="at:Parte">
                                                            <xs:attribute name="qualifica" use="required">
                                                                <xs:simpleType>
                                                                    <xs:restriction base="xs:normalizedString">
                                                                        <xs:enumeration value="Avvocato"/>
                                                                        <xs:enumeration value="Commercialista"/>
                                                                        <xs:enumeration value="Consulente del lavoro"/>
                                                                    </xs:restriction>
                                                                </xs:simpleType>
                                                            </xs:attribute>
                                                        </xs:extension>
                                                    </xs:complexContent>
                                                </xs:complexType>
                                            </xs:element>
                                        </xs:sequence>
                                    </xs:extension>
                                </xs:complexContent>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
</xs:schema>
