<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://schemi.processotelematico.giustizia.it/sicid/professionista/v1"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:evt="http://schemi.processotelematico.giustizia.it/eventi/professionista"
           xmlns:pt="http://schemi.processotelematico.giustizia.it/tipi/atti/v4"
           targetNamespace="http://schemi.processotelematico.giustizia.it/sicid/professionista/v1"
           elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.3">
    <xs:import namespace="http://schemi.processotelematico.giustizia.it/tipi/atti/v4"
               schemaLocation="../base_v4/tipi-atti.xsd"/>
    <xs:import namespace="http://schemi.processotelematico.giustizia.it/eventi/professionista"
               schemaLocation="../eventi-professionista.xsd"/>
    <xs:element name="DepositoSemplice">
        <xs:annotation>
            <xs:documentation>Deposito Atto semplice</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="pt:AttoProcedimento">
                    <xs:sequence>
                        <xs:element name="deposito">
                            <xs:annotation>
                                <xs:documentation>Specifica la tipologia di atto oggetto di deposito</xs:documentation>
                            </xs:annotation>
                            <xs:complexType>
                                <xs:choice>
                                    <xs:element ref="evt:depositoPerizia"/>
                                    <xs:element ref="evt:istanzaGenericaCTU"/>
                                    <xs:element ref="evt:istanzaLiquidazioneCTU"/>
                                    <xs:element ref="evt:integrazionePerizia"/>
                                    <xs:element ref="evt:richiestaProrogaTerminiPerizia"/>
                                    <xs:element ref="evt:AttoNonCodificato"/>
                                    <xs:element ref="evt:DepositoGiuramentoTelematico"/>
                                </xs:choice>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
</xs:schema>
