import {
  BarChart3,
  Bot,
  BriefcaseBusiness,
  Building2,
  CalendarDays,
  FileText,
  FolderOpen,
  Gavel,
  Home,
  Landmark,
  ReceiptText,
  Search,
  Settings,
  ShieldCheck,
} from "lucide-react";

export const navigation = [
  { label: "Panoramica", href: "/dashboard", icon: Home },
  { label: "Regia Operativa", href: "/dashboard?focus=regia", icon: Bot },
  { label: "Ricerca Studio", href: "/dashboard?focus=ricerca", icon: Search },
  { label: "Fascicoli", href: "/fascicoli", icon: FolderOpen },
  { label: "Agenda", href: "/dashboard?focus=agenda", icon: CalendarDays },
  { label: "Clienti e Anagrafiche", href: "/dashboard?focus=clienti", icon: BriefcaseBusiness },
  { label: "Redazione Atti", href: "/redazione-atti", icon: FileText },
  { label: "Servizi Telematici", href: "/telematico", icon: Landmark },
  { label: "Compensi e Parcelle", href: "/economia", icon: ReceiptText },
  { label: "Ricerca Legale", href: "/dashboard?focus=legal", icon: Gavel },
  { label: "Statistiche", href: "/dashboard?focus=statistiche", icon: BarChart3 },
  { label: "Piattaforma", href: "/admin", icon: Building2 },
  { label: "Conformità", href: "/telematico?focus=conformita", icon: ShieldCheck },
  { label: "Impostazioni", href: "/admin?focus=impostazioni", icon: Settings },
];
