import {
  AtSign,
  Bell,
  Bot,
  Building2,
  CalendarSync,
  Clock3,
  CloudUpload,
  CreditCard,
  MailCheck,
  MessageCircle,
  ShieldCheck,
  type LucideIcon,
} from 'lucide-react'
import type { SettingsField, SettingsSection, SettingTone } from './types'

export const SETTINGS_SECTIONS: Array<{
  id: SettingsSection
  label: string
  description: string
  icon: LucideIcon
  tone: SettingTone
}> = [
  { id: 'studio', label: 'Dati Studio', description: 'Anagrafica, albo, recapiti e coordinate usate nei documenti.', icon: Building2, tone: 'primary' },
  { id: 'pec', label: 'PEC', description: 'Parametri certificati per invio e ricezione telematica.', icon: MailCheck, tone: 'success' },
  { id: 'firma', label: 'Firma Digitale', description: 'P12, PEM o dispositivo di firma tramite IUSENTRA Local Signer.', icon: ShieldCheck, tone: 'warning' },
  { id: 'smtp', label: 'Email SMTP', description: 'Casella ordinaria separata dalla PEC.', icon: AtSign, tone: 'info' },
  { id: 'whatsapp', label: 'WhatsApp', description: 'Canale messaggi e promemoria cliente.', icon: MessageCircle, tone: 'success' },
  { id: 'scheduler', label: 'Scheduler', description: 'Backup e automazioni periodiche dello studio.', icon: Clock3, tone: 'neutral' },
  { id: 'ai', label: 'AI Locale', description: 'Assistente sul PC dello studio e ricerca nei documenti.', icon: Bot, tone: 'primary' },
  { id: 'pagamenti', label: 'Pagamenti', description: 'Carte, PayPal, Satispay, SumUp, bonifico e link parcella.', icon: CreditCard, tone: 'info' },
  { id: 'notifiche', label: 'Notifiche', description: 'Messaggi WhatsApp, promemoria e registro dello studio.', icon: Bell, tone: 'success' },
  { id: 'backup', label: 'Backup', description: 'Copie, verifica e scaricamento protetto dei dati dello studio.', icon: CloudUpload, tone: 'warning' },
  { id: 'calendari', label: 'Calendari', description: 'Collega agenda e scadenze ai calendari usati dallo studio.', icon: CalendarSync, tone: 'primary' },
]

export const SETTINGS_FIELDS: Record<SettingsSection, SettingsField[]> = {
  studio: [
    { name: 'nome', label: 'Nome studio', required: true, width: 'half' },
    { name: 'avvocato', label: 'Avvocato titolare', width: 'half' },
    { name: 'numero_iscrizione_albo', label: 'Numero iscrizione Albo', width: 'third' },
    { name: 'ordine_avvocati', label: 'Ordine degli Avvocati', width: 'third' },
    { name: 'codice_fiscale_avvocato', label: 'C.F. Avvocato per PCT', width: 'third', placeholder: 'RSSMRA80A01H501Z' },
    { name: 'piva', label: 'Partita IVA', width: 'third' },
    { name: 'cf', label: 'Codice fiscale studio', width: 'third' },
    { name: 'telefono', label: 'Telefono', width: 'third' },
    { name: 'email', label: 'Email studio', type: 'email', width: 'third' },
    { name: 'sito_web', label: 'Sito web', type: 'url', width: 'third' },
    { name: 'indirizzo', label: 'Indirizzo', width: 'full' },
    { name: 'city', label: 'Citta', width: 'third' },
    { name: 'province', label: 'Provincia', width: 'third', placeholder: 'MI' },
    { name: 'patron_name', label: 'Santo patrono', width: 'third' },
    { name: 'patron_day', label: 'Giorno patrono', type: 'number', width: 'third', min: 0, max: 31 },
    { name: 'patron_month', label: 'Mese patrono', type: 'number', width: 'third', min: 0, max: 12 },
    { name: 'iban', label: 'IBAN', width: 'half' },
    { name: 'banca', label: 'Banca', width: 'half' },
  ],
  pec: [
    { name: 'indirizzo', label: 'Indirizzo PEC', type: 'email', required: true, width: 'half' },
    { name: 'password', label: 'Password PEC', type: 'password', width: 'half' },
    { name: 'smtp_host', label: 'Server invio PEC', required: true, width: 'half' },
    { name: 'smtp_port', label: 'Porta invio PEC', type: 'number', width: 'third', min: 1, max: 65535 },
    { name: 'imap_host', label: 'Server ricezione PEC', required: true, width: 'half' },
    { name: 'imap_port', label: 'Porta ricezione PEC', type: 'number', width: 'third', min: 1, max: 65535 },
    { name: 'use_ssl', label: 'Connessione sicura diretta', type: 'checkbox', width: 'half' },
  ],
  firma: [
    { name: 'backend_preferito', label: 'Canale firma', type: 'select', width: 'half', options: [
      { value: 'auto', label: 'Automatico' },
      { value: 'pkcs11', label: 'Dispositivo USB tramite Local Signer' },
      { value: 'p12', label: 'Certificato P12/PFX' },
      { value: 'pem', label: 'Certificato PEM' },
    ] },
    { name: 'visible_signature_mode', label: 'Posizione firma visibile', type: 'select', width: 'half', options: [
      { value: 'laterale', label: 'Laterale' },
      { value: 'basso_sinistra', label: 'In basso a sinistra' },
      { value: 'basso_destra', label: 'In basso a destra' },
    ] },
    { name: 'cf_avvocato', label: 'C.F. avvocato nel certificato', width: 'half' },
    { name: 'password', label: 'Password P12', type: 'password', width: 'half' },
    { name: 'p12_path', label: 'Percorso P12/PFX salvato', width: 'half' },
    { name: 'firma_p12_file', label: 'Carica P12/PFX', type: 'file', width: 'half', accept: '.p12,.pfx' },
    { name: 'cert_pem_path', label: 'Percorso certificato PEM', width: 'half' },
    { name: 'firma_cert_pem_file', label: 'Carica certificato PEM', type: 'file', width: 'half', accept: '.crt,.cer,.pem' },
    { name: 'key_pem_path', label: 'Percorso chiave PEM', width: 'half' },
    { name: 'firma_key_pem_file', label: 'Carica chiave PEM', type: 'file', width: 'half', accept: '.key,.pem' },
    { name: 'key_pem_password', label: 'Password chiave PEM', type: 'password', width: 'half' },
    { name: 'pkcs11_library', label: 'Percorso driver firma', width: 'half' },
    { name: 'pkcs11_slot', label: 'Slot dispositivo', width: 'third' },
    { name: 'pkcs11_label', label: 'Nome certificato', width: 'third' },
  ],
  smtp: [
    { name: 'host', label: 'Server invio email', required: true, width: 'half' },
    { name: 'port', label: 'Porta invio email', type: 'number', width: 'third', min: 1, max: 65535 },
    { name: 'username', label: 'Username', width: 'half' },
    {
      name: 'password',
      label: 'Password email',
      type: 'password',
      width: 'half',
      help: "Con Gmail inserisci la password per le app, non la password normale dell'account.",
      helpLink: { label: 'Genera password per le app Google', href: 'https://myaccount.google.com/apppasswords' },
    },
    { name: 'from_address', label: 'Mittente email', type: 'email', width: 'half' },
    { name: 'from_name', label: 'Nome mittente', width: 'half' },
    { name: 'imap_host', label: 'Server ricezione email', width: 'half' },
    { name: 'imap_port', label: 'Porta ricezione email', type: 'number', width: 'third', min: 1, max: 65535 },
    { name: 'use_tls', label: 'Connessione sicura per invio', type: 'checkbox', width: 'half' },
    { name: 'imap_use_ssl', label: 'Connessione sicura per ricezione', type: 'checkbox', width: 'half' },
  ],
  whatsapp: [
    { name: 'twilio_sid', label: 'Twilio SID', width: 'half' },
    { name: 'twilio_token', label: 'Chiave riservata Twilio', type: 'password', width: 'half' },
    { name: 'twilio_numero', label: 'Numero Twilio WhatsApp', width: 'half' },
    { name: 'callmebot_key', label: 'Chiave CallMeBot', type: 'password', width: 'half' },
  ],
  scheduler: [
    { name: 'backup_abilitato', label: 'Backup automatico attivo', type: 'checkbox', width: 'half' },
    { name: 'backup_ora', label: 'Ora backup', type: 'time', width: 'half' },
    { name: 'wa_reminder_abilitato', label: 'Promemoria WhatsApp attivi', type: 'checkbox', width: 'half' },
    { name: 'wa_reminder_ora', label: 'Ora promemoria', type: 'time', width: 'half' },
  ],
  ai: [
    { name: 'enabled', label: 'AI locale attiva', type: 'checkbox', width: 'half' },
    { name: 'auto_bootstrap', label: 'Prepara motore locale automaticamente', type: 'checkbox', width: 'half' },
    { name: 'base_url', label: 'Collegamento AI sul PC', width: 'full', help: "Lascia invariato se l'assistente gira su questo computer." },
    { name: 'chat_model', label: "Risposte dell'assistente", type: 'select', width: 'half', options: [
      { value: '__auto__', label: 'Automatico (consigliato)' },
      { value: 'gemma3:1b', label: 'Veloce' },
      { value: 'qwen2.5:0.5b', label: 'Molto leggero' },
      { value: 'mistral', label: 'Piu completo se gia installato' },
    ] },
    { name: 'embed_model', label: 'Ricerca nei documenti', type: 'select', width: 'half', options: [
      { value: '__auto__', label: 'Automatico (consigliato)' },
      { value: 'embeddinggemma:300m', label: 'Ricerca locale consigliata' },
      { value: 'nomic-embed-text', label: 'Ricerca alternativa' },
    ] },
    { name: 'keep_alive', label: "Disponibilita dopo l'uso", type: 'select', width: 'third', options: [
      { value: '10m', label: '10 minuti (consigliato)' },
      { value: '30m', label: '30 minuti' },
      { value: '1h', label: '1 ora' },
    ] },
    { name: 'auto_index_documents', label: 'Indicizza documenti automaticamente', type: 'checkbox', width: 'half' },
  ],
  pagamenti: [],
  notifiche: [],
  backup: [],
  calendari: [],
}
