"""I caratteri che l'editor atti offre, e nient'altro.

Questo elenco stava dentro `pct/template_atti.py`, che in cima importa il
driver di PostgreSQL. Dove quel driver non c'e' — un ambiente di prova, una
macchina di sviluppo, un'immagine ridotta — il modulo non si carica,
l'importazione fedele non trova il catalogo e ripiega su tre soli caratteri:
ogni atto torna in Times New Roman o in Arial, qualunque cosa dichiari il
documento. Un elenco di caratteri non deve dipendere dal database.

Qui non si importa niente: e' un dato, e chi lo usa non paga il prezzo di
tirarsi dietro mezzo applicativo.
"""

from __future__ import annotations

from typing import Dict

EDITOR_FONT_CATALOG: Dict[str, Dict[str, str]] = {
    "source_serif": {
        "label": "Source Serif 4",
        "css_stack": "'Source Serif 4', Georgia, 'Times New Roman', serif",
        "docx_family": "Source Serif 4",
        "pdf_family": "times",
        "rtf_family": "Times New Roman",
        "category": "classico",
        "tone": "serif",
    },
    "merriweather": {
        "label": "Merriweather",
        "css_stack": "Merriweather, Georgia, 'Times New Roman', serif",
        "docx_family": "Merriweather",
        "pdf_family": "times",
        "rtf_family": "Times New Roman",
        "category": "giudiziario",
        "tone": "serif",
    },
    "libre_baskerville": {
        "label": "Libre Baskerville",
        "css_stack": "'Libre Baskerville', Georgia, 'Times New Roman', serif",
        "docx_family": "Libre Baskerville",
        "pdf_family": "times",
        "rtf_family": "Times New Roman",
        "category": "classico",
        "tone": "serif",
    },
    "spectral": {
        "label": "Spectral",
        "css_stack": "'Spectral', Georgia, 'Times New Roman', serif",
        "docx_family": "Spectral",
        "pdf_family": "times",
        "rtf_family": "Times New Roman",
        "category": "contrattuale",
        "tone": "serif",
    },
    "crimson_text": {
        "label": "Crimson Text",
        "css_stack": "'Crimson Text', Georgia, 'Times New Roman', serif",
        "docx_family": "Crimson Text",
        "pdf_family": "times",
        "rtf_family": "Times New Roman",
        "category": "classico",
        "tone": "serif",
    },
    "times_new_roman": {
        "label": "Times New Roman",
        "css_stack": "'Times New Roman', Times, serif",
        "docx_family": "Times New Roman",
        "pdf_family": "times",
        "rtf_family": "Times New Roman",
        "category": "giudiziario",
        "tone": "serif",
    },
    "garamond": {
        "label": "Garamond",
        "css_stack": "Garamond, 'EB Garamond', Georgia, serif",
        "docx_family": "Garamond",
        "pdf_family": "times",
        "rtf_family": "Times New Roman",
        "category": "classico",
        "tone": "serif",
    },
    "inter": {
        "label": "Inter",
        "css_stack": "'Inter', Arial, Helvetica, sans-serif",
        "docx_family": "Inter",
        "pdf_family": "helvetica",
        "rtf_family": "Arial",
        "category": "moderno",
        "tone": "sans",
    },
    "manrope": {
        "label": "Manrope",
        "css_stack": "'Manrope', Arial, Helvetica, sans-serif",
        "docx_family": "Manrope",
        "pdf_family": "helvetica",
        "rtf_family": "Arial",
        "category": "moderno",
        "tone": "sans",
    },
    "aptos": {
        "label": "Aptos",
        "css_stack": "Aptos, Calibri, Arial, Helvetica, sans-serif",
        "docx_family": "Aptos",
        "pdf_family": "helvetica",
        "rtf_family": "Arial",
        "category": "moderno",
        "tone": "sans",
    },
    "arial": {
        "label": "Arial",
        "css_stack": "Arial, Helvetica, sans-serif",
        "docx_family": "Arial",
        "pdf_family": "helvetica",
        "rtf_family": "Arial",
        "category": "moderno",
        "tone": "sans",
    },
    "calibri": {
        "label": "Calibri",
        "css_stack": "Calibri, Aptos, Arial, Helvetica, sans-serif",
        "docx_family": "Calibri",
        "pdf_family": "helvetica",
        "rtf_family": "Arial",
        "category": "moderno",
        "tone": "sans",
    },
    "cambria": {
        "label": "Cambria",
        "css_stack": "Cambria, Georgia, 'Times New Roman', serif",
        "docx_family": "Cambria",
        "pdf_family": "times",
        "rtf_family": "Times New Roman",
        "category": "giudiziario",
        "tone": "serif",
    },
    "verdana": {
        "label": "Verdana",
        "css_stack": "Verdana, Geneva, Arial, Helvetica, sans-serif",
        "docx_family": "Verdana",
        "pdf_family": "helvetica",
        "rtf_family": "Arial",
        "category": "moderno",
        "tone": "sans",
    },
    "courier_new": {
        "label": "Courier New",
        "css_stack": "'Courier New', Courier, monospace",
        "docx_family": "Courier New",
        "pdf_family": "courier",
        "rtf_family": "Courier New",
        "category": "placeholder",
        "tone": "mono",
    },
    "ibm_plex_mono": {
        "label": "IBM Plex Mono",
        "css_stack": "'IBM Plex Mono', 'Courier New', monospace",
        "docx_family": "IBM Plex Mono",
        "pdf_family": "courier",
        "rtf_family": "Courier New",
        "category": "placeholder",
        "tone": "mono",
    },
    # ------------------------------------------------------------------
    # Corredo di Microsoft Word
    #
    # Un atto che arriva dallo studio di controparte, dalla cancelleria o da un
    # consulente e' scritto quasi sempre con uno di questi. Dichiararli qui
    # serve all'importazione fedele: un carattere non dichiarato ricadrebbe su
    # un ripiego e l'avvocato vedrebbe l'atto cambiare aspetto.
    # ------------------------------------------------------------------
    "georgia": {
        "label": "Georgia",
        "css_stack": "Georgia, 'Times New Roman', serif",
        "docx_family": "Georgia",
        "pdf_family": "times",
        "rtf_family": "Georgia",
        "category": "classico",
        "tone": "serif",
    },
    "book_antiqua": {
        "label": "Book Antiqua",
        "css_stack": "'Book Antiqua', 'Palatino Linotype', Palatino, serif",
        "docx_family": "Book Antiqua",
        "pdf_family": "times",
        "rtf_family": "Book Antiqua",
        "category": "classico",
        "tone": "serif",
    },
    "palatino_linotype": {
        "label": "Palatino Linotype",
        "css_stack": "'Palatino Linotype', 'Book Antiqua', Palatino, serif",
        "docx_family": "Palatino Linotype",
        "pdf_family": "times",
        "rtf_family": "Palatino Linotype",
        "category": "classico",
        "tone": "serif",
    },
    "bookman_old_style": {
        "label": "Bookman Old Style",
        "css_stack": "'Bookman Old Style', Bookman, serif",
        "docx_family": "Bookman Old Style",
        "pdf_family": "times",
        "rtf_family": "Bookman Old Style",
        "category": "classico",
        "tone": "serif",
    },
    "century_schoolbook": {
        "label": "Century Schoolbook",
        "css_stack": "'Century Schoolbook', 'Century Schoolbook L', serif",
        "docx_family": "Century Schoolbook",
        "pdf_family": "times",
        "rtf_family": "Century Schoolbook",
        "category": "classico",
        "tone": "serif",
    },
    "constantia": {
        "label": "Constantia",
        "css_stack": "Constantia, Georgia, serif",
        "docx_family": "Constantia",
        "pdf_family": "times",
        "rtf_family": "Constantia",
        "category": "classico",
        "tone": "serif",
    },
    "perpetua": {
        "label": "Perpetua",
        "css_stack": "Perpetua, Georgia, serif",
        "docx_family": "Perpetua",
        "pdf_family": "times",
        "rtf_family": "Perpetua",
        "category": "classico",
        "tone": "serif",
    },
    "rockwell": {
        "label": "Rockwell",
        "css_stack": "Rockwell, 'Courier New', serif",
        "docx_family": "Rockwell",
        "pdf_family": "times",
        "rtf_family": "Rockwell",
        "category": "classico",
        "tone": "serif",
    },
    "sylfaen": {
        "label": "Sylfaen",
        "css_stack": "Sylfaen, Georgia, serif",
        "docx_family": "Sylfaen",
        "pdf_family": "times",
        "rtf_family": "Sylfaen",
        "category": "classico",
        "tone": "serif",
    },
    "garamond_mt": {
        "label": "Garamond MT",
        "css_stack": "'Garamond MT', Garamond, Georgia, serif",
        "docx_family": "Garamond MT",
        "pdf_family": "times",
        "rtf_family": "Garamond MT",
        "category": "classico",
        "tone": "serif",
    },
    "baskerville_old": {
        "label": "Baskerville Old Face",
        "css_stack": "'Baskerville Old Face', Baskerville, Georgia, serif",
        "docx_family": "Baskerville Old Face",
        "pdf_family": "times",
        "rtf_family": "Baskerville Old Face",
        "category": "classico",
        "tone": "serif",
    },
    "cambria_math": {
        "label": "Cambria Math",
        "css_stack": "'Cambria Math', Cambria, Georgia, serif",
        "docx_family": "Cambria Math",
        "pdf_family": "times",
        "rtf_family": "Cambria Math",
        "category": "classico",
        "tone": "serif",
    },
    "tahoma": {
        "label": "Tahoma",
        "css_stack": "Tahoma, Verdana, Arial, sans-serif",
        "docx_family": "Tahoma",
        "pdf_family": "helvetica",
        "rtf_family": "Tahoma",
        "category": "moderno",
        "tone": "sans",
    },
    "segoe_ui": {
        "label": "Segoe UI",
        "css_stack": "'Segoe UI', Tahoma, Arial, sans-serif",
        "docx_family": "Segoe UI",
        "pdf_family": "helvetica",
        "rtf_family": "Segoe UI",
        "category": "moderno",
        "tone": "sans",
    },
    "trebuchet_ms": {
        "label": "Trebuchet MS",
        "css_stack": "'Trebuchet MS', Tahoma, Arial, sans-serif",
        "docx_family": "Trebuchet MS",
        "pdf_family": "helvetica",
        "rtf_family": "Trebuchet MS",
        "category": "moderno",
        "tone": "sans",
    },
    "century_gothic": {
        "label": "Century Gothic",
        "css_stack": "'Century Gothic', 'Apple Gothic', Arial, sans-serif",
        "docx_family": "Century Gothic",
        "pdf_family": "helvetica",
        "rtf_family": "Century Gothic",
        "category": "moderno",
        "tone": "sans",
    },
    "franklin_gothic": {
        "label": "Franklin Gothic",
        "css_stack": "'Franklin Gothic Book', 'Franklin Gothic', Arial, sans-serif",
        "docx_family": "Franklin Gothic",
        "pdf_family": "helvetica",
        "rtf_family": "Franklin Gothic Book",
        "category": "moderno",
        "tone": "sans",
    },
    "candara": {
        "label": "Candara",
        "css_stack": "Candara, Calibri, Arial, sans-serif",
        "docx_family": "Candara",
        "pdf_family": "helvetica",
        "rtf_family": "Candara",
        "category": "moderno",
        "tone": "sans",
    },
    "corbel": {
        "label": "Corbel",
        "css_stack": "Corbel, Calibri, Arial, sans-serif",
        "docx_family": "Corbel",
        "pdf_family": "helvetica",
        "rtf_family": "Corbel",
        "category": "moderno",
        "tone": "sans",
    },
    "gill_sans_mt": {
        "label": "Gill Sans MT",
        "css_stack": "'Gill Sans MT', 'Gill Sans', Arial, sans-serif",
        "docx_family": "Gill Sans MT",
        "pdf_family": "helvetica",
        "rtf_family": "Gill Sans MT",
        "category": "moderno",
        "tone": "sans",
    },
    "lucida_sans": {
        "label": "Lucida Sans",
        "css_stack": "'Lucida Sans', 'Lucida Grande', Arial, sans-serif",
        "docx_family": "Lucida Sans",
        "pdf_family": "helvetica",
        "rtf_family": "Lucida Sans",
        "category": "moderno",
        "tone": "sans",
    },
    "arial_narrow": {
        "label": "Arial Narrow",
        "css_stack": "'Arial Narrow', Arial, sans-serif",
        "docx_family": "Arial Narrow",
        "pdf_family": "helvetica",
        "rtf_family": "Arial Narrow",
        "category": "moderno",
        "tone": "sans",
    },
    "arial_black": {
        "label": "Arial Black",
        "css_stack": "'Arial Black', Arial, sans-serif",
        "docx_family": "Arial Black",
        "pdf_family": "helvetica",
        "rtf_family": "Arial Black",
        "category": "moderno",
        "tone": "sans",
    },
    "impact": {
        "label": "Impact",
        "css_stack": "Impact, 'Arial Black', sans-serif",
        "docx_family": "Impact",
        "pdf_family": "helvetica",
        "rtf_family": "Impact",
        "category": "moderno",
        "tone": "sans",
    },
    "comic_sans_ms": {
        "label": "Comic Sans MS",
        "css_stack": "'Comic Sans MS', 'Comic Sans', cursive, sans-serif",
        "docx_family": "Comic Sans MS",
        "pdf_family": "helvetica",
        "rtf_family": "Comic Sans MS",
        "category": "moderno",
        "tone": "sans",
    },
    "microsoft_sans": {
        "label": "Microsoft Sans Serif",
        "css_stack": "'Microsoft Sans Serif', Arial, sans-serif",
        "docx_family": "Microsoft Sans Serif",
        "pdf_family": "helvetica",
        "rtf_family": "Microsoft Sans Serif",
        "category": "moderno",
        "tone": "sans",
    },
    "bahnschrift": {
        "label": "Bahnschrift",
        "css_stack": "Bahnschrift, 'DIN Alternate', Arial, sans-serif",
        "docx_family": "Bahnschrift",
        "pdf_family": "helvetica",
        "rtf_family": "Bahnschrift",
        "category": "moderno",
        "tone": "sans",
    },
    "ebrima": {
        "label": "Ebrima",
        "css_stack": "Ebrima, 'Segoe UI', Arial, sans-serif",
        "docx_family": "Ebrima",
        "pdf_family": "helvetica",
        "rtf_family": "Ebrima",
        "category": "moderno",
        "tone": "sans",
    },
    "consolas": {
        "label": "Consolas",
        "css_stack": "Consolas, 'Courier New', monospace",
        "docx_family": "Consolas",
        "pdf_family": "courier",
        "rtf_family": "Consolas",
        "category": "placeholder",
        "tone": "mono",
    },
    "lucida_console": {
        "label": "Lucida Console",
        "css_stack": "'Lucida Console', Consolas, 'Courier New', monospace",
        "docx_family": "Lucida Console",
        "pdf_family": "courier",
        "rtf_family": "Lucida Console",
        "category": "placeholder",
        "tone": "mono",
    },
}


#: Le etichette, nell'ordine della tendina.
ETICHETTE_CARATTERI: tuple[str, ...] = tuple(
    str(voce.get("label") or "").strip()
    for voce in EDITOR_FONT_CATALOG.values()
    if str(voce.get("label") or "").strip()
)

#: Da ogni etichetta al suo tono: «serif», «sans» o «mono». Serve a chi deve
#: scegliere il ripiego generico del foglio di stile: un carattere senza grazie
#: che ripiega su `serif` cambia faccia appena manca dal computer di chi legge.
TONO_CARATTERI: Dict[str, str] = {
    str(voce.get("label") or "").strip(): str(voce.get("tone") or "serif").strip().lower()
    for voce in EDITOR_FONT_CATALOG.values()
    if str(voce.get("label") or "").strip()
}

__all__ = ["EDITOR_FONT_CATALOG", "ETICHETTE_CARATTERI", "TONO_CARATTERI"]
