"""Seed operativo della piattaforma legale derivato dalle wave v2 allegate."""

from __future__ import annotations


def _entry(
    code: str,
    name: str,
    *,
    source_wave: str,
    area_label: str,
    subbranch_code: str,
    channel_code: str,
    workflow_code: str,
    complexity_level: str,
    estimated_duration_days: int,
    operational_priority: int,
    registry_code: str = "",
    coverage_mode: str = "OPERATIONAL_READY",
    requires_human_review: bool = True,
    requires_hearing: bool = False,
    requires_registry_enrollment: bool = False,
    allows_settlement: bool = False,
    practice_id: str = "",
    act_compiler_model_code: str = "",
    checklist_template_id: str = "",
    fascicolo_type: str = "",
    tariffario_hint: str = "",
    required_documents: tuple[str, ...] = (),
    checklist: tuple[str, ...] = (),
    deadlines: tuple[str, ...] = (),
    template_labels: tuple[str, ...] = (),
) -> dict[str, object]:
    return {
        "code": code,
        "name": name,
        "source_wave": source_wave,
        "area_label": area_label,
        "subbranch_code": subbranch_code,
        "coverage_mode": coverage_mode,
        "operational_priority": operational_priority,
        "channel_code": channel_code,
        "registry_code": registry_code,
        "workflow_code": workflow_code,
        "complexity_level": complexity_level,
        "estimated_duration_days": estimated_duration_days,
        "requires_human_review": requires_human_review,
        "requires_hearing": requires_hearing,
        "requires_registry_enrollment": requires_registry_enrollment,
        "allows_settlement": allows_settlement,
        "practice_id": practice_id,
        "act_compiler_model_code": act_compiler_model_code,
        "checklist_template_id": checklist_template_id,
        "fascicolo_type": fascicolo_type,
        "tariffario_hint": tariffario_hint,
        "required_documents": list(required_documents),
        "checklist": list(checklist),
        "deadlines": list(deadlines),
        "template_labels": list(template_labels),
    }


LEGAL_PLATFORM_SEED: tuple[dict[str, object], ...] = (
    _entry(
        "PROC_LIC_IMP_001",
        "Impugnazione del licenziamento individuale",
        source_wave="wave1",
        area_label="Lavoro",
        subbranch_code="LAV_CESSAZIONE_IMPUGNAZIONE_LICENZIAMENTO",
        channel_code="PCT_CIVILE",
        registry_code="RG_LAVORO",
        workflow_code="WF_LAVORO_IMPUGNAZIONE_LICENZIAMENTO",
        complexity_level="HIGH",
        estimated_duration_days=180,
        operational_priority=95,
        requires_hearing=True,
        requires_registry_enrollment=True,
        allows_settlement=True,
        practice_id="licenziamento",
        act_compiler_model_code="LAV_IMPLIC_001",
        fascicolo_type="LAVORO",
        tariffario_hint="rito_lavoro",
        required_documents=("Lettera di licenziamento", "Contratto di lavoro", "Buste paga"),
        checklist=("Verificare i termini decadenziali", "Raccogliere la prova documentale", "Impostare tutela reintegratoria o indennitaria"),
        deadlines=("Impugnazione stragiudiziale entro il termine utile", "Ricorso giudiziale dopo l'impugnazione, se necessario"),
        template_labels=("Ricorso ex art. 414 c.p.c.", "Diffida di impugnazione del licenziamento"),
    ),
    _entry(
        "PROC_PRIV_INF_001",
        "Adeguamento informative e basi giuridiche GDPR",
        source_wave="wave1",
        area_label="Privacy e digitale",
        subbranch_code="DIG_PRIVACY_INFORMATIVE_E_BASI_GIURIDICHE",
        channel_code="INTERNO_STUDIO",
        registry_code="INTERNO_STUDIO",
        workflow_code="WF_PRIVACY_INFORMATIVE_GDPR",
        complexity_level="MEDIUM",
        estimated_duration_days=30,
        operational_priority=80,
        allows_settlement=True,
        fascicolo_type="CONSULENZA",
        tariffario_hint="consulenza_compliance",
        required_documents=("Registro trattamenti", "Informative in uso", "Elenco basi giuridiche"),
        checklist=("Mappare trattamenti e finalita", "Verificare basi giuridiche e tempi di conservazione", "Aggiornare informative e registro"),
        deadlines=("Riesame interno del pacchetto privacy prima della consegna",),
        template_labels=("Informativa privacy", "Registro basi giuridiche"),
    ),
    _entry(
        "PROC_PRIV_DB_001",
        "Gestione data breach",
        source_wave="wave1",
        area_label="Privacy e digitale",
        subbranch_code="DIG_PRIVACY_DATA_BREACH",
        channel_code="PROCEDURA_INTERNA_AZIENDALE",
        registry_code="INTERNO_STUDIO",
        workflow_code="WF_PRIVACY_DATA_BREACH",
        complexity_level="HIGH",
        estimated_duration_days=7,
        operational_priority=100,
        fascicolo_type="CONSULENZA",
        tariffario_hint="incident_response",
        required_documents=("Registro incidenti", "Timeline dell'evento", "Valutazione rischio interessati"),
        checklist=("Qualificare l'incidente", "Valutare obbligo di notifica", "Conservare le evidenze di remediation"),
        deadlines=("Notifica al Garante entro 72 ore, se dovuta",),
        template_labels=("Notifica data breach", "Comunicazione agli interessati"),
    ),
    _entry(
        "PROC_231_GAP_001",
        "Gap analysis 231",
        source_wave="wave1",
        area_label="Compliance",
        subbranch_code="COMP_231_GAP_ANALYSIS_231",
        channel_code="PROCEDURA_INTERNA_AZIENDALE",
        registry_code="INTERNO_STUDIO",
        workflow_code="WF_231_GAP_ANALYSIS",
        complexity_level="HIGH",
        estimated_duration_days=60,
        operational_priority=88,
        allows_settlement=True,
        fascicolo_type="CONSULENZA",
        tariffario_hint="assessment_compliance",
        required_documents=("Organigramma", "Procedure interne", "Risk matrix esistente"),
        checklist=("Mappare processi sensibili", "Valutare gap del modello", "Produrre remediation plan"),
        deadlines=("Consegna report al management",),
        template_labels=("Report gap analysis 231",),
    ),
    _entry(
        "PROC_231_MODEL_001",
        "Adozione o aggiornamento Modello 231",
        source_wave="wave1",
        area_label="Compliance",
        subbranch_code="COMP_231_MODELLI_231",
        channel_code="PROCEDURA_INTERNA_AZIENDALE",
        registry_code="INTERNO_STUDIO",
        workflow_code="WF_231_MODEL_UPDATE",
        complexity_level="HIGH",
        estimated_duration_days=90,
        operational_priority=90,
        allows_settlement=True,
        fascicolo_type="CONSULENZA",
        tariffario_hint="modello_231",
        required_documents=("Risk matrix", "Procedure societarie", "Delibera di adozione"),
        checklist=("Aggiornare parte generale e speciale", "Allineare protocolli di controllo", "Preparare delibera finale"),
        deadlines=("Sessione di approvazione e archiviazione corporate",),
        template_labels=("Delibera di adozione Modello 231", "Parte generale del modello"),
    ),
    _entry(
        "PROC_ACC_ATTI_001",
        "Istanza di accesso agli atti",
        source_wave="wave1",
        area_label="Amministrativo",
        subbranch_code="AMM_ACCESSO_ACCESSO_AGLI_ATTI",
        channel_code="PEC_ONLY",
        registry_code="ACCESSO_ATTI",
        workflow_code="WF_ACCESSO_ATTI",
        complexity_level="MEDIUM",
        estimated_duration_days=30,
        operational_priority=82,
        allows_settlement=True,
        practice_id="accesso_atti",
        fascicolo_type="AMMINISTRATIVO",
        tariffario_hint="accesso_documentale",
        required_documents=("Provvedimento o procedimento di interesse", "Delega cliente", "Dati dell'amministrazione"),
        checklist=("Verificare legittimazione e interesse", "Inviare istanza all'amministrazione corretta", "Monitorare silenzio o diniego"),
        deadlines=("Monitorare il termine di risposta dell'amministrazione",),
        template_labels=("Istanza accesso agli atti", "Diffida per silenzio o diniego"),
    ),
    _entry(
        "PROC_PDC_001",
        "Permesso di costruire",
        source_wave="wave1",
        area_label="Urbanistica",
        subbranch_code="URB_URBAN_PERMESSO_DI_COSTRUIRE",
        channel_code="SPORTELLO_PA",
        registry_code="PROTOCOLLO_PA",
        workflow_code="WF_URBANISTICA_PDC",
        complexity_level="HIGH",
        estimated_duration_days=90,
        operational_priority=84,
        requires_registry_enrollment=True,
        allows_settlement=True,
        fascicolo_type="AMMINISTRATIVO",
        tariffario_hint="procedimento_edilizio",
        required_documents=("Titolo di proprieta", "Elaborati tecnici", "Relazione asseverata"),
        checklist=("Verificare stato legittimo", "Comporre kit tecnico-amministrativo", "Monitorare richieste di integrazione"),
        deadlines=("Verifica delle integrazioni richieste dal Comune",),
        template_labels=("Istanza permesso di costruire",),
    ),
    _entry(
        "PROC_PDS_001",
        "Permesso di soggiorno",
        source_wave="wave1",
        area_label="Immigrazione",
        subbranch_code="INT_IMMIGRAZ_PERMESSO_DI_SOGGIORNO",
        channel_code="SPORTELLO_PA",
        registry_code="IMMIGRAZIONE",
        workflow_code="WF_IMMIGRAZIONE_PDS",
        complexity_level="HIGH",
        estimated_duration_days=60,
        operational_priority=86,
        requires_registry_enrollment=True,
        allows_settlement=True,
        practice_id="permesso_soggiorno",
        act_compiler_model_code="IMM_PERMSOG_001",
        fascicolo_type="AMMINISTRATIVO",
        tariffario_hint="immigrazione_permesso",
        required_documents=("Passaporto o documento equipollente", "Permesso scaduto o provvedimento", "Documentazione reddituale o alloggio"),
        checklist=("Verificare titolo di soggiorno richiesto", "Controllare kit documentale", "Monitorare convocazioni di Questura"),
        deadlines=("Presentazione o rinnovo entro i termini del titolo posseduto",),
        template_labels=("Ricorso permesso di soggiorno", "Istanza amministrativa permesso di soggiorno"),
    ),
    _entry(
        "PROC_SAN_RM_001",
        "Valutazione e azione per responsabilita medica",
        source_wave="wave1",
        area_label="Sanitario",
        subbranch_code="SPEC_SAN_RESPONSABILITA_MEDICA",
        channel_code="PCT_CIVILE",
        registry_code="RG_CIVILE",
        workflow_code="WF_SANITARIO_RESPONSABILITA_MEDICA",
        complexity_level="HIGH",
        estimated_duration_days=240,
        operational_priority=87,
        requires_hearing=True,
        requires_registry_enrollment=True,
        allows_settlement=True,
        fascicolo_type="CIVILE",
        tariffario_hint="responsabilita_sanitaria",
        required_documents=("Cartella clinica", "Consulenza medico-legale", "Documenti spesa e danno"),
        checklist=("Acquisire cartella clinica completa", "Valutare profilo di colpa sanitaria", "Stimare danno e strategia"),
        deadlines=("Verificare mediazione o ATP obbligatorio prima dell'azione",),
        template_labels=("Diffida responsabilita medica", "Atto introduttivo responsabilita sanitaria"),
    ),
    _entry(
        "PROC_SOC_DEL_001",
        "Predisposizione delibera societaria",
        source_wave="wave1",
        area_label="Societario",
        subbranch_code="SOC_GOV_DELIBERE_SOCIETARIE",
        channel_code="INTERNO_STUDIO",
        registry_code="INTERNO_STUDIO",
        workflow_code="WF_SOCIETARIO_DELIBERE",
        complexity_level="MEDIUM",
        estimated_duration_days=15,
        operational_priority=78,
        allows_settlement=True,
        practice_id="governance_societaria",
        act_compiler_model_code="SOC_PAR_001",
        fascicolo_type="CONSULENZA",
        tariffario_hint="governance_societaria",
        required_documents=("Statuto", "Libro soci o capitale", "Ordine del giorno"),
        checklist=("Verificare quorum e competenza", "Preparare bozza delibera", "Archiviare verbale e allegati"),
        deadlines=("Formalizzazione e archiviazione della delibera",),
        template_labels=("Delibera societaria", "Verbale assemblea"),
    ),
    _entry(
        "PROC_SOC_PATTI_001",
        "Redazione patto parasociale",
        source_wave="wave2",
        area_label="Societario",
        subbranch_code="SOCIETARIO_CONTRATTI_PATTI_PARASOCIALI",
        channel_code="INTERNO_STUDIO",
        registry_code="INTERNO_STUDIO",
        workflow_code="WF_SOC_PATTI_V1",
        complexity_level="HIGH",
        estimated_duration_days=15,
        operational_priority=85,
        allows_settlement=True,
        act_compiler_model_code="SOC_CONT_001",
        fascicolo_type="CONSULENZA",
        tariffario_hint="contrattualistica_societaria",
        required_documents=("Statuto", "Cap table", "Obiettivi di governance tra soci"),
        checklist=("Definire governance e quorum", "Regolare prelazione, gradimento e deadlock", "Allineare il patto con statuto e patti esistenti"),
        deadlines=("Raccolta firme delle parti e versioning finale",),
        template_labels=("Patto parasociale",),
    ),
    _entry(
        "PROC_SOC_IMP_001",
        "Impugnazione delibera assembleare",
        source_wave="wave2",
        area_label="Societario",
        subbranch_code="SOCIETARIO_ASSEMBLEE_E_IMPUGNAZIONI",
        channel_code="INTERNO_STUDIO",
        registry_code="INTERNO_STUDIO",
        workflow_code="WF_SOC_IMP_001",
        complexity_level="HIGH",
        estimated_duration_days=60,
        operational_priority=88,
        requires_hearing=True,
        requires_registry_enrollment=True,
        allows_settlement=True,
        act_compiler_model_code="SOC_RIC_001",
        fascicolo_type="CIVILE",
        tariffario_hint="contenzioso_societario",
        required_documents=("Verbale assemblea", "Statuto", "Prova della legittimazione del socio"),
        checklist=("Verificare termini di impugnazione", "Qualificare nullita o annullabilita", "Raccogliere documenti societari e convocazione"),
        deadlines=("Impugnazione nel termine previsto per il vizio dedotto",),
        template_labels=("Atto di impugnazione delibera",),
    ),
    _entry(
        "PROC_CCI_NEGO_001",
        "Composizione negoziata della crisi",
        source_wave="wave2",
        area_label="Crisi d'impresa",
        subbranch_code="CRISI_IMPRESA_COMPOSIZIONE_NEGOZIATA",
        channel_code="PORTALE_MINISTERIALE",
        registry_code="CCII",
        workflow_code="WF_CCI_NEGO_001",
        complexity_level="SPECIALIST",
        estimated_duration_days=90,
        operational_priority=90,
        requires_registry_enrollment=True,
        allows_settlement=True,
        fascicolo_type="CONSULENZA",
        tariffario_hint="crisi_impresa",
        required_documents=("Bilanci e situazione economica", "Elenco creditori", "Piano di risanamento preliminare"),
        checklist=("Verificare accesso alla composizione negoziata", "Raccogliere il set documentale CCII", "Coordinare esperto e interlocuzioni"),
        deadlines=("Deposito istanza sul portale nei tempi del piano di crisi",),
        template_labels=("Istanza composizione negoziata",),
    ),
    _entry(
        "PROC_TRIB_RIC_002",
        "Ricorso tributario di primo grado",
        source_wave="wave2",
        area_label="Tributario",
        subbranch_code="TRIB_CONTENZIOSO_RICORSO_PRIMO_GRADO",
        channel_code="PTT_TRIBUTARIO",
        registry_code="PTT_TRIBUTARIO",
        workflow_code="WF_TRIB_RIC_002",
        complexity_level="HIGH",
        estimated_duration_days=75,
        operational_priority=92,
        requires_hearing=True,
        requires_registry_enrollment=True,
        allows_settlement=True,
        practice_id="ricorso_tributario",
        act_compiler_model_code="TRIB_RIC_001",
        checklist_template_id="ricorso_tributario",
        fascicolo_type="TRIBUTARIO",
        tariffario_hint="ricorso_tributario",
        required_documents=("Atto tributario impugnato", "Prova della notifica", "Procura e contributo unificato"),
        checklist=("Verificare termini di impugnazione", "Predisporre NIR e allegati PTT", "Valutare sospensione cautelare"),
        deadlines=("Deposito del ricorso nel termine perentorio",),
        template_labels=("Ricorso tributario", "Istanza cautelare tributaria"),
    ),
    _entry(
        "PROC_TRIB_RISC_001",
        "Istanza di rateizzazione o sospensione riscossione",
        source_wave="wave2",
        area_label="Tributario",
        subbranch_code="TRIB_RISCOSSIONE_RATEIZZAZIONI_E_SOSPENSIONI",
        channel_code="STRAGIUDIZIALE",
        registry_code="RISCOSSIONE",
        workflow_code="WF_TRIB_RISC_001",
        complexity_level="MEDIUM",
        estimated_duration_days=30,
        operational_priority=84,
        allows_settlement=True,
        fascicolo_type="TRIBUTARIO",
        tariffario_hint="istanza_riscossione",
        required_documents=("Cartella o intimazione", "Estratto debitorio", "Prova del pregiudizio"),
        checklist=("Verificare titolo della riscossione", "Impostare domanda di sospensione o rateizzazione", "Monitorare esito dell'ente"),
        deadlines=("Invio dell'istanza prima delle attivita esecutive rilevanti",),
        template_labels=("Istanza rateizzazione", "Istanza sospensione riscossione"),
    ),
    _entry(
        "PROC_APP_GARA_001",
        "Ricorso su gara e aggiudicazione appalto",
        source_wave="wave2",
        area_label="Amministrativo",
        subbranch_code="AMM_APPALTI_GARE_E_AGGIUDICAZIONE",
        channel_code="PAT_AMMINISTRATIVO",
        registry_code="PAT_AMMINISTRATIVO",
        workflow_code="WF_APP_GARA_001",
        complexity_level="SPECIALIST",
        estimated_duration_days=45,
        operational_priority=90,
        requires_hearing=True,
        requires_registry_enrollment=True,
        allows_settlement=True,
        practice_id="ricorso_tar",
        act_compiler_model_code="AMM_RIC_001",
        checklist_template_id="ricorso_tar",
        fascicolo_type="AMMINISTRATIVO",
        tariffario_hint="ricorso_tar_appalti",
        required_documents=("Provvedimento di esclusione o aggiudicazione", "Atti di gara", "Procura e contributo"),
        checklist=("Verificare rito appalti e termini abbreviati", "Raccogliere atti di gara essenziali", "Valutare cautelare e accesso"),
        deadlines=("Ricorso amministrativo nel termine speciale di settore",),
        template_labels=("Ricorso TAR appalti", "Motivi aggiunti appalti"),
    ),
    _entry(
        "PROC_EDIL_SAN_001",
        "Istanza di sanatoria edilizia",
        source_wave="wave2",
        area_label="Edilizia e urbanistica",
        subbranch_code="AMM_EDILIZIA_ABUSI_E_SANATORIE",
        channel_code="SPORTELLO_PA",
        registry_code="PROTOCOLLO_PA",
        workflow_code="WF_EDIL_SAN_001",
        complexity_level="HIGH",
        estimated_duration_days=120,
        operational_priority=86,
        requires_registry_enrollment=True,
        allows_settlement=True,
        fascicolo_type="AMMINISTRATIVO",
        tariffario_hint="sanatoria_edilizia",
        required_documents=("Titoli edilizi", "Stato legittimo", "Elaborati tecnici e fotografie"),
        checklist=("Verificare sanabilita dell'intervento", "Raccogliere relazioni tecniche", "Monitorare integrazioni dell'ente"),
        deadlines=("Presentazione dell'istanza e monitoraggio integrazioni",),
        template_labels=("Istanza sanatoria edilizia",),
    ),
    _entry(
        "PROC_AMB_SANZ_001",
        "Memoria difensiva su sanzione ambientale",
        source_wave="wave2",
        area_label="Ambiente",
        subbranch_code="AMBIENTE_AUTORIZZAZIONI_E_SANZIONI",
        channel_code="AUTORITA_INDIPENDENTE",
        registry_code="AUTORITA_AMBIENTALE",
        workflow_code="WF_AMB_SANZ_001",
        complexity_level="HIGH",
        estimated_duration_days=40,
        operational_priority=82,
        allows_settlement=True,
        fascicolo_type="AMMINISTRATIVO",
        tariffario_hint="sanzione_ambientale",
        required_documents=("Verbale o contestazione", "Autorizzazioni ambientali", "Prove tecniche"),
        checklist=("Verificare fonte sanzionatoria e termini", "Raccogliere autorizzazioni e evidenze", "Predisporre memoria e richieste istruttorie"),
        deadlines=("Deposito memoria entro il termine assegnato dall'autorita",),
        template_labels=("Memoria difensiva ambientale",),
    ),
    _entry(
        "PROC_IP_MARCHI_001",
        "Deposito e tutela marchio",
        source_wave="wave2",
        area_label="Proprieta industriale",
        subbranch_code="IP_MARCHI_DEPOSITO_E_TUTELA",
        channel_code="PORTALE_MINISTERIALE",
        registry_code="MARCHI",
        workflow_code="WF_IP_MARCHI_001",
        complexity_level="MEDIUM",
        estimated_duration_days=30,
        operational_priority=80,
        requires_registry_enrollment=True,
        allows_settlement=True,
        fascicolo_type="CONSULENZA",
        tariffario_hint="marchi_e_brevetti",
        required_documents=("Segno distintivo", "Classi di Nizza", "Report anteriorita"),
        checklist=("Verificare anteriorita e distintivita", "Classificare prodotti e servizi", "Monitorare deposito e opposizioni"),
        deadlines=("Deposito domanda e presidio dei termini di opposizione",),
        template_labels=("Domanda deposito marchio", "Parere anteriorita"),
    ),
    _entry(
        "PROC_CYB_INC_001",
        "Incident response e coordinamento legale cyber",
        source_wave="wave2",
        area_label="Cybersecurity",
        subbranch_code="DIG_CYBERSECURITY_INCIDENT_RESPONSE",
        channel_code="INTERNO_STUDIO",
        registry_code="INTERNO_STUDIO",
        workflow_code="WF_CYB_INC_001",
        complexity_level="SPECIALIST",
        estimated_duration_days=10,
        operational_priority=87,
        allows_settlement=True,
        fascicolo_type="CONSULENZA",
        tariffario_hint="incident_response",
        required_documents=("Incident log", "Matrice impatti", "Piano remediation"),
        checklist=("Qualificare l'incidente cyber", "Valutare obblighi NIS2 e privacy", "Documentare remediation e comunicazioni"),
        deadlines=("Presidio immediato delle notifiche obbligatorie",),
        template_labels=("Notifica incidente cyber", "Memoria interna incident response"),
    ),
    _entry(
        "PROC_LAV_DISC_001",
        "Contestazione disciplinare e gestione procedimento",
        source_wave="wave2",
        area_label="Lavoro",
        subbranch_code="LAV_GESTIONE_DISCIPLINARE",
        channel_code="PEC_ONLY",
        registry_code="LAVORO_DISCIPLINARE",
        workflow_code="WF_LAV_DISC_001",
        complexity_level="HIGH",
        estimated_duration_days=20,
        operational_priority=83,
        allows_settlement=True,
        act_compiler_model_code="LAV_DISC_001",
        fascicolo_type="LAVORO",
        tariffario_hint="disciplinare_lavoro",
        required_documents=("Contestazione disciplinare", "Contratto e policy aziendali", "Eventuali giustificazioni"),
        checklist=("Verificare addebito e termini di difesa", "Predisporre contestazione o memoria", "Gestire audizione e provvedimento finale"),
        deadlines=("Rispetto dei termini della procedura disciplinare",),
        template_labels=("Contestazione disciplinare", "Memoria difensiva disciplinare"),
    ),
    _entry(
        "PROC_CONS_REC_001",
        "Reclamo garanzia e recesso consumatore",
        source_wave="wave2",
        area_label="Consumatori",
        subbranch_code="CONSUMATORI_GARANZIE_E_RECESSO",
        channel_code="STRAGIUDIZIALE",
        registry_code="CONSUMATORI",
        workflow_code="WF_CONS_REC_001",
        complexity_level="MEDIUM",
        estimated_duration_days=20,
        operational_priority=79,
        allows_settlement=True,
        fascicolo_type="STRAGIUDIZIALE",
        tariffario_hint="tutela_consumatore",
        required_documents=("Contratto o ordine", "Prova di acquisto", "Comunicazioni con il venditore"),
        checklist=("Verificare garanzia legale o diritto di recesso", "Predisporre reclamo o diffida", "Valutare soluzione conciliativa"),
        deadlines=("Invio del reclamo e monitoraggio del riscontro",),
        template_labels=("Reclamo consumatore", "Lettera di recesso"),
    ),
)
