"""Fonti ufficiali integrabili nei Template Atti.

Il registro non contiene testo normativo copiato: conserva riferimenti,
ambito, URL ufficiali e criteri di applicazione. Lex e l'editor possono
mostrarli come presidio e proposta redazionale, senza sostituire la verifica
professionale dell'avvocato.
"""
from __future__ import annotations

from typing import Any


LAST_VERIFIED_AT = "2026-06-06"
REGISTRY_VERSION = "2026.06.06.template-fonti-ufficiali.v2"


def _source(
    source_id: str,
    title: str,
    source_title: str,
    article: str,
    official_url: str,
    reason: str,
    terms: tuple[str, ...],
    *,
    status: str = "fonte ufficiale vigente consultata",
    scope: str = "specifica",
    source_type: str = "normativa",
    deprecated: bool = False,
    coverage_role: str = "",
    applies_to_prefixes: tuple[str, ...] = (),
    excludes_terms: tuple[str, ...] = (),
) -> dict[str, Any]:
    if not coverage_role:
        scope_key = scope.casefold()
        type_key = source_type.casefold()
        if scope_key in {"generale", "generale processuale", "sostanziale generale", "base comune"}:
            coverage_role = "base_comune"
        elif type_key in {"telematica", "deontologia", "autorita", "ordinamento professionale"}:
            coverage_role = type_key.replace(" ", "_")
        elif type_key in {"normativa secondaria", "fonte attuativa", "fonte collegata"}:
            coverage_role = "secondaria_collegata"
        else:
            coverage_role = "specifica"
    return {
        "id": source_id,
        "title": title,
        "source_title": source_title,
        "article": article,
        "official_url": official_url,
        "reason_for_application": reason,
        "verification_status": status,
        "last_verified_at": LAST_VERIFIED_AT,
        "scope": scope,
        "source_type": source_type,
        "deprecated": deprecated,
        "coverage_role": coverage_role,
        "match_terms": terms,
        "applies_to_prefixes": applies_to_prefixes,
        "excludes_terms": excludes_terms,
    }


TEMPLATE_ATTI_LEGAL_SOURCES: tuple[dict[str, Any], ...] = (
    _source(
        "normattiva_codice_civile",
        "Codice civile",
        "R.D. 16 marzo 1942, n. 262",
        "codice civile",
        "https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=042U0262&atto.dataPubblicazioneGazzetta=1942-04-04&tipoDettaglio=vigente",
        "Base civilistica generale per contratti, responsabilita, obbligazioni, societa, famiglia e successioni.",
        ("civile", "contratto", "contrattuale", "adempimento", "inadempimento", "responsabilita", "risarcimento", "societario", "famiglia", "succession"),
        scope="generale",
        applies_to_prefixes=("CIV", "STR", "SOC", "LOC", "RCD", "FAM", "VGS"),
    ),
    _source(
        "cc_art_1219_mora",
        "Codice civile - costituzione in mora",
        "Codice civile",
        "art. 1219 c.c.",
        "https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=042U0262&atto.dataPubblicazioneGazzetta=1942-04-04&tipoDettaglio=vigente",
        "Richiamo specifico per diffide, messe in mora, solleciti e richieste di pagamento.",
        ("diffida", "mora", "inadempimento", "pagamento", "sollecito", "invito ad adempiere"),
        applies_to_prefixes=("STR", "BAN", "CON", "LOC", "RCD", "LAV"),
    ),
    _source(
        "normattiva_cpc",
        "Codice di procedura civile",
        "R.D. 28 ottobre 1940, n. 1443",
        "codice di procedura civile",
        "https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=040U1443&atto.dataPubblicazioneGazzetta=1940-10-28&tipoDettaglio=vigente",
        "Base processuale generale per atti civili, cautelari, esecutivi, monitori, lavoro e famiglia davanti al giudice ordinario.",
        ("cpc", "c.p.c", "citazione", "comparsa", "ricorso", "memoria", "appello", "cassazione", "esecuzione", "cautelare", "monitorio"),
        scope="generale processuale",
        applies_to_prefixes=("CIV", "CAU", "ESE", "MON", "GDP", "TMP-CIV", "TMP-CAUT", "TMP-ESE", "LAV", "FAM", "RCD", "CONC"),
    ),
    _source(
        "corte_cassazione_sentenzeweb",
        "Corte di Cassazione - SentenzeWeb",
        "Corte Suprema di Cassazione",
        "banca dati SentenzeWeb e servizi online",
        "https://www.cortedicassazione.it/it/altri_servizi.page?contentId=TGN1864",
        "Fonte giurisprudenziale ufficiale per verificare precedenti, sentenze civili e penali, ordinanze, massime e aggiornamenti della Corte di cassazione prima di consolidare una strategia o un modello.",
        ("cassazione", "sentenzeweb", "sentenza", "ordinanza", "massima", "precedente", "giurisprudenza", "sezioni unite"),
        source_type="autorita",
        coverage_role="autorita",
        applies_to_prefixes=("CIV", "CAU", "ESE", "MON", "GDP", "TMP-CIV", "TMP-CAUT", "TMP-ESE", "LAV", "FAM", "RCD", "CONC", "PEN", "TRIB", "BAN", "SOC", "LOC", "IPD", "IMM"),
    ),
    _source(
        "corte_costituzionale_decisioni",
        "Corte costituzionale - decisioni e pronunce",
        "Corte costituzionale",
        "sentenze, ordinanze e decisioni",
        "https://www.cortecostituzionale.it/decisions",
        "Fonte giurisprudenziale ufficiale per verificare questioni di legittimità costituzionale, pronunce additive/interpretative, ordinanze e impatto su norme applicabili al modello.",
        ("corte costituzionale", "costituzionale", "questione di legittimità", "illegittimità costituzionale", "sentenza costituzionale", "ordinanza costituzionale"),
        source_type="autorita",
        coverage_role="autorita",
        applies_to_prefixes=("CIV", "CAU", "ESE", "MON", "GDP", "TMP-CIV", "TMP-CAUT", "TMP-ESE", "LAV", "FAM", "RCD", "CONC", "PEN", "TRIB", "AMM", "BAN", "SOC", "LOC", "IMM"),
    ),
    _source(
        "pst_banca_dati_pubblica_giurisprudenza_merito",
        "Banca dati pubblica della giurisprudenza di merito",
        "Portale dei Servizi Telematici - Ministero della Giustizia",
        "provvedimenti civili di merito dal 1 gennaio 2016",
        "https://pst.giustizia.it/PST/page/it/operativa_la_banca_dati_pubblica__la_giurisprudenza_di_merito_al_servizio_del_cittadino?contentId=NWS3007&modelId=4",
        "Fonte ministeriale per verificare orientamenti di Tribunali e Corti d'appello quando il modello richiede confronto con prassi di merito o precedenti territoriali.",
        ("giurisprudenza di merito", "tribunale", "corte d'appello", "sentenza di merito", "ordinanza di merito", "provvedimenti civili", "banca dati pubblica"),
        source_type="autorita",
        coverage_role="autorita",
        applies_to_prefixes=("CIV", "CAU", "ESE", "MON", "GDP", "TMP-CIV", "TMP-CAUT", "TMP-ESE", "LAV", "FAM", "RCD", "CONC", "BAN", "SOC", "LOC", "IPD"),
    ),
    _source(
        "giustizia_amministrativa_ricerche_decisioni",
        "Giustizia amministrativa - ricerche decisioni",
        "Consiglio di Stato e TAR",
        "ricerca decisioni, pareri e provvedimenti",
        "https://www.giustizia-amministrativa.it/ricerche2",
        "Fonte giurisprudenziale ufficiale per ricorsi TAR, appelli al Consiglio di Stato, pareri e controllo di precedenti amministrativi.",
        ("giustizia amministrativa", "tar", "consiglio di stato", "cga", "ricorso amministrativo", "appello amministrativo", "decisione amministrativa", "parere"),
        source_type="autorita",
        coverage_role="autorita",
        applies_to_prefixes=("AMM", "TMP-AMM", "APP", "CIV", "IPD", "IMM", "TRIB"),
    ),
    _source(
        "giustizia_tributaria_def_giurisprudenza",
        "Documentazione economica e finanziaria - giurisprudenza tributaria",
        "Dipartimento delle Finanze / Giustizia tributaria",
        "banca dati normativa, prassi e giurisprudenza fiscale",
        "https://def.giustiziatributaria.gov.it/DocTribFrontend/Guida.jsp",
        "Fonte ufficiale per normativa, prassi amministrativa e giurisprudenza tributaria, comprese sentenze delle Corti di giustizia tributaria e massime fiscali.",
        ("giustizia tributaria", "sentenza tributaria", "corte di giustizia tributaria", "def", "cerdef", "prassi fiscale", "giurisprudenza fiscale", "tributi"),
        source_type="autorita",
        coverage_role="autorita",
        applies_to_prefixes=("TRIB", "TMP-TRIB", "CONC", "SOC", "BAN", "CIV"),
    ),
    _source(
        "curia_cgue_giurisprudenza_ue",
        "CURIA - giurisprudenza dell'Unione europea",
        "Corte di giustizia dell'Unione europea",
        "sentenze, ordinanze, pareri e conclusioni",
        "https://curia.europa.eu/site/jcms/?PortalAction_x_000_userLang=it",
        "Fonte ufficiale per precedenti CGUE/Tribunale UE, rinvii pregiudiziali, interpretazione del diritto UE e coordinamento con normativa nazionale.",
        ("curia", "cgue", "corte di giustizia", "tribunale ue", "rinvio pregiudiziale", "diritto ue", "ecli", "sentenza ue"),
        source_type="autorita",
        coverage_role="autorita",
        applies_to_prefixes=("CIV", "TRIB", "BAN", "CON", "IPD", "IMM", "LAV", "FAM", "SOC", "ADR"),
    ),
    _source(
        "hudoc_cedu_giurisprudenza",
        "HUDOC - giurisprudenza CEDU",
        "Corte europea dei diritti dell'uomo",
        "sentenze, decisioni, casi comunicati, pareri consultivi e sintesi giuridiche",
        "https://www.echr.coe.int/hudoc-database",
        "Fonte ufficiale per giurisprudenza CEDU, violazioni convenzionali, equo processo, tutela diritti fondamentali e argomenti sovranazionali.",
        ("hudoc", "cedu", "corte europea diritti uomo", "diritti umani", "articolo 6", "equo processo", "strasburgo", "convenzione europea"),
        source_type="autorita",
        coverage_role="autorita",
        applies_to_prefixes=("CIV", "PEN", "AMM", "TRIB", "IMM", "FAM", "LAV", "RCD"),
    ),
    _source(
        "eurlex_legislazione_giurisprudenza_ue",
        "EUR-Lex - diritto e giurisprudenza UE",
        "Ufficio delle pubblicazioni dell'Unione europea",
        "legislazione, Gazzetta ufficiale UE e giurisprudenza",
        "https://eur-lex.europa.eu/advanced-search-form.html?locale=it",
        "Fonte ufficiale per regolamenti, direttive, decisioni, consolidamenti, CELEX, Gazzetta ufficiale UE e giurisprudenza UE collegata.",
        ("eur-lex", "celex", "regolamento ue", "direttiva ue", "decisione ue", "gazzetta ufficiale ue", "legislazione europea", "giurisprudenza ue"),
        source_type="autorita",
        coverage_role="autorita",
        applies_to_prefixes=("CIV", "TRIB", "BAN", "CON", "IPD", "IMM", "LAV", "FAM", "SOC", "ADR", "PRI"),
    ),
    _source(
        "cpc_art_163_citazione",
        "Codice di procedura civile - contenuto dell'atto di citazione",
        "Codice di procedura civile",
        "art. 163 c.p.c.",
        "https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=040U1443&atto.dataPubblicazioneGazzetta=1940-10-28&tipoDettaglio=vigente",
        "Controllo specifico per atti introduttivi civili a citazione.",
        ("citazione", "atto di citazione", "vocatio", "convenire"),
        applies_to_prefixes=("CIV_CIT", "CIV_ORD", "RCD", "BAN", "SOC"),
    ),
    _source(
        "cpc_art_167_comparsa",
        "Codice di procedura civile - comparsa di risposta",
        "Codice di procedura civile",
        "art. 167 c.p.c.",
        "https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=040U1443&atto.dataPubblicazioneGazzetta=1940-10-28&tipoDettaglio=vigente",
        "Controllo specifico per comparsa di costituzione, difese, eccezioni, riconvenzionale e chiamata del terzo.",
        ("comparsa", "costituzione", "risposta", "convenuto", "riconvenzionale", "chiamata del terzo"),
        applies_to_prefixes=("CIV_COM", "CIV_ORD", "CIV_IMP"),
    ),
    _source(
        "cpc_art_171_ter_memorie",
        "Codice di procedura civile - memorie integrative Cartabia",
        "Codice di procedura civile",
        "art. 171-ter c.p.c.",
        "https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=040U1443&atto.dataPubblicazioneGazzetta=1940-10-28&tipoDettaglio=vigente",
        "Controllo per memorie n. 1, n. 2, n. 3 e scansione pre-udienza nel rito civile riformato.",
        ("171-ter", "memoria n. 1", "memoria n. 2", "memoria n. 3", "deduzioni istruttorie", "memoria istruttoria"),
        applies_to_prefixes=("CIV_ORD", "CIV_SUC"),
    ),
    _source(
        "cpc_rito_semplificato",
        "Codice di procedura civile - rito semplificato",
        "Codice di procedura civile",
        "artt. 281-decies e ss. c.p.c.",
        "https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=040U1443&atto.dataPubblicazioneGazzetta=1940-10-28&tipoDettaglio=vigente",
        "Controllo per ricorsi e atti del rito semplificato di cognizione.",
        ("rito semplificato", "281-decies", "702-bis", "semplificato"),
        applies_to_prefixes=("CIV_INT", "TMP-CIV"),
    ),
    _source(
        "cpc_procedimento_monitorio",
        "Codice di procedura civile - procedimento di ingiunzione",
        "Codice di procedura civile",
        "artt. 633 e ss. c.p.c.",
        "https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=040U1443&atto.dataPubblicazioneGazzetta=1940-10-28&tipoDettaglio=vigente",
        "Controllo specifico per ricorsi per decreto ingiuntivo, opposizioni, prova scritta, provvisoria esecuzione e termini monitori.",
        ("decreto ingiuntivo", "ricorso per decreto ingiuntivo", "monitorio", "ingiunzione", "opposizione a decreto ingiuntivo", "provvisoria esecutorietà"),
        applies_to_prefixes=("MON", "TMP-CAUT"),
    ),
    _source(
        "cpc_procedimenti_cautelari_uniformi",
        "Codice di procedura civile - procedimento cautelare uniforme",
        "Codice di procedura civile",
        "artt. 669-bis e ss. c.p.c.",
        "https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=040U1443&atto.dataPubblicazioneGazzetta=1940-10-28&tipoDettaglio=vigente",
        "Controllo specifico per ricorsi cautelari, reclamo, instaurazione del merito e provvedimenti urgenti.",
        ("cautelare", "ricorso cautelare", "reclamo cautelare", "sequestro", "inaudita altera parte", "provvedimento urgente", "urgenza"),
        applies_to_prefixes=("CAU", "TMP-CAUT"),
    ),
    _source(
        "cpc_art_700_urgenza",
        "Codice di procedura civile - provvedimenti d'urgenza",
        "Codice di procedura civile",
        "art. 700 c.p.c.",
        "https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=040U1443&atto.dataPubblicazioneGazzetta=1940-10-28&tipoDettaglio=vigente",
        "Controllo specifico per ricorsi d'urgenza quando il diritto non è tutelabile utilmente con altro cautelare tipico.",
        ("700", "urgenza", "provvedimento d'urgenza", "ricorso cautelare d'urgenza"),
        applies_to_prefixes=("CAU", "TMP-CAUT"),
    ),
    _source(
        "cpc_sequestri",
        "Codice di procedura civile - sequestri",
        "Codice di procedura civile",
        "artt. 670 e 671 c.p.c.",
        "https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=040U1443&atto.dataPubblicazioneGazzetta=1940-10-28&tipoDettaglio=vigente",
        "Controllo specifico per sequestro giudiziario e conservativo, periculum, fumus e beni da vincolare.",
        ("sequestro conservativo", "sequestro giudiziario", "sequestro"),
        applies_to_prefixes=("CAU", "TMP-CAUT"),
    ),
    _source(
        "cpc_procedimenti_possessori",
        "Codice di procedura civile - procedimenti possessori",
        "Codice di procedura civile",
        "art. 703 c.p.c.",
        "https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=040U1443&atto.dataPubblicazioneGazzetta=1940-10-28&tipoDettaglio=vigente",
        "Controllo specifico per azioni di reintegrazione e manutenzione nel possesso.",
        ("possesso", "possessoria", "manutenzione nel possesso", "reintegrazione nel possesso"),
        applies_to_prefixes=("CIV", "TMP-CAUT"),
    ),
    _source(
        "normattiva_d_lgs_149_2022_cartabia_civile",
        "Riforma civile Cartabia",
        "D.Lgs. 10 ottobre 2022, n. 149",
        "processo civile, famiglia, esecuzione e ADR",
        "https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=22G00158&atto.dataPubblicazioneGazzetta=2022-10-17&tipoDettaglio=originario",
        "Fonte di riforma da richiamare per controlli Cartabia su rito civile, persone, famiglia, esecuzione e ADR.",
        ("cartabia", "riforma civile", "famiglia", "171-ter", "281-decies", "mediazione", "negoziazione assistita", "esecuzione"),
        scope="riforma processuale",
        applies_to_prefixes=("CIV", "CAU", "ESE", "FAM", "ADR", "LAV", "CONC"),
    ),
    _source(
        "normattiva_d_lgs_164_2024_correttivo_cartabia_civile",
        "Correttivo Cartabia civile",
        "D.Lgs. 31 ottobre 2024, n. 164",
        "correttivo processo civile, famiglia, esecuzione e ADR",
        "https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=24G00183&atto.dataPubblicazioneGazzetta=2024-11-11&tipoDettaglio=vigente",
        "Fonte correttiva collegata alla riforma civile Cartabia per controllare rito, decorrenze, famiglia, esecuzione, notifiche e ADR.",
        ("correttivo cartabia", "processo civile", "famiglia", "esecuzione", "negoziazione assistita", "mediazione", "rito"),
        scope="riforma processuale",
        applies_to_prefixes=("CIV", "CAU", "ESE", "FAM", "ADR", "LAV", "CONC"),
    ),
    _source(
        "pst_dm_44_2011",
        "Regole tecniche PCT",
        "D.M. 21 febbraio 2011, n. 44",
        "processo civile telematico",
        "https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto:2011;44!vig=",
        "Presidio tecnico-giuridico per deposito telematico, PEC, comunicazioni e notificazioni nel PCT.",
        ("pct", "pst", "deposito telematico", "datiatto", "busta", "reginde", "processo civile telematico"),
        source_type="telematica",
        applies_to_prefixes=("CIV", "CAU", "ESE", "MON", "GDP", "FAM", "LAV", "RCD", "BAN", "SOC", "IPD", "CONC", "TMP-CIV", "TMP-CAUT", "TMP-ESE", "TMP-FAM", "TMP-LAV", "TMP-NOT", "TMP-PROC"),
    ),
    _source(
        "pst_specifiche_tecniche_pct",
        "Specifiche tecniche PCT/PST",
        "Portale dei Servizi Telematici - Ministero della Giustizia",
        "specifiche tecniche processo telematico",
        "https://pst.giustizia.it/PST/resources/cms/documents/SpecificheTecnicheTestoCoordinatoArticolato.pdf",
        "Fonte tecnica ufficiale per formati, depositi, allegati, busta e controlli telematici PCT.",
        ("pct", "pst", "specifiche tecniche", "deposito", "allegati", "busta", "datiatto", "pdf/a"),
        source_type="telematica",
        applies_to_prefixes=("CIV", "CAU", "ESE", "MON", "GDP", "FAM", "LAV", "CONC", "TMP-CIV", "TMP-CAUT", "TMP-ESE", "TMP-FAM", "TMP-LAV", "TMP-NOT", "TMP-PROC"),
    ),
    _source(
        "pst_dgsia_2024_art_27_attestazione_conformita",
        "Specifiche tecniche DGSIA 2024 - attestazione di conformità",
        "Portale dei Servizi Telematici - Ministero della Giustizia",
        "Provvedimento DGSIA 7 agosto 2024, art. 27",
        "https://pst.giustizia.it/PST/en/paginadettaglio.page?contentId=ACC3429",
        "Fonte tecnica specifica per attestazione di conformità su documento informatico separato e inserimento degli elementi nella relazione di notificazione quando la copia informatica è destinata alla notifica.",
        ("attestazione conformità", "attestazione di conformità", "sentenza", "relata", "notifica", "documento informatico separato", "specifiche tecniche 2024", "art. 27"),
        source_type="telematica",
        applies_to_prefixes=("CIV_NOT", "TMP-NOT", "CIV", "LAV"),
    ),
    _source(
        "normattiva_dm_217_2023_giustizia_telematica",
        "Giustizia digitale - regole tecniche 2023",
        "D.M. 29 dicembre 2023, n. 217",
        "modifiche alle regole tecniche di giustizia telematica",
        "https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=23G00224&atto.dataPubblicazioneGazzetta=2023-12-30&qId=&tipoDettaglio=originario",
        "Fonte attuativa collegata a PCT e processo penale telematico: portale dei depositi telematici, ricevute e adeguamento delle regole tecniche post Cartabia.",
        ("deposito telematico", "portale dei depositi telematici", "giustizia digitale", "dominio giustizia", "ricevuta di accettazione", "regole tecniche"),
        source_type="normativa secondaria",
        applies_to_prefixes=("CIV", "CAU", "ESE", "MON", "GDP", "FAM", "LAV", "PEN", "CONC", "TMP-CIV", "TMP-CAUT", "TMP-ESE", "TMP-FAM", "TMP-LAV", "TMP-NOT", "TMP-PROC"),
    ),
    _source(
        "disp_att_cpc_art_196_quater_deposito_telematico",
        "Disposizioni di attuazione c.p.c. - deposito telematico",
        "R.D. 18 dicembre 1941, n. 1368",
        "art. 196-quater disp. att. c.p.c.",
        "https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:regio.decreto:1941-08-25;1368:1~art196quater=",
        "Fonte collegata per obbligatorietà del deposito telematico, eccezioni e indisponibilità dei sistemi.",
        ("deposito telematico", "obbligatorietà deposito telematico", "sistemi non funzionanti", "modalità non telematiche"),
        source_type="normativa secondaria",
        applies_to_prefixes=("CIV", "CAU", "ESE", "MON", "GDP", "FAM", "LAV", "CONC", "TMP-CIV", "TMP-CAUT", "TMP-ESE", "TMP-FAM", "TMP-LAV", "TMP-NOT", "TMP-PROC"),
    ),
    _source(
        "disp_att_cpc_art_196_undecies_attestazione",
        "Disposizioni di attuazione c.p.c. - attestazione di conformità",
        "R.D. 18 dicembre 1941, n. 1368",
        "art. 196-undecies disp. att. c.p.c.",
        "https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:regio.decreto:1941-08-25;1368:1~art196undecies=",
        "Fonte normativa specifica per modalità e contenuto dell'attestazione di conformità, anche su documento informatico separato secondo specifiche tecniche.",
        ("196-undecies", "attestazione conformità", "attestazione di conformità", "copia informatica", "documento informatico separato", "relata", "notifica sentenza"),
        source_type="normativa secondaria",
        applies_to_prefixes=("CIV_NOT", "TMP-NOT", "CIV", "LAV"),
    ),
    _source(
        "normattiva_dpr_115_2002_spese_giustizia",
        "Testo unico spese di giustizia",
        "D.P.R. 30 maggio 2002, n. 115",
        "contributo unificato e spese di giustizia",
        "https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.presidente.repubblica:2002-05-30;115!vig=",
        "Presidio per contributo unificato, valore causa e spese processuali.",
        ("contributo unificato", "spese di giustizia", "valore causa", "nota iscrizione ruolo"),
        applies_to_prefixes=("CIV", "AMM", "TRIB", "FAM", "LAV", "CONC"),
    ),
    _source(
        "normattiva_legge_53_1994_notifiche",
        "Notificazioni in proprio dell'avvocato",
        "L. 21 gennaio 1994, n. 53",
        "notifiche avvocati e notifiche PEC",
        "https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=094G0076&atto.dataPubblicazioneGazzetta=1994-01-26&tipoDettaglio=vigente",
        "Fonte primaria per notifiche in proprio, relata, attestazioni e prova della notifica PEC.",
        ("notifica", "relata", "notificazione", "pec", "attestazione", "conformita", "consegna", "accettazione"),
        applies_to_prefixes=("CIV_NOT", "STR", "RCD", "AMM", "CON", "BAN", "TMP-NOT"),
    ),
    _source(
        "normattiva_dl_179_2012_art_16_decies_attestazione",
        "D.L. 179/2012 - potere di attestazione del difensore",
        "D.L. 18 ottobre 2012, n. 179",
        "art. 16-decies",
        "https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legge:2012-10-18;179~art16decies=",
        "Fonte specifica per il potere del difensore di attestare la conformità delle copie informatiche estratte dal fascicolo informatico o dai registri telematici.",
        ("16-decies", "attestazione conformità", "attestazione di conformità", "fascicolo informatico", "sentenza", "copia informatica", "notifica"),
        applies_to_prefixes=("CIV_NOT", "TMP-NOT", "CIV", "LAV"),
    ),
    _source(
        "normattiva_cpc_art_285_325_326_sentenza_termine_breve",
        "Codice di procedura civile - notifica sentenza e termine breve",
        "R.D. 28 ottobre 1940, n. 1443",
        "artt. 285, 325 e 326 c.p.c.",
        "https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=040U1443&atto.dataPubblicazioneGazzetta=1940-10-28&tipoDettaglio=vigente",
        "Fonte processuale specifica per notifica della sentenza e decorrenza dei termini brevi di impugnazione.",
        ("sentenza", "notifica sentenza", "termine breve", "decorrenza termini", "impugnazione", "art. 285", "art. 325", "art. 326"),
        applies_to_prefixes=("CIV_NOT", "TMP-NOT", "CIV", "LAV", "FAM"),
    ),
    _source(
        "normattiva_dpr_68_2005_pec",
        "Posta elettronica certificata",
        "D.P.R. 11 febbraio 2005, n. 68",
        "PEC",
        "https://www.normattiva.it/uri-res/N2Ls?urn:nir:presidente.repubblica:decreto:2005-02-11;68=",
        "Fonte primaria per messaggio PEC, ricevute, dati di certificazione, invio e consegna.",
        ("pec", "ricevuta", "accettazione", "consegna", "busta di trasporto", "dati di certificazione"),
        source_type="telematica",
        applies_to_prefixes=("CIV_NOT", "STR", "PRI", "CON", "BAN", "RCD", "TMP-NOT", "TMP-STR"),
    ),
    _source(
        "normattiva_cad_art_48",
        "Codice dell'amministrazione digitale - PEC e recapiti certificati",
        "D.Lgs. 7 marzo 2005, n. 82",
        "art. 48 CAD",
        "https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:2005-03-07;82~art48=",
        "Presidio per trasmissioni telematiche che richiedono ricevuta di invio e consegna.",
        ("cad", "domicilio digitale", "pec", "recapito certificato", "pubblici elenchi"),
        applies_to_prefixes=("CIV_NOT", "AMM", "PRI", "STR", "TMP-NOT", "TMP-STR"),
    ),
    _source(
        "normattiva_cpp",
        "Codice di procedura penale",
        "D.P.R. 22 settembre 1988, n. 447",
        "codice di procedura penale",
        "https://www.normattiva.it/eli/id/1988/10/24/088G0492/CONSOLIDATED",
        "Base processuale per atti penali, istanze, impugnazioni, nomine, querele e costituzione di parte civile.",
        ("penale", "c.p.p", "cpp", "querela", "denuncia", "archiviazione", "incidente probatorio", "parte civile", "impugnazione"),
        scope="generale processuale",
        applies_to_prefixes=("PEN",),
    ),
    _source(
        "normattiva_codice_penale",
        "Codice penale",
        "R.D. 19 ottobre 1930, n. 1398",
        "codice penale",
        "https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=030U1398&atto.dataPubblicazioneGazzetta=1930-10-26&tipoDettaglio=vigente",
        "Fonte sostanziale generale da richiamare quando l'atto penale richiede qualificazione giuridica del fatto.",
        ("reato", "codice penale", "delitto", "contravvenzione", "querela", "denuncia", "parte civile"),
        scope="sostanziale generale",
        applies_to_prefixes=("PEN",),
    ),
    _source(
        "pst_pdp_penale",
        "Portale deposito atti penali",
        "Portale Servizi Telematici - Ministero della Giustizia",
        "PDP/PPT",
        "https://pst.giustizia.it/PST/resources/cms/documents/Specifiche_Tecniche_PPT_11.07.2023_post_DM_2023_signed.pdf",
        "Fonte tecnica ufficiale per deposito penale telematico e atti difensivi su portale.",
        ("pdp", "ppt", "deposito penale", "portale deposito atti penali", "atto penale telematico"),
        source_type="telematica",
        applies_to_prefixes=("PEN",),
    ),
    _source(
        "normattiva_d_lgs_150_2022_cartabia_penale",
        "Riforma penale Cartabia",
        "D.Lgs. 10 ottobre 2022, n. 150",
        "processo penale",
        "https://www.normattiva.it/eli/id/2022/10/17/22G00159/ORIGINAL",
        "Fonte di riforma per controlli su atti penali, impugnazioni e deposito telematico penale.",
        ("cartabia penale", "riforma penale", "penale", "impugnazione", "querela"),
        scope="riforma processuale",
        applies_to_prefixes=("PEN",),
    ),
    _source(
        "pst_specifiche_penale_2024",
        "Specifiche tecniche deposito penale telematico",
        "Portale dei Servizi Telematici - Ministero della Giustizia",
        "specifiche tecniche D.M. 44/2011 aggiornate 2024",
        "https://pst.giustizia.it/PST/resources/cms/documents/m_dg.DOG07.07082024.0004292.ID_SPECIFICHETECNICHE_DM_44_2011_FINALE_31_.pdf",
        "Fonte tecnica collegata per deposito penale telematico, autenticazione, formato atti, richiesta copie e servizi del dominio giustizia.",
        ("deposito penale", "processo penale telematico", "specifiche tecniche", "portale depositi telematici", "richiesta copie"),
        source_type="telematica",
        coverage_role="secondaria_collegata",
        applies_to_prefixes=("PEN",),
    ),
    _source(
        "normattiva_cpa",
        "Codice del processo amministrativo",
        "D.Lgs. 2 luglio 2010, n. 104",
        "codice del processo amministrativo",
        "https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:2010-07-02;104@originale=",
        "Base processuale per ricorsi TAR, Consiglio di Stato, motivi aggiunti, cautelari, silenzio e ottemperanza.",
        ("amministrativo", "tar", "consiglio di stato", "motivi aggiunti", "ottemperanza", "accesso agli atti", "silenzio"),
        applies_to_prefixes=("AMM", "TMP-AMM"),
    ),
    _source(
        "giustizia_amministrativa_pat",
        "Processo amministrativo telematico",
        "Giustizia Amministrativa",
        "regole tecnico-operative PAT",
        "https://www.giustizia-amministrativa.it/documents/20142/74204502/Pubblicazione%2BRegole%2Btecnico-operative%2BPAT.pdf/db2b8d35-4e88-c32a-a7c6-15715348d34b?t=1748969121419",
        "Fonte ufficiale per deposito, moduli e regole tecnico-operative PAT.",
        ("pat", "siga", "processo amministrativo telematico", "modulo deposito", "tar"),
        source_type="telematica",
        applies_to_prefixes=("AMM", "TMP-AMM"),
    ),
    _source(
        "normattiva_decreto_22_05_2020_pat",
        "Regole tecnico-operative PAT",
        "Decreto Presidente Consiglio di Stato 22 maggio 2020",
        "processo amministrativo telematico",
        "https://www.normattiva.it/eli/id/2020/05/27/20A02846/ORIGINAL",
        "Fonte attuativa ufficiale per deposito, moduli, comunicazioni e aggiornamenti del processo amministrativo telematico; sostituisce il precedente impianto del D.P.C.M. 40/2016 nel perimetro PAT.",
        ("pat", "siga", "processo amministrativo telematico", "modulo deposito", "deposito amministrativo", "ricorso tar"),
        source_type="normativa secondaria",
        applies_to_prefixes=("AMM", "TMP-AMM"),
    ),
    _source(
        "giustizia_amministrativa_dpcs_2025_pat",
        "PAT - regole tecnico-operative aggiornate 2025",
        "Giustizia Amministrativa",
        "D.P.C.S. 28 luglio 2021 come modificato dal D.P.C.S. 9 maggio 2025",
        "https://www.giustizia-amministrativa.it/en/-/152174-588",
        "Fonte ufficiale di aggiornamento per accesso ai portali esterni, depositi telematici e decorrenze delle modifiche PAT 2025.",
        ("pat", "processo amministrativo telematico", "regole tecniche-operative", "depositi telematici", "portali esterni"),
        source_type="telematica",
        coverage_role="secondaria_collegata",
        applies_to_prefixes=("AMM", "TMP-AMM"),
    ),
    _source(
        "normattiva_d_lgs_36_2023_appalti",
        "Codice dei contratti pubblici",
        "D.Lgs. 31 marzo 2023, n. 36",
        "contratti pubblici",
        "https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=23G00044&atto.dataPubblicazioneGazzetta=2023-03-31&tipoDettaglio=vigente",
        "Fonte primaria per ricorsi, istanze e pareri in materia di appalti pubblici.",
        ("appalto", "appalti", "gara", "esclusione da gara", "contratti pubblici", "anac", "precontenzioso"),
        applies_to_prefixes=("AMM",),
    ),
    _source(
        "anac_contratti_pubblici_pcp",
        "ANAC - Piattaforma contratti pubblici",
        "Autorita Nazionale Anticorruzione",
        "digitalizzazione contratti pubblici",
        "https://www.anticorruzione.it/-/piattaforma-contratti%20-pubblici",
        "Fonte istituzionale per digitalizzazione del ciclo di vita dei contratti pubblici e PCP.",
        ("pcp", "bdncp", "anac", "digitalizzazione contratti pubblici", "contratti pubblici"),
        source_type="autorita",
        applies_to_prefixes=("AMM",),
    ),
    _source(
        "anac_precontenzioso_2023",
        "ANAC - pareri di precontenzioso",
        "Autorita Nazionale Anticorruzione",
        "delibera ANAC n. 267/2023",
        "https://www.anticorruzione.it/-/regolamento-in-materia-di-pareri-di-precontenzioso-del.-n.-267-20.06.2023",
        "Fonte istituzionale per istanze di parere di precontenzioso sui contratti pubblici.",
        ("precontenzioso", "parere anac", "art. 220", "gara"),
        source_type="autorita",
        applies_to_prefixes=("AMM",),
    ),
    _source(
        "normattiva_d_lgs_546_1992_tributario",
        "Processo tributario",
        "D.Lgs. 31 dicembre 1992, n. 546",
        "contenzioso tributario",
        "https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:1992-12-31;546@originale=",
        "Base processuale per ricorsi, appelli, controdeduzioni, sospensive e memorie tributarie.",
        ("tributario", "corte di giustizia tributaria", "ricorso tributario", "sospensione", "controdeduzioni", "ptt"),
        applies_to_prefixes=("TRIB", "TRI"),
    ),
    _source(
        "giustizia_tributaria_ptt",
        "Processo tributario telematico",
        "Portale Giustizia Tributaria",
        "regole tecniche PTT",
        "https://def.giustiziatributaria.gov.it/DocTribFrontend/executePrintArticolo.do?codiceOrdinamento=0000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000&id=%7B9B8B2F76-C2FF-4972-BD82-69D51FB83CE1%7D&idAttoNormativo=%7B66C2D7E0-5F49-4C3F-9576-B05DFB713A20%7D",
        "Fonte tecnica per deposito e gestione telematica del processo tributario.",
        ("ptt", "sigit", "processo tributario telematico", "deposito tributario"),
        source_type="telematica",
        applies_to_prefixes=("TRIB", "TRI"),
    ),
    _source(
        "normattiva_d_lgs_220_2023_contenzioso_tributario",
        "Riforma contenzioso tributario",
        "D.Lgs. 30 dicembre 2023, n. 220",
        "contenzioso tributario",
        "https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=24G00001&atto.dataPubblicazioneGazzetta=2024-01-03&tipoDettaglio=vigente",
        "Fonte di riforma per atti, modelli e controlli sul processo tributario dopo la delega fiscale.",
        ("contenzioso tributario", "riforma fiscale", "ricorso tributario", "corte di giustizia tributaria", "deposito tributario"),
        scope="riforma processuale",
        applies_to_prefixes=("TRIB", "TRI"),
    ),
    _source(
        "normattiva_dm_163_2013_ptt",
        "Processo tributario telematico - regole",
        "D.M. 23 dicembre 2013, n. 163",
        "regole PTT",
        "https://www.normattiva.it/uri-res/N2Ls?urn:nir:ministero.economia.e.finanze:decreto:2013-12-23;163!vig=",
        "Fonte attuativa per formazione, trasmissione e gestione telematica degli atti del processo tributario.",
        ("ptt", "sigit", "processo tributario telematico", "deposito tributario", "documento informatico", "fascicolo informatico"),
        source_type="normativa secondaria",
        applies_to_prefixes=("TRIB", "TRI"),
    ),
    _source(
        "giustizia_tributaria_decreto_04_08_2015_specifiche_ptt",
        "PTT - specifiche tecniche",
        "Ministero dell'Economia e delle Finanze",
        "Decreto 4 agosto 2015",
        "https://def.giustiziatributaria.gov.it/DocTribFrontend/executePrintArticolo.do?codiceOrdinamento=0000000000000070000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000&id=%7BF26316C7-DFB9-4B44-9972-D2E9A54BCDE3%7D&idAttoNormativo=%7B66C2D7E0-5F49-4C3F-9576-B05DFB713A20%7D",
        "Fonte tecnica ufficiale per controlli SIGIT, anomalie, formati e trasmissione degli atti tributari telematici.",
        ("ptt", "sigit", "specifiche tecniche", "deposito tributario", "anomalie", "trasmissione telematica"),
        source_type="telematica",
        coverage_role="secondaria_collegata",
        applies_to_prefixes=("TRIB", "TRI"),
    ),
    _source(
        "normattiva_d_lgs_28_2010_mediazione",
        "Mediazione civile e commerciale",
        "D.Lgs. 4 marzo 2010, n. 28",
        "mediazione",
        "https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:2010-03-04;28=",
        "Fonte primaria per istanze, inviti, adesioni, verbali e condizione di procedibilita in mediazione.",
        ("mediazione", "mediatore", "organismo", "verbale di accordo", "verbale di mancato accordo"),
        applies_to_prefixes=("ADR", "STR", "CON", "BAN", "FAM"),
    ),
    _source(
        "normattiva_dm_150_2023_mediazione",
        "Mediazione civile - registro, indennità e organismi",
        "D.M. 24 ottobre 2023, n. 150",
        "mediazione civile e commerciale",
        "https://www.normattiva.it/eli/id/2023/10/31/23G00163/CONSOLIDATED/20250124",
        "Fonte attuativa per organismi di mediazione, enti di formazione, indennità, ADR consumo e patrocinio a spese dello Stato in mediazione.",
        ("mediazione", "organismo di mediazione", "indennita mediazione", "registro organismi", "enti formazione", "adr consumo"),
        source_type="normativa secondaria",
        applies_to_prefixes=("ADR", "STR", "CON", "BAN", "FAM"),
    ),
    _source(
        "giustizia_registro_mediazione_dm_150_2023",
        "Registro ministeriale organismi di mediazione",
        "Ministero della Giustizia",
        "registro organismi ed enti mediazione",
        "https://www.giustizia.it/giustizia/page/it/come_fare_per_iscriversi_al_registro_organismi_mediazione",
        "Fonte istituzionale per controllare organismo, ente, formatore, iscrizione e quadro operativo dopo il D.M. 150/2023.",
        ("mediazione", "registro organismi", "organismi mediazione", "enti formazione", "formatori mediazione"),
        source_type="autorita",
        applies_to_prefixes=("ADR", "CON", "BAN", "FAM"),
    ),
    _source(
        "normattiva_dl_132_2014_negoziazione",
        "Negoziazione assistita",
        "D.L. 12 settembre 2014, n. 132",
        "negoziazione assistita",
        "https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto-legge:2014-09-12;132!vig=",
        "Fonte primaria per inviti, accordi, famiglia negoziata e procedura di negoziazione assistita.",
        ("negoziazione", "invito a negoziazione", "accordo di negoziazione", "separazione negoziazione", "divorzio negoziazione"),
        applies_to_prefixes=("ADR", "STR", "FAM"),
    ),
    _source(
        "normattiva_d_lgs_216_2024_correttivo_adr",
        "Correttivo mediazione e negoziazione assistita",
        "D.Lgs. 27 dicembre 2024, n. 216",
        "mediazione civile, commerciale e negoziazione assistita",
        "https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=25G00003&atto.dataPubblicazioneGazzetta=2025-01-10&tipoDettaglio=vigente",
        "Fonte correttiva collegata a D.Lgs. 149/2022, D.Lgs. 28/2010 e D.L. 132/2014 per durata, delega, piattaforma, procura, agevolazioni e negoziazione assistita.",
        ("mediazione", "negoziazione assistita", "correttivo mediazione", "durata mediazione", "piattaforma telematica mediazione", "istruzione stragiudiziale"),
        scope="correttivo ADR",
        source_type="normativa secondaria",
        applies_to_prefixes=("ADR", "STR", "CON", "BAN", "FAM", "RCD"),
    ),
    _source(
        "normattiva_d_lgs_150_2011_riti",
        "Semplificazione dei riti civili",
        "D.Lgs. 1 settembre 2011, n. 150",
        "riti civili speciali",
        "https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=011G0192&atto.dataPubblicazioneGazzetta=2011-09-21&tipoDettaglio=vigente",
        "Fonte per procedimenti civili speciali, opposizioni e materie soggette a rito semplificato speciale.",
        ("rito", "opposizione", "sanzione", "immigrazione", "protezione internazionale", "semplificazione"),
        applies_to_prefixes=("IMM", "CIV", "GDP"),
    ),
    _source(
        "normattiva_legge_898_1970_divorzio",
        "Scioglimento del matrimonio e divorzio",
        "L. 1 dicembre 1970, n. 898",
        "divorzio",
        "https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=070U0898&atto.dataPubblicazioneGazzetta=1970-12-03&currentPage=1",
        "Fonte sostanziale per divorzio congiunto, giudiziale, assegno e modifica condizioni.",
        ("divorzio", "scioglimento matrimonio", "cessazione effetti civili", "assegno divorzile"),
        applies_to_prefixes=("FAM",),
    ),
    _source(
        "normattiva_legge_184_1983_adozione",
        "Adozione e affidamento dei minori",
        "L. 4 maggio 1983, n. 184",
        "adozione e affidamento",
        "https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=083U0184&atto.dataPubblicazioneGazzetta=1983-05-17&tipoDettaglio=vigente",
        "Fonte per tutela del minore, adozione, affidamento e provvedimenti minorili.",
        ("adozione", "affidamento minore", "minore", "curatore speciale", "giudice tutelare"),
        applies_to_prefixes=("FAM", "VGS"),
    ),
    _source(
        "normattiva_d_lgs_154_2013_filiazione",
        "Filiazione e responsabilita genitoriale",
        "D.Lgs. 28 dicembre 2013, n. 154",
        "filiazione",
        "https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:2013;154!vig=",
        "Fonte sostanziale per responsabilita genitoriale, affidamento, mantenimento e provvedimenti sui figli.",
        ("filiazione", "responsabilita genitoriale", "affidamento", "mantenimento figli", "ascolto del minore"),
        applies_to_prefixes=("FAM", "VGS"),
    ),
    _source(
        "normattiva_legge_76_2016_unioni_civili",
        "Unioni civili e convivenze",
        "L. 20 maggio 2016, n. 76",
        "unioni civili e convivenze",
        "https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=16G00082&atto.dataPubblicazioneGazzetta=2016-05-21&tipoDettaglio=vigente",
        "Fonte per accordi, ricorsi e pattuizioni relativi a unioni civili e convivenze.",
        ("unione civile", "convivenza", "conviventi", "coppia"),
        applies_to_prefixes=("FAM", "STR"),
    ),
    _source(
        "normattiva_l_300_1970_statuto_lavoratori",
        "Statuto dei lavoratori",
        "L. 20 maggio 1970, n. 300",
        "rapporti di lavoro",
        "https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=070U0300&atto.dataPubblicazioneGazzetta=1970-05-27&tipoDettaglio=vigente",
        "Fonte generale per tutela del lavoratore, attivita sindacale, controlli e licenziamenti.",
        ("lavoro", "lavoratore", "datore", "licenziamento", "reintegra", "mansioni", "sindacale", "controllo"),
        applies_to_prefixes=("LAV",),
    ),
    _source(
        "normattiva_l_604_1966_licenziamenti",
        "Licenziamenti individuali",
        "L. 15 luglio 1966, n. 604",
        "licenziamento individuale",
        "https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=066U0604&atto.dataPubblicazioneGazzetta=1966-08-06&tipoDettaglio=vigente",
        "Fonte per impugnazioni, diffide e ricorsi relativi a licenziamento individuale.",
        ("licenziamento", "giusta causa", "giustificato motivo", "impugnazione licenziamento"),
        applies_to_prefixes=("LAV",),
    ),
    _source(
        "normattiva_d_lgs_23_2015_tutele_crescenti",
        "Contratto a tutele crescenti",
        "D.Lgs. 4 marzo 2015, n. 23",
        "licenziamento e tutele crescenti",
        "https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=15G00037&atto.dataPubblicazioneGazzetta=2015-03-06&tipoDettaglio=vigente",
        "Fonte per regimi di tutela applicabili ai licenziamenti dei lavoratori assunti nel perimetro Jobs Act.",
        ("tutele crescenti", "licenziamento", "jobs act", "indennita"),
        applies_to_prefixes=("LAV",),
    ),
    _source(
        "normattiva_d_lgs_81_2015_lavoro",
        "Disciplina organica contratti di lavoro",
        "D.Lgs. 15 giugno 2015, n. 81",
        "contratti di lavoro",
        "https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=15G00095&atto.dataPubblicazioneGazzetta=2015-06-24&tipoDettaglio=vigente",
        "Fonte per contratti di lavoro, somministrazione, termine, part-time e profili contrattuali.",
        ("contratto di lavoro", "termine", "part-time", "somministrazione", "mansione"),
        applies_to_prefixes=("LAV",),
    ),
    _source(
        "normattiva_d_lgs_151_2015_dimissioni_telematiche",
        "Semplificazioni lavoro e dimissioni telematiche",
        "D.Lgs. 14 settembre 2015, n. 151",
        "art. 26 dimissioni volontarie e risoluzione consensuale",
        "https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:2015;151=",
        "Fonte settoriale per dimissioni telematiche, revoca e comunicazioni collegate al rapporto di lavoro.",
        ("dimissioni", "risoluzione consensuale", "dimissioni telematiche", "revoca dimissioni", "rapporto di lavoro"),
        scope="specifica lavoro",
        applies_to_prefixes=("LAV",),
    ),
    _source(
        "lavoro_dm_15_12_2015_dimissioni_telematiche",
        "Dimissioni telematiche - modulo e regole tecniche",
        "Ministero del Lavoro e delle Politiche Sociali",
        "D.M. 15 dicembre 2015",
        "https://www.lavoro.gov.it/documenti-e-norme/normative/Documents/2015/Decreto_ministeriale_15_dicembre_2015",
        "Fonte attuativa per modulo, standard tecnici, trasmissione e revoca delle dimissioni volontarie o risoluzioni consensuali.",
        ("dimissioni telematiche", "modulo dimissioni", "revoca dimissioni", "standard tecnici", "ministero lavoro"),
        source_type="normativa secondaria",
        applies_to_prefixes=("LAV",),
    ),
    _source(
        "inl_contestazione_licenziamento_gmo",
        "INL - contestazione licenziamento per giustificato motivo oggettivo",
        "Ispettorato Nazionale del Lavoro",
        "informativa procedura art. 7 L. 604/1966",
        "https://www.ispettorato.gov.it/servizi-e-modulistica/modalita-di-contestazione-del-licenziamento/",
        "Fonte istituzionale per comunicazione preventiva all'Ispettorato e tentativo obbligatorio di conciliazione nei licenziamenti per giustificato motivo oggettivo.",
        ("licenziamento", "giustificato motivo oggettivo", "conciliazione", "ispettorato", "articolo 7"),
        source_type="autorita",
        applies_to_prefixes=("LAV",),
    ),
    _source(
        "normattiva_l_223_1991_licenziamenti_collettivi",
        "Licenziamenti collettivi",
        "L. 23 luglio 1991, n. 223",
        "artt. 4, 5 e 24",
        "https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:legge:1991;223~art24!vig=",
        "Fonte specifica per procedure collettive, comunicazioni sindacali, criteri di scelta e impugnazioni.",
        ("licenziamento collettivo", "mobilita", "procedura collettiva", "criteri di scelta", "riduzione personale"),
        applies_to_prefixes=("LAV",),
    ),
    _source(
        "normattiva_tub_385_1993",
        "Testo unico bancario",
        "D.Lgs. 1 settembre 1993, n. 385",
        "TUB",
        "https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=093G0428&atto.dataPubblicazioneGazzetta=1993-09-30&tipoDettaglio=vigente",
        "Fonte primaria per documentazione bancaria, credito, trasparenza, rapporti bancari e ABF.",
        ("bancario", "banca", "mutuo", "conto corrente", "fideiussione", "centrale rischi", "abf", "intermediario finanziario"),
        applies_to_prefixes=("BAN",),
    ),
    _source(
        "abf_normativa",
        "Arbitro Bancario Finanziario",
        "Banca d'Italia - ABF",
        "disposizioni ABF aggiornate a febbraio 2025",
        "https://www.arbitrobancariofinanziario.it/abf/normativa/index.html",
        "Fonte istituzionale per ricorsi ABF e controversie bancarie stragiudiziali.",
        ("abf", "arbitro bancario", "ricorso abf", "banca d'italia"),
        source_type="autorita",
        applies_to_prefixes=("BAN",),
    ),
    _source(
        "bancaditalia_trasparenza_operazioni_2025",
        "Trasparenza bancaria e correttezza intermediari",
        "Banca d'Italia",
        "Disposizioni di trasparenza aggiornate 2025",
        "https://www.bancaditalia.it/compiti/vigilanza/normativa/archivio-norme/disposizioni/trasparenza_operazioni/2025.02.13/SMDD-Disposizioni-di-trasparenza.pdf",
        "Fonte secondaria di vigilanza per contratti bancari, reclami, informativa precontrattuale, variazioni e correttezza delle relazioni con i clienti.",
        ("trasparenza bancaria", "intermediario", "cliente banca", "reclamo banca", "contratto bancario", "credito", "mutuo"),
        source_type="autorita",
        coverage_role="secondaria_collegata",
        applies_to_prefixes=("BAN",),
    ),
    _source(
        "bancaditalia_abf_disposizioni_2025",
        "ABF - disposizioni procedurali",
        "Banca d'Italia - Arbitro Bancario Finanziario",
        "disposizioni aggiornate a febbraio 2025",
        "https://www.arbitrobancariofinanziario.it/abf/normativa/index.html",
        "Fonte procedurale per competenza ABF, ricorso, reclamo preventivo, termini e documenti della controversia bancaria.",
        ("abf", "ricorso abf", "arbitro bancario", "reclamo banca", "controversia bancaria", "banca d'italia"),
        source_type="autorita",
        applies_to_prefixes=("BAN",),
    ),
    _source(
        "normattiva_tuf_58_1998",
        "Testo unico della finanza",
        "D.Lgs. 24 febbraio 1998, n. 58",
        "TUF",
        "https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=098G0074&atto.dataPubblicazioneGazzetta=1998-03-26&tipoDettaglio=vigente",
        "Fonte per contenzioso finanziario, servizi di investimento, intermediari e obblighi informativi.",
        ("finanziario", "investimento", "intermediario", "consob", "acf", "strumenti finanziari"),
        applies_to_prefixes=("BAN", "SOC"),
    ),
    _source(
        "acf_consob",
        "Arbitro per le Controversie Finanziarie",
        "Consob - ACF",
        "Regolamento ACF",
        "https://www.acf.consob.it/normativa/normativa-acf",
        "Fonte istituzionale per ricorsi ACF e controversie retail su servizi di investimento.",
        ("acf", "arbitro controversie finanziarie", "consob", "investitore retail"),
        source_type="autorita",
        applies_to_prefixes=("BAN", "SOC"),
    ),
    _source(
        "consob_acf_delibere_regolamento_2023",
        "ACF - regolamento e delibere Consob",
        "Consob",
        "Delibere ACF 19602/2016, 21867/2021 e 22721/2023",
        "https://www.acf.consob.it/normativa/normativa-acf",
        "Fonte procedurale Consob per ricorsi ACF, obblighi degli intermediari, condizione di procedibilità e limiti della controversia finanziaria.",
        ("acf", "consob", "ricorso acf", "intermediario finanziario", "investitore retail", "regolamento acf"),
        source_type="autorita",
        applies_to_prefixes=("BAN", "SOC"),
    ),
    _source(
        "normattiva_codice_assicurazioni_209_2005",
        "Codice delle assicurazioni private",
        "D.Lgs. 7 settembre 2005, n. 209",
        "assicurazioni",
        "https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:2005;209",
        "Fonte primaria per sinistri, RC auto, polizze, danneggiati e rapporti assicurativi.",
        ("assicurazione", "assicurativo", "sinistro", "rc auto", "polizza", "ivass"),
        applies_to_prefixes=("RCD",),
    ),
    _source(
        "ivass_arbitro_assicurativo",
        "Arbitro Assicurativo",
        "IVASS",
        "AAS operativo dal 15 gennaio 2026",
        "https://www.ivass.it/consumatori/aas/index.html",
        "Fonte istituzionale per ricorsi e reclami assicurativi dopo reclamo all'impresa o intermediario.",
        ("arbitro assicurativo", "aas", "ivass", "reclamo assicurazione", "sinistro"),
        source_type="autorita",
        applies_to_prefixes=("RCD",),
    ),
    _source(
        "normattiva_dm_215_2024_arbitro_assicurativo",
        "Arbitro Assicurativo - regolamento",
        "D.M. 6 novembre 2024, n. 215",
        "risoluzione stragiudiziale controversie assicurative",
        "https://www.normattiva.it/eli/id/2025/01/09/25G00001/ORIGINAL",
        "Fonte regolamentare per competenza, criteri di svolgimento, composizione e natura delle controversie dell'Arbitro Assicurativo.",
        ("arbitro assicurativo", "aas", "ricorso assicurativo", "reclamo assicurazione", "controversia assicurativa"),
        source_type="normativa secondaria",
        applies_to_prefixes=("RCD",),
    ),
    _source(
        "ivass_provvedimento_106122_2025_aas",
        "AAS - disposizioni tecniche e attuative",
        "IVASS",
        "Provvedimento n. 106122 del 23 maggio 2025",
        "https://www.ivass.it/normativa/nazionale/secondaria-ivass/amministrativi-provv/2025/106122/index.html?dotcache=refresh",
        "Fonte tecnica IVASS per adesione, referenti, mezzi elettronici, procedura e adempimenti dell'Arbitro Assicurativo.",
        ("arbitro assicurativo", "aas", "ivass", "provvedimento 106122", "ricorso assicurativo", "pec arbitro"),
        source_type="autorita",
        coverage_role="secondaria_collegata",
        applies_to_prefixes=("RCD",),
    ),
    _source(
        "normattiva_codice_consumo_206_2005",
        "Codice del consumo",
        "D.Lgs. 6 settembre 2005, n. 206",
        "tutela del consumatore",
        "https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:2005;206!vig=",
        "Fonte primaria per reclami, diffide e azioni su consumo, garanzia, e-commerce e clausole vessatorie.",
        ("consumatore", "garanzia", "e-commerce", "clausole vessatorie", "rimborso", "fornitore", "telefonico", "energia"),
        applies_to_prefixes=("CON",),
    ),
    _source(
        "agcom_conciliaweb",
        "ConciliaWeb",
        "AGCOM",
        "Regolamento controversie utenti/operatori comunicazioni elettroniche",
        "https://www.agcom.it/competenze/consumatori/controversie-tra-utenti-finali-e-fornitori-di-servizi-di-comunicazioni-2023/procedura-di-conciliazione",
        "Fonte istituzionale per reclami e conciliazioni in materia telefonica/comunicazioni elettroniche.",
        ("conciliaweb", "agcom", "operatore telefonico", "telefonico", "comunicazioni elettroniche"),
        source_type="autorita",
        applies_to_prefixes=("CON",),
    ),
    _source(
        "agcom_delibera_203_18_conciliaweb",
        "ConciliaWeb - regolamento controversie comunicazioni",
        "AGCOM",
        "Delibera n. 203/18/CONS",
        "https://www.agcom.it/provvedimenti/delibera-203-18-cons",
        "Fonte regolatoria per tentativo di conciliazione telematica, Co.re.com, provvedimenti temporanei e procedura utenti/operatori.",
        ("conciliaweb", "agcom", "corecom", "controversie utenti operatori", "telefonico", "comunicazioni elettroniche"),
        source_type="autorita",
        coverage_role="secondaria_collegata",
        applies_to_prefixes=("CON",),
    ),
    _source(
        "agcom_delibera_194_23_cons_conciliaweb",
        "ConciliaWeb - modifiche regolamento 2023",
        "AGCOM",
        "Delibera n. 194/23/CONS",
        "https://www.agcom.it/sites/default/files/migration/delibera/Delibera%20194-23-CONS.pdf",
        "Fonte collegata per il quadro aggiornato delle procedure di risoluzione delle controversie tra utenti e operatori di comunicazioni elettroniche.",
        ("conciliaweb", "agcom", "delibera 194/23", "controversie comunicazioni", "utenti operatori"),
        source_type="autorita",
        coverage_role="secondaria_collegata",
        applies_to_prefixes=("CON",),
    ),
    _source(
        "garante_gdpr",
        "GDPR - Garante Privacy",
        "Garante per la protezione dei dati personali",
        "Regolamento (UE) 2016/679",
        "https://www.garanteprivacy.it/regolamentoue",
        "Fonte istituzionale per esercizio diritti, informative, data breach, trattamenti e reclami privacy.",
        ("privacy", "gdpr", "dati personali", "data breach", "profilazione", "informativa", "accesso ai dati", "cancellazione dati"),
        source_type="autorita",
        applies_to_prefixes=("PRI", "IPD", "STR"),
    ),
    _source(
        "garante_cookie_linee_guida_2021",
        "Cookie e altri strumenti di tracciamento",
        "Garante per la protezione dei dati personali",
        "Linee guida 10 giugno 2021",
        "https://www.garanteprivacy.it/web/guest/home/docweb/-/docweb-display/docweb/9677876%26nbsp",
        "Fonte dell'autorità per informativa, consenso, tracciamento, cookie analytics/profilazione e controlli privacy su siti e servizi digitali.",
        ("cookie", "tracciamento", "profilazione", "consenso", "informativa privacy", "sito web"),
        source_type="autorita",
        coverage_role="secondaria_collegata",
        applies_to_prefixes=("PRI", "IPD", "STR"),
    ),
    _source(
        "eurlex_gdpr",
        "Regolamento (UE) 2016/679",
        "EUR-Lex",
        "GDPR",
        "https://eur-lex.europa.eu/eli/reg/2016/679/oj/ita",
        "Fonte UE primaria per basi giuridiche, diritti dell'interessato, informative e responsabilizzazione.",
        ("gdpr", "base giuridica", "trattamento", "interessato", "informativa", "diritti privacy"),
        applies_to_prefixes=("PRI", "IPD", "STR"),
    ),
    _source(
        "normattiva_privacy_196_2003",
        "Codice privacy",
        "D.Lgs. 30 giugno 2003, n. 196",
        "protezione dati personali",
        "https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=003G0218&atto.dataPubblicazioneGazzetta=2003-07-29&tipoDettaglio=vigente",
        "Fonte nazionale coordinata con il GDPR per trattamento dati e tutela dell'interessato.",
        ("privacy", "dati personali", "garante", "trattamento illecito"),
        applies_to_prefixes=("PRI", "IPD"),
    ),
    _source(
        "normattiva_d_lgs_101_2018_adeguamento_gdpr",
        "Adeguamento nazionale al GDPR",
        "D.Lgs. 10 agosto 2018, n. 101",
        "adeguamento Codice privacy al Regolamento UE 2016/679",
        "https://www.normattiva.it/eli/id/2018/09/04/18G00129/CONSOLIDATED/20231130",
        "Fonte di raccordo nazionale tra GDPR e Codice privacy per reclami, informative, diritti e responsabilità del titolare.",
        ("privacy", "gdpr", "adeguamento", "codice privacy", "reclamo garante", "diritti interessato"),
        scope="fonte collegata privacy",
        applies_to_prefixes=("PRI", "IPD"),
    ),
    _source(
        "normattiva_cpi_30_2005",
        "Codice della proprieta industriale",
        "D.Lgs. 10 febbraio 2005, n. 30",
        "proprieta industriale",
        "https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=005G0055&atto.dataPubblicazioneGazzetta=2005-03-04&tipoDettaglio=vigente",
        "Fonte primaria per marchi, brevetti, contraffazione, inibitorie e concorrenza nel perimetro IP.",
        ("marchio", "brevetto", "contraffazione", "proprieta industriale", "inibitoria", "nome a dominio"),
        applies_to_prefixes=("IPD", "SOC"),
    ),
    _source(
        "uibm_deposito_telematico_proprieta_industriale",
        "UIBM - deposito telematico proprieta industriale",
        "Ministero delle Imprese e del Made in Italy - UIBM",
        "servizi online UIBM",
        "https://uibm.mise.gov.it/index.php/it/i-servizi/assistenza-deposito-telmatico",
        "Fonte istituzionale collegata per deposito telematico di marchi, brevetti, disegni, modelli, istanze connesse e rinnovi marchi.",
        ("uibm", "deposito telematico", "marchio", "brevetto", "disegno", "modello", "rinnovo marchio", "proprieta industriale"),
        source_type="autorita",
        coverage_role="secondaria_collegata",
        applies_to_prefixes=("IPD", "SOC"),
    ),
    _source(
        "normattiva_diritto_autore_633_1941",
        "Diritto d'autore",
        "L. 22 aprile 1941, n. 633",
        "diritto d'autore",
        "https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=041U0633&atto.dataPubblicazioneGazzetta=1941-07-16&tipoDettaglio=vigente",
        "Fonte primaria per copyright, plagio, immagini, contenuti web e licenze.",
        ("copyright", "diritto d'autore", "plagio", "immagini", "contenuti web", "software", "licenza"),
        applies_to_prefixes=("IPD",),
    ),
    _source(
        "siae_diritto_autore_repertori",
        "SIAE - diritto d'autore e repertori",
        "Societa Italiana degli Autori ed Editori",
        "tutela e gestione diritti d'autore",
        "https://www.siae.it/it/autori-ed-editori/diritto-autore/",
        "Fonte operativa collegata per gestione collettiva, repertori, utilizzazioni, compensi, deposito opere e verifica pratica dei diritti d'autore.",
        ("siae", "diritto d'autore", "repertorio", "deposito opera", "opera creativa", "compenso autore", "utilizzazione opere"),
        source_type="fonte collegata",
        applies_to_prefixes=("IPD",),
    ),
    _source(
        "normattiva_codice_crisi_14_2019",
        "Codice della crisi d'impresa e dell'insolvenza",
        "D.Lgs. 12 gennaio 2019, n. 14",
        "crisi d'impresa e insolvenza",
        "https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=19G00007&atto.dataPubblicazioneGazzetta=2019-02-14&tipoDettaglio=vigente",
        "Fonte primaria vigente per liquidazione giudiziale, concordato minore, esdebitazione e procedure concorsuali.",
        ("crisi", "insolvenza", "liquidazione giudiziale", "concordato", "esdebitazione", "stato passivo", "curatore"),
        applies_to_prefixes=("CONC", "TMP-IMP"),
    ),
    _source(
        "normattiva_d_lgs_136_2024_correttivo_crisi",
        "Correttivo Codice della crisi d'impresa",
        "D.Lgs. 13 settembre 2024, n. 136",
        "correttivo codice crisi d'impresa e insolvenza",
        "https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=24G00154&atto.dataPubblicazioneGazzetta=2024-09-27&tipoDettaglio=vigente",
        "Fonte correttiva collegata per controllare concordato, liquidazione giudiziale, composizione negoziata, sovraindebitamento, esdebitazione e coordinamento del Codice della crisi.",
        ("crisi", "insolvenza", "correttivo crisi", "concordato", "liquidazione giudiziale", "sovraindebitamento", "esdebitazione"),
        scope="correttivo crisi",
        source_type="normativa secondaria",
        applies_to_prefixes=("CONC", "TMP-IMP"),
    ),
    _source(
        "pst_portale_vendite_pubbliche_specifiche_concorsuali",
        "Portale Vendite Pubbliche e procedure concorsuali",
        "Ministero della Giustizia - Portale dei Servizi Telematici",
        "specifiche tecniche BDAG/PVP",
        "https://pst.giustizia.it/PST/resources/cms/documents/BDAG_ST_V1.2_23092024.pdf",
        "Fonte tecnica collegata per pubblicita delle vendite, flussi telematici e dati delle procedure esecutive e concorsuali nel dominio giustizia.",
        ("portale vendite pubbliche", "pvp", "procedure concorsuali", "vendite", "liquidazione giudiziale", "bdag"),
        source_type="telematica",
        coverage_role="secondaria_collegata",
        applies_to_prefixes=("CONC", "ESE", "TMP-IMP"),
    ),
    _source(
        "normattiva_legge_fallimentare_267_1942_transitoria",
        "Legge fallimentare - solo procedure anteriori/transitorie",
        "R.D. 16 marzo 1942, n. 267",
        "disciplina fallimentare transitoria",
        "https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=042U0267&atto.dataPubblicazioneGazzetta=1942-04-06&tipoDettaglio=vigente",
        "Fonte da usare solo se la pratica riguarda procedure ancora regolate dal regime previgente; per nuove procedure prevale il Codice della crisi.",
        ("fallimento", "legge fallimentare", "procedura fallimentare previgente"),
        status="fonte ufficiale con uso transitorio da verificare",
        scope="transitoria",
        deprecated=True,
        applies_to_prefixes=("CONC",),
    ),
    _source(
        "normattiva_tu_immigrazione_286_1998",
        "Testo unico immigrazione",
        "D.Lgs. 25 luglio 1998, n. 286",
        "immigrazione",
        "https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=098G0348&atto.dataPubblicazioneGazzetta=1998-08-18&tipoDettaglio=vigente",
        "Fonte primaria per permesso di soggiorno, espulsione, ricongiungimento e status dello straniero.",
        ("immigrazione", "permesso di soggiorno", "espulsione", "ricongiungimento", "straniero"),
        applies_to_prefixes=("IMM",),
    ),
    _source(
        "normattiva_d_lgs_25_2008_protezione_internazionale",
        "Procedure per il riconoscimento della protezione internazionale",
        "D.Lgs. 28 gennaio 2008, n. 25",
        "protezione internazionale",
        "https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:2008-01-28;25=",
        "Fonte procedurale specifica per Commissioni territoriali, decisione, ricorso, audizione, videoregistrazione e termini in materia di protezione internazionale.",
        ("protezione internazionale", "commissione territoriale", "richiedente asilo", "ricorso protezione", "audizione", "videoregistrazione"),
        scope="procedura protezione internazionale",
        applies_to_prefixes=("IMM",),
    ),
    _source(
        "interno_protezione_internazionale_commissioni",
        "Ministero dell'Interno - protezione internazionale",
        "Ministero dell'Interno",
        "Commissioni territoriali e Commissione nazionale asilo",
        "https://www.interno.gov.it/it/temi/immigrazione-e-asilo/protezione-internazionale",
        "Fonte istituzionale collegata per inquadramento operativo di status di rifugiato, protezione sussidiaria, Commissioni territoriali e Commissione nazionale.",
        ("protezione internazionale", "ministero interno", "commissione territoriale", "commissione nazionale asilo", "rifugiato", "protezione sussidiaria"),
        source_type="autorita",
        applies_to_prefixes=("IMM",),
    ),
    _source(
        "normattiva_legge_392_1978_locazioni",
        "Locazioni immobili urbani",
        "L. 27 luglio 1978, n. 392",
        "locazioni",
        "https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=078U0392&atto.dataPubblicazioneGazzetta=1978-07-29&tipoDettaglio=vigente",
        "Fonte per sfratti, canoni, morosita e locazioni a uso diverso dall'abitativo.",
        ("locazione", "sfratto", "morosita", "canone", "rilascio immobile"),
        applies_to_prefixes=("LOC", "CIV_SFR", "STR", "TMP-STR"),
    ),
    _source(
        "normattiva_legge_431_1998_locazioni_abitative",
        "Locazioni abitative",
        "L. 9 dicembre 1998, n. 431",
        "locazioni abitative",
        "https://www.normattiva.it/eli/id/1998/12/15/098G0483/CONSOLIDATED",
        "Fonte per locazioni abitative, disdette e richieste di rilascio in materia abitativa.",
        ("locazione abitativa", "rilascio", "disdetta", "canone abitativo"),
        applies_to_prefixes=("LOC", "CIV_SFR", "STR"),
    ),
    _source(
        "agenzia_entrate_rli_locazioni",
        "Agenzia Entrate - RLI Web locazioni",
        "Agenzia delle Entrate",
        "registrazione contratti di locazione e adempimenti successivi",
        "https://apptel.agenziaentrate.gov.it/RliWeb/",
        "Fonte operativa ufficiale per registrazione contratti di locazione, adempimenti successivi, termine di 30 giorni, ricevute e regime della cedolare secca.",
        ("rli", "locazione", "registrazione contratto locazione", "cedolare secca", "imposta di registro", "adempimenti successivi", "proroga", "risoluzione"),
        source_type="autorita",
        coverage_role="secondaria_collegata",
        applies_to_prefixes=("LOC", "CIV_SFR", "STR", "TMP-STR"),
    ),
    _source(
        "normattiva_codice_strada_285_1992",
        "Codice della strada",
        "D.Lgs. 30 aprile 1992, n. 285",
        "circolazione stradale",
        "https://www.normattiva.it/eli/stato/DECRETO_LEGISLATIVO/1992/04/30/285/CONSOLIDATED",
        "Fonte sostanziale per sinistri stradali, opposizioni a verbali e responsabilita da circolazione.",
        ("sinistro stradale", "codice della strada", "verbale", "opposizione sanzione", "rc auto"),
        applies_to_prefixes=("RCD", "GDP"),
    ),
    _source(
        "normattiva_dpr_495_1992_regolamento_codice_strada",
        "Regolamento di esecuzione del Codice della strada",
        "D.P.R. 16 dicembre 1992, n. 495",
        "regolamento di esecuzione e attuazione del Codice della strada",
        "https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.presidente.repubblica:1992;495=",
        "Fonte attuativa collegata per segnaletica, notificazioni, accertamenti, opposizioni a verbali, circolazione e controlli tecnici su sinistri e sanzioni stradali.",
        ("codice della strada", "regolamento esecuzione", "verbale", "segnaletica", "opposizione sanzione", "sinistro stradale"),
        source_type="normativa secondaria",
        applies_to_prefixes=("RCD", "GDP"),
    ),
    _source(
        "normattiva_l_247_2012_ordinamento_forense",
        "Ordinamento della professione forense",
        "L. 31 dicembre 2012, n. 247",
        "ordinamento forense",
        "https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:legge:2012-12-31;247=",
        "Fonte trasversale per incarico, mandato, doveri professionali, compensi, informazione al cliente e responsabilita dell'avvocato.",
        ("avvocato", "mandato", "incarico professionale", "compenso", "cliente", "rinuncia al mandato", "revoca mandato", "deontologia"),
        source_type="ordinamento professionale",
        applies_to_prefixes=("STR_INC", "STR_PREV", "CIV_PROC", "STD", "PRI", "SOC", "STR", "TMP-CIV", "TMP-CAUT", "TMP-ESE", "TMP-FAM", "TMP-LAV", "TMP-NOT", "TMP-PROC", "TMP-STR"),
    ),
    _source(
        "cnf_codice_deontologico_forense",
        "Codice deontologico forense",
        "Consiglio Nazionale Forense",
        "codice deontologico forense",
        "https://codicedeontologico-cnf.it/",
        "Fonte deontologica per doveri di informazione, riservatezza, rapporti con cliente/controparte, compenso, mandato, rinuncia, restituzione documenti e condotta nel processo.",
        ("deontologia", "codice deontologico", "riservatezza", "segreto professionale", "informazione al cliente", "compenso", "mandato", "rinuncia", "restituzione documenti", "controparte"),
        source_type="deontologia",
        applies_to_prefixes=("STR_INC", "STR_PREV", "CIV_PROC", "STD", "PRI", "STR", "SOC", "PEN", "FAM", "LAV", "TMP-CIV", "TMP-CAUT", "TMP-ESE", "TMP-FAM", "TMP-LAV", "TMP-NOT", "TMP-PROC", "TMP-STR"),
    ),
    _source(
        "cnf_cdf_art_24_conflitto_interessi",
        "Codice deontologico forense - conflitto di interessi",
        "Consiglio Nazionale Forense",
        "art. 24 CDF",
        "https://codicedeontologico-cnf.it/voci/art-24-cdf-conflitto-di-interessi/",
        "Presidio per incarichi, procure, difese contro soggetti già assistiti, pratiche familiari e verifiche di conflitto prima dell'accettazione.",
        ("conflitto di interessi", "interessi confliggenti", "parte già assistita", "ex cliente", "curatore speciale", "controparte già assistita"),
        source_type="deontologia",
        applies_to_prefixes=("STD", "STR_INC", "CIV_PROC", "FAM", "PEN"),
    ),
    _source(
        "cnf_cdf_art_25_compensi",
        "Codice deontologico forense - accordi sul compenso",
        "Consiglio Nazionale Forense",
        "art. 25 CDF",
        "https://codicedeontologico-cnf.it/voci/art-25-cdf-accordi-sulla-definizione-del-compenso/",
        "Presidio deontologico per preventivi, patti di compenso, divieto di quota lite sul bene oggetto della lite e accordi economici con il cliente.",
        ("compenso", "preventivo", "onorario", "patto di quota lite", "accordo compenso", "pattuizione compensi"),
        source_type="deontologia",
        applies_to_prefixes=("STR_PREV", "STR_INC", "STD"),
    ),
    _source(
        "gu_cdf_art_25_bis_equo_compenso_2026",
        "Codice deontologico forense - art. 25-bis equo compenso",
        "Gazzetta Ufficiale - comunicato CNF",
        "GU Serie Generale n. 29 del 5 febbraio 2026",
        "https://www.gazzettaufficiale.it/eli/id/2026/02/05/26A00480/SG",
        "Fonte ufficiale della modifica dell'art. 25-bis CDF in materia di equo compenso, efficace dal 7 aprile 2026.",
        ("equo compenso", "25-bis", "cliente forte", "grande impresa", "compenso non equo", "convenzione professionale"),
        status="fonte ufficiale vigente consultata; decorrenza 7 aprile 2026",
        source_type="deontologia",
        applies_to_prefixes=("STR_PREV", "STR_INC", "STD", "SOC"),
    ),
    _source(
        "normattiva_l_49_2023_equo_compenso",
        "Equo compenso prestazioni professionali",
        "L. 21 aprile 2023, n. 49",
        "equo compenso",
        "https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:legge:2023-04-21;49=",
        "Fonte primaria per patti, convenzioni, clienti forti e nullità delle clausole non eque nei rapporti professionali.",
        ("equo compenso", "cliente forte", "grande impresa", "convenzione professionale", "compenso non equo"),
        applies_to_prefixes=("STR_PREV", "STR_INC", "STD", "SOC"),
    ),
    _source(
        "cnf_cdf_art_26_adempimento_mandato",
        "Codice deontologico forense - adempimento del mandato",
        "Consiglio Nazionale Forense",
        "art. 26 CDF",
        "https://codicedeontologico-cnf.it/voci/art-26-cdf-adempimento-del-mandato/",
        "Presidio per accettazione dell'incarico, competenza professionale, atti necessari e prevenzione di ritardi o negligenze nella pratica.",
        ("mandato", "adempimento mandato", "incarico", "competenza professionale", "negligenza", "ritardo", "atti necessari"),
        source_type="deontologia",
        applies_to_prefixes=("STD", "STR_INC", "CIV_PROC", "PEN", "FAM", "LAV", "AMM", "TRI", "TRIB", "TMP-CIV", "TMP-CAUT", "TMP-ESE", "TMP-FAM", "TMP-LAV", "TMP-NOT", "TMP-PROC", "TMP-STR"),
    ),
    _source(
        "cnf_cdf_art_27_informazione_cliente",
        "Codice deontologico forense - doveri di informazione",
        "Consiglio Nazionale Forense",
        "art. 27 CDF",
        "https://codicedeontologico-cnf.it/voci/art-27-cdf-doveri-di-informazione/",
        "Presidio per informativa al cliente su incarico, attività, rischi, costi prevedibili, negoziazione assistita e atti necessari a evitare pregiudizi.",
        ("informazione al cliente", "dovere di informazione", "costo prevedibile", "rischi", "negoziazione assistita", "mandato", "cliente"),
        source_type="deontologia",
        applies_to_prefixes=("STD", "STR_INC", "STR_PREV", "ADR", "FAM", "LAV", "PEN", "AMM", "TRI", "TRIB", "TMP-CIV", "TMP-CAUT", "TMP-ESE", "TMP-FAM", "TMP-LAV", "TMP-NOT", "TMP-PROC", "TMP-STR"),
    ),
    _source(
        "cnf_cdf_art_28_segreto_professionale",
        "Codice deontologico forense - riserbo e segreto professionale",
        "Consiglio Nazionale Forense",
        "art. 28 CDF",
        "https://codicedeontologico-cnf.it/voci/art-28-cdf-riserbo-e-segreto-professionale/",
        "Presidio per riservatezza, segreto professionale, gestione documenti e dati del cliente nei modelli e nelle comunicazioni.",
        ("segreto professionale", "riserbo", "riservatezza", "documenti del cliente", "dati del cliente", "privacy studio"),
        source_type="deontologia",
        applies_to_prefixes=("STD", "STR_INC", "PRI", "PEN", "FAM", "SOC"),
    ),
    _source(
        "cnf_cdf_art_29_richiesta_pagamento",
        "Codice deontologico forense - richiesta di pagamento",
        "Consiglio Nazionale Forense",
        "art. 29 CDF",
        "https://codicedeontologico-cnf.it/voci/art-29-cdf-richiesta-di-pagamento/",
        "Presidio per acconti, anticipi, nota spese, documento fiscale, proporzione del compenso e patrocinio a spese dello Stato.",
        ("pagamento", "acconto", "anticipo", "nota spese", "documento fiscale", "compenso sproporzionato", "patrocinio a spese dello stato"),
        source_type="deontologia",
        applies_to_prefixes=("STR_PREV", "STR_INC", "STD"),
    ),
    _source(
        "gu_cdf_titolo_iv_adr_2025",
        "Codice deontologico forense - Titolo IV e negoziazione assistita",
        "Gazzetta Ufficiale - comunicato CNF",
        "GU Serie Generale n. 202 del 1 settembre 2025",
        "https://www.gazzettaufficiale.it/atto/serie_generale/caricaDettaglioAtto/originario?atto.codiceRedazionale=25A04804&atto.dataPubblicazioneGazzetta=2025-09-01&elenco30giorni=true",
        "Fonte ufficiale delle modifiche agli artt. 48, 50, 51, 56, 61, 62, nuovo 62-bis e Titolo IV su processo e ADR.",
        ("negoziazione assistita", "adr", "processo", "risoluzione alternativa", "titolo iv", "62-bis"),
        status="fonte ufficiale vigente consultata; modifiche pubblicate in GU 1 settembre 2025",
        source_type="deontologia",
        applies_to_prefixes=("ADR", "FAM", "CIV", "LAV", "STR"),
    ),
    _source(
        "cnf_cdf_art_68_ex_cliente",
        "Codice deontologico forense - incarichi contro parte già assistita",
        "Consiglio Nazionale Forense",
        "art. 68 CDF",
        "https://codicedeontologico-cnf.it/voci/art-68-cdf-assunzione-di-incarichi-contro-una-parte-gia-assistita/",
        "Presidio per verificare incarichi contro ex clienti, controversie familiari e incarichi in cui informazioni precedenti possano incidere sulla nuova difesa.",
        ("parte già assistita", "ex cliente", "contro ex cliente", "controparte già assistita", "curatore speciale del minore", "genitore contro l'altro"),
        source_type="deontologia",
        applies_to_prefixes=("FAM", "STD", "STR_INC", "CIV_PROC"),
    ),
    _source(
        "normattiva_dm_55_2014_parametri_forensi",
        "Parametri forensi",
        "D.M. 10 marzo 2014, n. 55, aggiornato dal D.M. 147/2022",
        "compensi avvocato",
        "https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=014G00067&atto.dataPubblicazioneGazzetta=2014-04-02&tipoDettaglio=vigente",
        "Fonte per preventivi, patti, incarichi e valutazione dei compensi professionali.",
        ("preventivo", "compenso", "onorario", "parametri forensi", "incarico"),
        source_type="ordinamento professionale",
        applies_to_prefixes=("STR_PREV", "STR_INC", "STD"),
    ),
)


def _normalise(value: Any) -> str:
    return " ".join(str(value or "").replace("_", " ").split()).casefold()


def _public_row(source: dict[str, Any], confidence: float, match_reason: str) -> dict[str, Any]:
    row = {
        key: value
        for key, value in source.items()
        if key not in {"match_terms", "applies_to_prefixes", "excludes_terms"}
    }
    row["confidence"] = round(confidence, 2)
    row["match_reason"] = match_reason
    row["registry_version"] = REGISTRY_VERSION
    return row


def template_atti_sources_for_model(*, model_code: str = "", model_name: str = "", area: str = "") -> list[dict[str, Any]]:
    """Restituisce le fonti ufficiali coerenti con il modello.

    Il fallback non usa piu' una norma specifica impropria: se non emerge un
    match specifico, vengono restituite fonti generali del processo civile o
    dell'ordinamento forense in base al contesto, con `scope` dichiarato.
    """

    code = str(model_code or "").strip().upper()
    haystack = _normalise(" ".join(str(item or "") for item in (model_code, model_name, area)))
    rows: list[dict[str, Any]] = []
    seen: set[str] = set()

    for source in TEMPLATE_ATTI_LEGAL_SOURCES:
        excludes = tuple(_normalise(item) for item in source.get("excludes_terms", ()))
        if any(item and item in haystack for item in excludes):
            continue
        prefixes = tuple(str(item).upper() for item in source.get("applies_to_prefixes", ()))
        prefix_match = bool(prefixes and code and any(code.startswith(prefix) for prefix in prefixes))
        terms = tuple(_normalise(item) for item in source.get("match_terms", ()))
        term_match = any(term and term in haystack for term in terms)
        if not prefix_match and not term_match:
            continue
        source_id = str(source.get("id") or "")
        if source_id in seen:
            continue
        seen.add(source_id)
        confidence = 0.94 if prefix_match and term_match else 0.88 if prefix_match else 0.82
        reason = "prefisso modello e contenuto" if prefix_match and term_match else "prefisso modello" if prefix_match else "contenuto modello"
        rows.append(_public_row(source, confidence, reason))

    role_order = {
        "specifica": 0,
        "telematica": 1,
        "secondaria_collegata": 1,
        "autorita": 2,
        "deontologia": 2,
        "ordinamento_professionale": 2,
        "base_comune": 5,
    }
    rows.sort(
        key=lambda item: (
            bool(item.get("deprecated")),
            role_order.get(str(item.get("coverage_role") or ""), 3),
            -float(item.get("confidence") or 0),
            str(item.get("id") or ""),
        )
    )
    return rows


def template_atti_source_registry_summary() -> dict[str, Any]:
    by_type: dict[str, int] = {}
    by_scope: dict[str, int] = {}
    by_role: dict[str, int] = {}
    deprecated = 0
    for source in TEMPLATE_ATTI_LEGAL_SOURCES:
        by_type[str(source.get("source_type") or "normativa")] = by_type.get(str(source.get("source_type") or "normativa"), 0) + 1
        by_scope[str(source.get("scope") or "specifica")] = by_scope.get(str(source.get("scope") or "specifica"), 0) + 1
        by_role[str(source.get("coverage_role") or "specifica")] = by_role.get(str(source.get("coverage_role") or "specifica"), 0) + 1
        deprecated += 1 if source.get("deprecated") else 0
    return {
        "registry_version": REGISTRY_VERSION,
        "last_verified_at": LAST_VERIFIED_AT,
        "total_sources": len(TEMPLATE_ATTI_LEGAL_SOURCES),
        "by_type": by_type,
        "by_scope": by_scope,
        "by_role": by_role,
        "deprecated_or_transitional": deprecated,
    }
